#Imports

In [ ]:
import time
import datetime as dt
from datetime import datetime, timedelta
import numpy as np
import yfinance as yf
import random
import pandas as pd
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning) #ignores "Dataframe is highly fragmented" warning.
from sklearn import preprocessing, svm
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (AdaBoostClassifier, RandomForestClassifier,
                              StackingClassifier, HistGradientBoostingClassifier,
                              ExtraTreesClassifier, BaggingClassifier, VotingClassifier)
from matplotlib import pyplot as plt
import math
from dateutil.relativedelta import relativedelta
from typing_extensions import reveal_type
from enum import unique

#Fetching Training Data

In [1]:
import pandas as pd

df_earnings_hist_est_eps = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Earnings_History&Estimates&EPS_trend_Balanced(438,61).csv")
print("df_earnings_hist_est_eps shape:", df_earnings_hist_est_eps.shape)
y_earnings_hist_est_eps = df_earnings_hist_est_eps.pop("label")

df_earnings_hist = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Earnings_History_Balanced(505,17).csv")
print("df_earnings_hist shape:", df_earnings_hist.shape)
y_earnings_hist = df_earnings_hist.pop("label")

df_earnings_hist_est = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Earnings_Estimates_&_History_Balanced(487,41).csv")
print("df_earnings_hist_est shape:", df_earnings_hist_est.shape)
y_earnings_hist_est = df_earnings_hist_est.pop("label")

df_earnings_est = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Earnings_Estimates_Balanced(546,16).csv")
print("df_earnings_est shape:", df_earnings_est.shape)
y_earnings_est = df_earnings_est.pop("label")

df_analystpricetarget_eps = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Analyst_price_targets_&_eps_trend_Balanced(517,22).csv")
print("df_analystpricetarget_eps shape:", df_analystpricetarget_eps.shape)
y_analystpricetarget_eps = df_analystpricetarget_eps.pop("label")

df_income_statement = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/IncomeStatement_Balanced_(1608,31).csv")
print("df_income_statement shape:", df_income_statement.shape)
y_income_statement = df_income_statement.pop("label")

df_balancesheet = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Quarterly_Balancesheet_Balanced(792,34).csv")
print("df_balancesheet shape:", df_balancesheet.shape)
y_balancesheet = df_balancesheet.pop("label")

df_cashflow = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Quarterly_Cashflow_Balanced_(786,6).csv")
print("df_cashflow shape:", df_cashflow.shape)
y_cashflow = df_cashflow.pop("label")

df_rev_est = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Revenue_Estimate_Balanced(367,17).csv")
print("df_rev_est shape:", df_rev_est.shape)
y_rev_est = df_rev_est.pop("label")

df_meta = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Meta Data/MetaData[x3]_balanced(2508, 96).csv")
print("df_meta shape:", df_meta.shape)
y_meta = df_meta.pop("label")

df_final_estimator = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Used for testing/FINAL-ESTIMATOR-TRAINING-DATA-BALANCED-.csv")
df_final_estimator = df_final_estimator.drop(columns = ["Unnamed: 0"])
print("df_final_estimator shape: ", df_final_estimator.shape)
y_final_estimator = df_final_estimator.pop("label")

df_earnings_hist_est_eps shape: (438, 61)
df_earnings_hist shape: (504, 17)
df_earnings_hist_est shape: (486, 41)
df_earnings_est shape: (544, 17)
df_analystpricetarget_eps shape: (516, 22)
df_income_statement shape: (1608, 31)
df_balancesheet shape: (792, 35)
df_cashflow shape: (786, 6)
df_rev_est shape: (366, 17)
df_meta shape: (2508, 96)
df_final_estimator shape:  (1124, 11)

In [2]:
print(f'''
df_earnings_hist_est_eps columns: {df_earnings_hist_est_eps.columns}
df_earnings_hist columns: {df_earnings_hist.columns}
df_earnings_hist_est columns: {df_earnings_hist_est.columns}
df_earnings_est columns: {df_earnings_est.columns}
df_analystpricetarget_eps columns: {df_analystpricetarget_eps.columns}
df_income_statement columns: {df_income_statement.columns}
df_balancesheet columns: {df_balancesheet.columns}
df_cashflow columns: {df_cashflow.columns}
df_rev_est columns: {df_rev_est.columns}
df_meta columns: {df_meta.columns}
df_final_estimator columns: {df_final_estimator.columns}
''')

df_earnings_hist_est_eps columns: Index(['epsActual_1', 'epsEstimate_1', 'epsDifference_1', 'surprisePercent_1',
       'epsActual_2', 'epsEstimate_2', 'epsDifference_2', 'surprisePercent_2',
       'epsActual_3', 'epsEstimate_3', 'epsDifference_3', 'surprisePercent_3',
       'epsActual_4', 'epsEstimate_4', 'epsDifference_4', 'surprisePercent_4',
       'avg_1', 'low_1', 'high_1', 'yearAgoEps_1', 'numberOfAnalysts_1',
       'growth_1', 'avg_2', 'low_2', 'high_2', 'yearAgoEps_2',
       'numberOfAnalysts_2', 'growth_2', 'avg_3', 'low_3', 'high_3',
       'yearAgoEps_3', 'numberOfAnalysts_3', 'growth_3', 'avg_4', 'low_4',
       'high_4', 'yearAgoEps_4', 'numberOfAnalysts_4', 'growth_4', 'current_1',
       '7daysAgo_1', '30daysAgo_1', '60daysAgo_1', '90daysAgo_1', 'current_2',
       '7daysAgo_2', '30daysAgo_2', '60daysAgo_2', '90daysAgo_2', 'current_3',
       '7daysAgo_3', '30daysAgo_3', '60daysAgo_3', '90daysAgo_3', 'current_4',
       '7daysAgo_4', '30daysAgo_4', '60daysAgo_4', '90daysAgo_4'],
      dtype='object')
df_earnings_hist columns: Index(['epsActual_1', 'epsEstimate_1', 'epsDifference_1', 'surprisePercent_1',
       'epsActual_2', 'epsEstimate_2', 'epsDifference_2', 'surprisePercent_2',
       'epsActual_3', 'epsEstimate_3', 'epsDifference_3', 'surprisePercent_3',
       'epsActual_4', 'epsEstimate_4', 'epsDifference_4', 'surprisePercent_4'],
      dtype='object')
df_earnings_hist_est columns: Index(['epsActual_1', 'epsEstimate_1', 'epsDifference_1', 'surprisePercent_1',
       'epsActual_2', 'epsEstimate_2', 'epsDifference_2', 'surprisePercent_2',
       'epsActual_3', 'epsEstimate_3', 'epsDifference_3', 'surprisePercent_3',
       'epsActual_4', 'epsEstimate_4', 'epsDifference_4', 'surprisePercent_4',
       'avg_1', 'low_1', 'high_1', 'yearAgoEps_1', 'numberOfAnalysts_1',
       'growth_1', 'avg_2', 'low_2', 'high_2', 'yearAgoEps_2',
       'numberOfAnalysts_2', 'growth_2', 'avg_3', 'low_3', 'high_3',
       'yearAgoEps_3', 'numberOfAnalysts_3', 'growth_3', 'avg_4', 'low_4',
       'high_4', 'yearAgoEps_4', 'numberOfAnalysts_4', 'growth_4'],
      dtype='object')
df_earnings_est columns: Index(['avg_1', 'low_1', 'high_1', 'numberOfAnalysts_1', 'avg_2', 'low_2',
       'high_2', 'numberOfAnalysts_2', 'avg_3', 'low_3', 'high_3',
       'numberOfAnalysts_3', 'avg_4', 'low_4', 'high_4', 'numberOfAnalysts_4'],
      dtype='object')
df_analystpricetarget_eps columns: Index(['current price', 'current_1', '7daysAgo_1', '30daysAgo_1',
       '60daysAgo_1', '90daysAgo_1', 'current_2', '7daysAgo_2', '30daysAgo_2',
       '60daysAgo_2', '90daysAgo_2', 'current_3', '7daysAgo_3', '30daysAgo_3',
       '60daysAgo_3', '90daysAgo_3', 'current_4', '7daysAgo_4', '30daysAgo_4',
       '60daysAgo_4', '90daysAgo_4'],
      dtype='object')
df_income_statement columns: Index(['Tax Effect Of Unusual Items_1', 'Tax Rate For Calcs_1',
       'Net Income From Continuing Operation Net Minority Interest_1',
       'Normalized Income_1',
       'Net Income From Continuing And Discontinued Operation_1',
       'Net Income Common Stockholders_1', 'Net Income_1',
       'Net Income Including Noncontrolling Interests_1',
       'Net Income Continuous Operations_1', 'Pretax Income_1',
       'Tax Effect Of Unusual Items_3', 'Tax Rate For Calcs_3',
       'Net Income From Continuing Operation Net Minority Interest_3',
       'Normalized Income_3',
       'Net Income From Continuing And Discontinued Operation_3',
       'Net Income Common Stockholders_3', 'Net Income_3',
       'Net Income Including Noncontrolling Interests_3',
       'Net Income Continuous Operations_3', 'Pretax Income_3',
       'Tax Effect Of Unusual Items_4', 'Tax Rate For Calcs_4',
       'Net Income From Continuing Operation Net Minority Interest_4',
       'Normalized Income_4',
       'Net Income From Continuing And Discontinued Operation_4',
       'Net Income Common Stockholders_4', 'Net Income_4',
       'Net Income Including Noncontrolling Interests_4',
       'Net Income Continuous Operations_4', 'Pretax Income_4'],
      dtype='object')
df_balancesheet columns: Index(['Total Liabilities Net Minority Interest_1', 'Total Assets_1',
       'Tangible Book Value_2', 'Net Tangible Assets_2',
       'Common Stock Equity_2', 'Total Equity Gross Minority Interest_2',
       'Stockholders Equity_2', 'Total Liabilities Net Minority Interest_2',
       'Total Assets_2', 'Ordinary Shares Number_3', 'Share Issued_3',
       'Tangible Book Value_3', 'Net Tangible Assets_3',
       'Common Stock Equity_3', 'Total Equity Gross Minority Interest_3',
       'Stockholders Equity_3', 'Total Liabilities Net Minority Interest_3',
       'Total Assets_3', 'Tangible Book Value_4', 'Net Tangible Assets_4',
       'Common Stock Equity_4', 'Total Equity Gross Minority Interest_4',
       'Stockholders Equity_4', 'Total Liabilities Net Minority Interest_4',
       'Total Assets_4', 'Ordinary Shares Number_5', 'Share Issued_5',
       'Tangible Book Value_5', 'Net Tangible Assets_5',
       'Common Stock Equity_5', 'Total Equity Gross Minority Interest_5',
       'Stockholders Equity_5', 'Total Liabilities Net Minority Interest_5',
       'Total Assets_5'],
      dtype='object')
df_cashflow columns: Index(['Free Cash Flow_1', 'Free Cash Flow_2', 'Free Cash Flow_3',
       'Free Cash Flow_4', 'Free Cash Flow_5'],
      dtype='object')
df_rev_est columns: Index(['avg_1', 'low_1', 'high_1', 'numberOfAnalysts_1', 'avg_2', 'low_2',
       'high_2', 'numberOfAnalysts_2', 'avg_3', 'low_3', 'high_3',
       'numberOfAnalysts_3', 'avg_4', 'low_4', 'high_4', 'numberOfAnalysts_4'],
      dtype='object')
df_meta columns: Index(['Tangible Book Value_1', 'Net Tangible Assets_1',
       'Common Stock Equity_1', 'Total Equity Gross Minority Interest_1',
       'Stockholders Equity_1', 'Total Liabilities Net Minority Interest_1',
       'Total Assets_1', 'Tangible Book Value_2', 'Net Tangible Assets_2',
       'Common Stock Equity_2', 'Total Equity Gross Minority Interest_2',
       'Stockholders Equity_2', 'Total Liabilities Net Minority Interest_2',
       'Total Assets_2', 'Ordinary Shares Number_3', 'Share Issued_3',
       'Tangible Book Value_3', 'Net Tangible Assets_3',
       'Common Stock Equity_3', 'Total Equity Gross Minority Interest_3',
       'Stockholders Equity_3', 'Total Liabilities Net Minority Interest_3',
       'Total Assets_3', 'Tangible Book Value_4', 'Net Tangible Assets_4',
       'Common Stock Equity_4', 'Stockholders Equity_4',
       'Total Liabilities Net Minority Interest_4', 'Total Assets_4',
       'Ordinary Shares Number_5', 'Share Issued_5', 'Tangible Book Value_5',
       'Net Tangible Assets_5', 'Common Stock Equity_5',
       'Stockholders Equity_5', 'Total Liabilities Net Minority Interest_5',
       'Total Assets_5', 'Free Cash Flow_1', 'Free Cash Flow_2',
       'Operating Cash Flow_2', 'Free Cash Flow_3', 'Operating Cash Flow_3',
       'Free Cash Flow_4', 'Operating Cash Flow_4', 'Free Cash Flow_5',
       'Operating Cash Flow_5', 'current price', 'current_1', '7daysAgo_1',
       '30daysAgo_1', '60daysAgo_1', '90daysAgo_1', 'current_2', '7daysAgo_2',
       '30daysAgo_2', '60daysAgo_2', '90daysAgo_2', 'current_3', '7daysAgo_3',
       '30daysAgo_3', '60daysAgo_3', '90daysAgo_3', 'current_4', '7daysAgo_4',
       '30daysAgo_4', '60daysAgo_4', '90daysAgo_4', 'avg_1_1', 'low_1_1',
       'high_1_1', 'numberOfAnalysts_1_1', 'avg_2_1', 'low_2_1', 'high_2_1',
       'numberOfAnalysts_2_1', 'avg_3_1', 'low_3_1', 'high_3_1',
       'numberOfAnalysts_3_1', 'avg_4_1', 'low_4_1', 'avg_1_2', 'low_1_2',
       'high_1_2', 'numberOfAnalysts_1_2', 'avg_2_2', 'low_2_2', 'high_2_2',
       'avg_3_2', 'low_3_2', 'high_3_2', 'avg_4_2', 'low_4_2', 'epsEstimate_1',
       'epsActual_4'],
      dtype='object')
df_final_estimator columns: Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='object')

# Algorithms

In [ ]:
GB = HistGradientBoostingClassifier(random_state=1)
BagGB = BaggingClassifier(estimator = GB,  n_estimators = 100, random_state=1)

RF = RandomForestClassifier(random_state=1)

RF2 = RandomForestClassifier(random_state=1)

ADARF = AdaBoostClassifier(estimator = RandomForestClassifier(random_state =1), random_state=1)

ADARF2 = AdaBoostClassifier(estimator = RandomForestClassifier(random_state =1), random_state=1)

ET = ExtraTreesClassifier(random_state=1)

NN = MLPClassifier(solver='adam', alpha=0.1,
                    hidden_layer_sizes=(11, 5),activation = "tanh", random_state=1, max_iter=1000000,  early_stopping=True)
BagNN = BaggingClassifier(estimator = NN,  n_estimators = 10, random_state=1)

vote = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)
vote2 = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)
vote3 = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)
vote4 = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)
vote5 = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)
vote6 = VotingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], voting='soft'
)

stack = StackingClassifier(
    estimators = [('gb', GB), ('rf', RF), ('adarf', ADARF), ('et',ET)], final_estimator=RF
)

QDA = QuadraticDiscriminantAnalysis()

SVM = svm.SVC(random_state=1)

↓ Finds the best random state for the training test split

In [ ]:
# Earnings hist, est, eps trend
clf_earnings_hist_est_eps = RF.fit(df_earnings_hist_est_eps, y_earnings_hist_est_eps)


# Earnings hist, est
clf_earnings_hist_est = vote.fit(df_earnings_hist_est, y_earnings_hist_est)


# Revenue Estimates
clf_rev_est = vote2.fit(df_rev_est, y_rev_est)


# Income Statements
clf_income_statement = vote3.fit(df_income_statement, y_income_statement)


# Balance sheet
clf_balancesheet = vote4.fit(df_balancesheet, y_balancesheet)


# Cashflow
clf_cashflow = stack.fit(df_cashflow, y_cashflow)


# Earnings history
clf_earnings_hist = GB.fit(df_earnings_hist, y_earnings_hist)


# Earnings estimates
clf_earnings_est = ADARF.fit(df_earnings_est, y_earnings_est)


# Analyst Price Targets, eps trend
clf_analystpricetarget_eps = BagGB.fit(df_analystpricetarget_eps, y_analystpricetarget_eps)


# Meta AROUND 58% ACCURACY
clf_meta = ADARF2.fit(df_meta, y_meta)

#Final estimator
clf_final_estimator = vote6.fit(df_final_estimator, y_final_estimator)

Algorithms for each type of fundemental data

In [ ]:
'''
#Earnings hist, est, eps trend
X_train, X_test, y_train, y_test = train_test_split( df_earnings_hist_est_eps, y_earnings_hist_est_eps, random_state=38, test_size=0.05)
clf_earnings_hist_est_eps = RandomForestClassifier(random_state=1).fit(X_train, y_train)
score_earnings_hist_est_eps = clf_earnings_hist_est_eps.score(X_test, y_test)
print("earnings hist, est, and eps trend: ", score_earnings_hist_est_eps)

#Earnings hist, est
X_train, X_test, y_train, y_test = train_test_split( df_earnings_hist_est  , y_earnings_hist_est, random_state=25, test_size=0.05)
clf_earnings_hist_est = vote
clf_earnings_hist_est.fit(X_train, y_train)
score_earnings_hist_est = clf_earnings_hist_est.score(X_test, y_test)
print("earnings hist and est: ", score_earnings_hist_est)

#Earnings history
X_train, X_test, y_train, y_test = train_test_split( df_earnings_hist  , y_earnings_hist, random_state=72, test_size=0.05)
clf_earnings_hist = GB
clf_earnings_hist.fit(X_train, y_train)
score_earnings_hist = clf_earnings_hist.score(X_test, y_test)
print("earnings history: ", score_earnings_hist)

#Earnings estimates
X_train, X_test, y_train, y_test = train_test_split( df_earnings_est  , y_earnings_est, random_state=28, test_size=0.05)
clf_earnings_est = ET
clf_earnings_est.fit(X_train, y_train)
score_earnings_est = clf_earnings_est.score(X_test, y_test)
print("earnings estimates: ", score_earnings_est)

#Analyst Price Targets, eps trend
X_train, X_test, y_train, y_test = train_test_split( df_analystpricetarget_eps  , y_analystpricetarget_eps, random_state=46, test_size=0.05)
clf_analystpricetarget_eps = BagGB
clf_analystpricetarget_eps.fit(X_train, y_train)
score_analystpricetarget_eps = clf_analystpricetarget_eps.score(X_test, y_test)
print("analyst price targets and eps trend: ",score_analystpricetarget_eps)

#Revenue Estimates
X_train, X_test, y_train, y_test = train_test_split( df_rev_est  , y_rev_est, random_state=67, test_size=0.05)
clf_rev_est = vote
clf_rev_est.fit(X_train, y_train)
score_rev_est = clf_rev_est.score(X_test, y_test)
print("revenue estimates: ", score_rev_est)

#Income Statements
X_train, X_test, y_train, y_test = train_test_split( df_income_statement  , y_income_statement, random_state=5, test_size=0.05)
clf_income_statement = vote
clf_income_statement.fit(X_train, y_train)
score_income_statement = clf_income_statement.score(X_test, y_test)
print("income statement: ", score_income_statement)

#Balance sheet
X_train, X_test, y_train, y_test = train_test_split( df_balancesheet  , y_balancesheet, random_state=25, test_size=0.05)
clf_balancesheet = vote
clf_balancesheet.fit(X_train, y_train)
score_balancesheet = clf_balancesheet.score(X_test, y_test)
print("balancesheet: ",score_balancesheet)

#Cashflow
X_train, X_test, y_train, y_test = train_test_split( df_cashflow  , y_cashflow, random_state=21, test_size=0.05)
clf_cashflow = stack
clf_cashflow.fit(X_train, y_train)
score_cashflow = clf_cashflow.score(X_test, y_test)
print("cashflow: ", score_cashflow)

#Meta data is repeated :(
X_train, X_test, y_train, y_test = train_test_split( df_meta  , y_meta, random_state=55, test_size=0.05)
clf_meta = ADARF
clf_meta.fit(X_train, y_train)
score_meta = clf_meta.score(X_test, y_test)
print("meta: ",score_meta)
'''

'\n#Earnings hist, est, eps trend\nX_train, X_test, y_train, y_test = train_test_split( df_earnings_hist_est_eps, y_earnings_hist_est_eps, random_state=38, test_size=0.05)\nclf_earnings_hist_est_eps = RandomForestClassifier(random_state=1).fit(X_train, y_train)\nscore_earnings_hist_est_eps = clf_earnings_hist_est_eps.score(X_test, y_test)\nprint("earnings hist, est, and eps trend: ", score_earnings_hist_est_eps)\n\n#Earnings hist, est\nX_train, X_test, y_train, y_test = train_test_split( df_earnings_hist_est  , y_earnings_hist_est, random_state=25, test_size=0.05)\nclf_earnings_hist_est = vote\nclf_earnings_hist_est.fit(X_train, y_train)\nscore_earnings_hist_est = clf_earnings_hist_est.score(X_test, y_test)\nprint("earnings hist and est: ", score_earnings_hist_est)\n\n#Earnings history\nX_train, X_test, y_train, y_test = train_test_split( df_earnings_hist  , y_earnings_hist, random_state=72, test_size=0.05)\nclf_earnings_hist = GB\nclf_earnings_hist.fit(X_train, y_train)\nscore_earnings_hist = clf_earnings_hist.score(X_test, y_test)\nprint("earnings history: ", score_earnings_hist)\n\n#Earnings estimates\nX_train, X_test, y_train, y_test = train_test_split( df_earnings_est  , y_earnings_est, random_state=28, test_size=0.05)\nclf_earnings_est = ET\nclf_earnings_est.fit(X_train, y_train)\nscore_earnings_est = clf_earnings_est.score(X_test, y_test)\nprint("earnings estimates: ", score_earnings_est)\n\n#Analyst Price Targets, eps trend\nX_train, X_test, y_train, y_test = train_test_split( df_analystpricetarget_eps  , y_analystpricetarget_eps, random_state=46, test_size=0.05)\nclf_analystpricetarget_eps = BagGB\nclf_analystpricetarget_eps.fit(X_train, y_train)\nscore_analystpricetarget_eps = clf_analystpricetarget_eps.score(X_test, y_test)\nprint("analyst price targets and eps trend: ",score_analystpricetarget_eps)\n\n#Revenue Estimates\nX_train, X_test, y_train, y_test = train_test_split( df_rev_est  , y_rev_est, random_state=67, test_size=0.05)\nclf_rev_est = vote\nclf_rev_est.fit(X_train, y_train)\nscore_rev_est = clf_rev_est.score(X_test, y_test)\nprint("revenue estimates: ", score_rev_est)\n\n#Income Statements\nX_train, X_test, y_train, y_test = train_test_split( df_income_statement  , y_income_statement, random_state=5, test_size=0.05)\nclf_income_statement = vote\nclf_income_statement.fit(X_train, y_train)\nscore_income_statement = clf_income_statement.score(X_test, y_test)\nprint("income statement: ", score_income_statement)\n\n#Balance sheet\nX_train, X_test, y_train, y_test = train_test_split( df_balancesheet  , y_balancesheet, random_state=25, test_size=0.05)\nclf_balancesheet = vote\nclf_balancesheet.fit(X_train, y_train)\nscore_balancesheet = clf_balancesheet.score(X_test, y_test)\nprint("balancesheet: ",score_balancesheet)\n\n#Cashflow\nX_train, X_test, y_train, y_test = train_test_split( df_cashflow  , y_cashflow, random_state=21, test_size=0.05)\nclf_cashflow = stack\nclf_cashflow.fit(X_train, y_train)\nscore_cashflow = clf_cashflow.score(X_test, y_test)\nprint("cashflow: ", score_cashflow)\n\n#Meta data is repeated :(\nX_train, X_test, y_train, y_test = train_test_split( df_meta  , y_meta, random_state=55, test_size=0.05)\nclf_meta = ADARF\nclf_meta.fit(X_train, y_train)\nscore_meta = clf_meta.score(X_test, y_test)\nprint("meta: ",score_meta)\n'

In [ ]:
'''
#Cross validation
df = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Used for testing/FINAL-ESTIMATOR-TRAINING-DATA-2_deduped.csv") #abcdefghijklmnopqrstuvwxyz
y = df.pop("label")
print(df.shape, y.shape)

k = int(input("Enter number of cross validations: "))

RFscore = cross_val_score(RF,df,y,cv=k)
GBscore = cross_val_score(GB,df,y,cv=k)
BagGBscore = cross_val_score(BagGB,df,y,cv=k)
ADARFscore = cross_val_score(ADARF,df,y,cv=k)
ETscore = cross_val_score(ET,df,y,cv=k)
#BagNNscore = cross_val_score(BagNN,df,y,cv=k)
Votescore = cross_val_score(vote,df,y,cv=k)
Stackscore = cross_val_score(stack,df,y,cv=k)
'''
'''
print(f

{k} cross validations

RFscore: {RFscore.mean():.3f} (SD: {RFscore.std():.3f})
{RFscore}

GBscore: {GBscore.mean():.3f} (SD: {GBscore.std():.3f})
{GBscore}

BagGBscore: {BagGBscore.mean():.3f} (SD: {BagGBscore.std():.3f})
{BagGBscore}

ADARFscore: {ADARFscore.mean():.3f} (SD: {ADARFscore.std():.3f})
{ADARFscore}

ETscore: {ETscore.mean():.3f} (SD: {ETscore.std():.3f})
{ETscore}


Votescore: {Votescore.mean():.3f} (SD: {Votescore.std():.3f})
{Votescore}

Stackscore: {Stackscore.mean():.3f} (SD: {Stackscore.std():.3f})
{Stackscore}
      )
'''

'\nprint(f\n\n{k} cross validations\n\nRFscore: {RFscore.mean():.3f} (SD: {RFscore.std():.3f})\n{RFscore}\n\nGBscore: {GBscore.mean():.3f} (SD: {GBscore.std():.3f})\n{GBscore}\n\nBagGBscore: {BagGBscore.mean():.3f} (SD: {BagGBscore.std():.3f})\n{BagGBscore}\n\nADARFscore: {ADARFscore.mean():.3f} (SD: {ADARFscore.std():.3f})\n{ADARFscore}\n\nETscore: {ETscore.mean():.3f} (SD: {ETscore.std():.3f})\n{ETscore}\n\n\nVotescore: {Votescore.mean():.3f} (SD: {Votescore.std():.3f})\n{Votescore}\n\nStackscore: {Stackscore.mean():.3f} (SD: {Stackscore.std():.3f})\n{Stackscore}\n      )\n'

#Functions (fetching testing data, building the model, and est_date function)

In [ ]:
def unique_names(df, repeats):
  shape = df.shape
  columns_no = shape[1]/repeats
  columns_names = []
  for i in range(int(columns_no)):
    columns_names.append(df.columns[i])

  count = 1

  new_names = []

  for i in range(repeats):
    for i in range(int(columns_no)):
      if df.columns[i] in columns_names:
        new_column = f"{df.columns[i]}_{count}"
        new_names.append(new_column)

      else:
        new_column = df.columns[i]
        new_names.append(new_column)
    count = count+1
  return new_names


def testing_data(stock):

  stock = yf.Ticker(stock)

  try:
    #balancesheet
    balancesheet = stock.quarterly_balancesheet
    balancesheet = pd.concat([balancesheet.iloc[:,0], balancesheet.iloc[:,1], balancesheet.iloc[:,2],balancesheet.iloc[:,3],balancesheet.iloc[:,4]])
    balancesheet = balancesheet.to_frame().T
    balancesheet.columns = unique_names(balancesheet, 5)
    #balancesheet = balancesheet.dropna(axis=1)
  except:
    balancesheet = pd.DataFrame()
    print(stock, "balancesheet failed to load")

  try:
    #cashflow
    cashflow = stock.quarterly_cashflow
    cashflow = pd.concat([cashflow.iloc[:,0], cashflow.iloc[:,1], cashflow.iloc[:,2],cashflow.iloc[:,3],cashflow.iloc[:,4]])
    cashflow = cashflow.to_frame().T
    cashflow.columns = unique_names(cashflow, 5)
    #cashflow = cashflow.dropna(axis=1)
  except:
    cashflow = pd.DataFrame()
    print(str(stock),"cashflow failed to load")

  try:
    #Analyst price targets & eps trend
    analyst_price_targets = pd.DataFrame.from_dict(stock.analyst_price_targets, orient='index').transpose()
    analyst_price_targets.rename(columns = {"current":"current price"}, inplace = True)
    analyst_price_targets.rename(columns = {"high":"high estimate"}, inplace = True)
    analyst_price_targets.rename(columns = {"low":"low estimate"}, inplace = True)
    analyst_price_targets.rename(columns = {"mean":"mean estimate"}, inplace = True)
    analyst_price_targets.rename(columns = {"median":"median estimate"}, inplace = True)
    #analyst_price_targets = analyst_price_targets.dropna(axis=1)
  except:
    analyst_price_targets = pd.DataFrame()
    print(stock,"analyst price targets failed to load")

  try:
    eps_trend = stock.eps_trend
    eps_trend = pd.concat([eps_trend.iloc[0,:],eps_trend.iloc[1,:],eps_trend.iloc[2,:],eps_trend.iloc[3,:]]).to_frame().T
    eps_trend.columns = unique_names(eps_trend, 4)
    #eps_trend = eps_trend.dropna(axis=1)
  except:
    eps_trend = pd.DataFrame()
    print(stock,"eps trend failed to load")


  analyst_price_targets_eps_trend = pd.concat([analyst_price_targets, eps_trend], axis=1)

  try:
    #income statement
    incomestmt = stock.income_stmt
    incomestmt = pd.concat([incomestmt.iloc[:,0], incomestmt.iloc[:,1], incomestmt.iloc[:,2],incomestmt.iloc[:,3],incomestmt.iloc[:,4]])
    incomestmt = incomestmt.to_frame().T
    incomestmt.columns = unique_names(incomestmt,5)
    #incomestmt = incomestmt.dropna(axis=1)
  except:
    incomestmt = pd.DataFrame()
    print(stock,"incomestmt failed to load")

  try:
    #earning estimate
    earning_est = stock.earnings_estimate
    earning_est = pd.concat([earning_est.iloc[0,:],earning_est.iloc[1,:],earning_est.iloc[2,:],earning_est.iloc[3,:]]).to_frame().T
    earning_est.columns = unique_names(earning_est, 4)
    #earning_est = earning_est.dropna(axis=1)
  except:
    earning_est = pd.DataFrame()
    print(stock,"earnings estimates failed to load")

  try:
    #earnings history
    earning_hist = stock.earnings_history
    earning_hist = pd.concat([earning_hist.iloc[0,:],earning_hist.iloc[1,:],earning_hist.iloc[2,:],earning_hist.iloc[3,:]]).to_frame().T
    earning_hist.columns = unique_names(earning_hist, 4)
    #earnins_hist = earning_hist.dropna(axis=1)
  except:
    earning_hist = pd.DataFrame()
    print(stock,"earnings history failed to load")

  #earnings hist + est
  earning_hist = earning_hist.reset_index(drop=True)
  earning_est = earning_est.reset_index(drop=True)
  eps_trend = eps_trend.reset_index(drop=True)
  earnings_hist_est = pd.concat([earning_hist, earning_est], axis=1)
  #earnings_hist_est = earnings_hist_est.dropna()

  #earnings hist + estimates + eps
  earnings_hist_est_eps = pd.concat([earning_hist, earning_est, eps_trend], axis=1)
  #earnings_hist_est_eps = earnings_hist_est_eps.dropna()

  try:
    #Revenue estimates
    rev_est = stock.revenue_estimate
    rev_est = pd.concat([rev_est.iloc[0,:],rev_est.iloc[1,:],rev_est.iloc[2,:],rev_est.iloc[3,:]]).to_frame().T
    rev_est.columns = unique_names(rev_est, 4)
    #rev_est = rev_est.dropna(axis=1)
  except:
    rev_est = pd.DataFrame()
    print(stock,"revenue estimates failed to load")

  try:
    #Meta data
    rev_and_earning_est = pd.concat([rev_est,earning_est], axis = 1)
    rev_and_earning_est.columns = unique_names(rev_and_earning_est,2)
    meta = pd.concat([balancesheet, cashflow, analyst_price_targets, eps_trend, rev_and_earning_est, earning_hist  ],axis=1)
  except:
    meta = pd.DataFrame
    print(stock,"meta failed to load")

  return balancesheet, cashflow, analyst_price_targets_eps_trend, incomestmt, earning_est, earning_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta


def transform(input, template):

  df = template.iloc[0].to_frame().T

  input = pd.concat([input, df])

  input = input.dropna(axis=1)

  if input.shape[0] !=1:
    input = input.iloc[0].to_frame().T
  elif input.shape[0] == 1:
    input = pd.DataFrame()

  return input


def transformed_testing_data(stock):

  failed = []
  succeeded = []


  balancesheet, cashflow, analyst_target_eps, incomestmt, earnings_est, earnings_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta = testing_data(stock)

  balancesheet = transform(balancesheet, df_balancesheet)
  cashflow = transform(cashflow, df_cashflow)
  analyst_target_eps = transform(analyst_target_eps, df_analystpricetarget_eps)
  incomestmt = transform(incomestmt, df_income_statement)
  earnings_est = transform(earnings_est, df_earnings_est)
  earnings_hist = transform(earnings_hist, df_earnings_hist)
  earnings_hist_est = transform(earnings_hist_est, df_earnings_hist_est)
  earnings_hist_est_eps = transform(earnings_hist_est_eps, df_earnings_hist_est_eps)
  rev_est = transform(rev_est, df_rev_est)
  meta = transform(meta, df_meta)

  if transform(balancesheet, df_balancesheet).shape != (1, 34):
      failed.append(("balancesheet"))
  else:
      succeeded.append(("balancesheet"))

  if cashflow.shape != (1, 5):
      failed.append(( "cashflow"))
  else:
      succeeded.append(( "cashflow"))

  if analyst_target_eps.shape != (1, 21):
      failed.append(( "analyst_target_eps"))
  else:
      succeeded.append(( "analyst_target_eps"))

  if incomestmt.shape != (1, 30):
      failed.append(( "incomestmt"))
  else:
      succeeded.append(("incomestmt"))

  if earnings_est.shape != (1, 16):
      failed.append(( "earnings_est"))
  else:
      succeeded.append(( "earnings_est"))

  if earnings_hist.shape != (1, 16):
      failed.append(( "earnings_hist"))
  else:
      succeeded.append(( "earnings_hist"))

  if earnings_hist_est.shape != (1, 40):
      failed.append(( "earnings_hist_est"))
  else:
      succeeded.append(( "earnings_hist_est"))

  if earnings_hist_est_eps.shape != (1, 60):
      failed.append(( "earnings_hist_est_eps"))
  else:
      succeeded.append(("earnings_hist_est_eps"))

  if rev_est.shape != (1, 16):
      failed.append(("rev_est"))
  else:
      succeeded.append(("rev_est"))

  if meta.shape != (1, 95):
      failed.append(( "meta"))
  else:
      succeeded.append(( "meta"))

  return succeeded, failed, balancesheet, cashflow, analyst_target_eps, incomestmt, earnings_est, earnings_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta


def fundemental_model(stock):


  weighted_prediction = []
  predictions = []

  successful, failed, balancesheet, cashflow, analyst_target_eps, incomestmt, earnings_est, earnings_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta = transformed_testing_data(stock)
  print(f'''
  {stock}
  Successful: {len(successful)}
        {successful}
  Failed: {len(failed)}
        {failed}
  ''')
  if len(failed)==10:
    print("🔺🔺🔺 error occured 🔺🔺🔺")
    return f"error with {stock}",f"error with {stock}",f"error with {stock}",f"error with {stock}"

  else:
    #if "balancesheet" in successful:
    try:
        pred = clf_balancesheet.predict_proba(balancesheet)
        #weighted_prediction.append(pred[0,1]*(3025/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3025/32906))
        predictions.append(-100)
        print(f"Error occurred with balancesheet: {e}")

    #if "cashflow" in successful:
    try:
        pred = clf_cashflow.predict_proba(cashflow)
        #weighted_prediction.append(pred[0,1]*(3025/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3025/32906))
        predictions.append(-100)
        print(f"Error occurred with cashflow: {e}")

    #if "analyst_target_eps" in successful:
    try:
        pred = clf_analystpricetarget_eps.predict_proba(analyst_target_eps)
        #weighted_prediction.append(pred[0,1]*(3025/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3025/32906))
        predictions.append(-100)
        print(f"Error occurred with analyst_target_eps: {e}")

    #if "incomestmt" in successful:
    try:
        pred = clf_income_statement.predict_proba(incomestmt)
        #weighted_prediction.append(pred[0,1]*(3481/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3481/32906))
        predictions.append(-100)
        print(f"Error occurred with incomestmt: {e}")

    #if "earnings_est" in successful:
    try:
        pred = clf_earnings_est.predict_proba(earnings_est)
        #weighted_prediction.append(pred[0,1]*(2916/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(2916/32906))
        predictions.append(-100)
        print(f"Error occurred with earnings_est: {e}")

    #if "earnings_hist" in successful:
    try:
        pred = clf_earnings_hist.predict_proba(earnings_hist)
        #weighted_prediction.append(pred[0,1]*(3600/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3600/32906))
        predictions.append(-100)
        print(f"Error occurred with earnings_hist: {e}")

    #if "earnings_hist_est" in successful:
    try:
        pred = clf_earnings_hist_est.predict_proba(earnings_hist_est)
        #weighted_prediction.append(pred[0,1]*(4225/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(4225/32906))
        predictions.append(-100)
        print(f"Error occurred with earnings_hist_est: {e}")

    #if "earnings_hist_est_eps" in successful:
    try:
        pred = clf_earnings_hist_est_eps.predict_proba(earnings_hist_est_eps)
        #weighted_prediction.append(pred[0,1]*(3844/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3844/32906))
        predictions.append(-100)
        print(f"Error occurred with earnings_hist_est_eps: {e}")

    #if "rev_est" in successful:
    try:
        pred = clf_rev_est.predict_proba(rev_est)
        #weighted_prediction.append(pred[0,1]*(2401/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(2401/32906))
        predictions.append(-100)
        print(f"Error occurred with rev_est: {e}")

    #if "meta" in successful:
    try:
        pred = clf_meta.predict_proba(meta)
        #weighted_prediction.append(pred[0,1]*(3364/32906))
        predictions.append(pred[0,1])
    except Exception as e:
        #weighted_prediction.append(0.5*(3364/32906))
        predictions.append(-100)
        print(f"Error occurred with meta: {e}")


    predictions = pd.DataFrame({"":predictions}).transpose()
    final_estimator_pred = clf_final_estimator.predict_proba(predictions)
    if final_estimator_pred[0,1] >0.91:
      prediction = 1
      print("🔹", prediction,"🔹", "~83% accuracy 🔹")

    elif final_estimator_pred[0,1]<0.1:
      prediction = -1
      print("🔹", prediction,"🔹", "~86% accuracy 🔹")

    else:
       if final_estimator_pred[0,1] >0.8:
        prediction = 1
        print("🔹", prediction,"🔹", "~69% accuracy 🔹")

       elif final_estimator_pred[0,1]<0.15:
        prediction = -1
        print("🔹", prediction,"🔹", "~69% accuracy 🔹")
       else:
        prediction = "unknown"
        print("🔸 Uncertain 🔸")


    return prediction, final_estimator_pred[0,1]

In [ ]:
def change_days(date_str, days):
    import datetime as dt
    date = dt.datetime.strptime(date_str, "%Y-%m-%d")

    new_date = date + timedelta(days=days)

    return new_date.strftime("%Y-%m-%d")

def change_months(date_str, monthss):
  import datetime as dt
  date_obj = datetime.strptime(date_str, "%Y-%m-%d")

  new_date = date_obj + relativedelta(months=monthss)

  return new_date.strftime("%Y-%m-%d")

def est_date(stock):
  ticker = yf.Ticker(stock)
  ticker = ticker.quarterly_balance_sheet
  date = ((str(ticker.columns[0])).split())[0]
  date = change_months(date, 3)
  return date

#Tests

In [ ]:
#UNSEEN: FOR TESTING FINAL ESTIMATOR
stocks=['LOVE', 'LOWLF', 'LOW', 'LPLA', 'LQWDF', 'LXU', 'LYTS', 'LTC', 'LUCMF', 'LUCRF', 'LGCL', 'LUCN', 'LUCD', 'LCID', 'LKNCY', 'LUCK', 'LDSN', 'LUDG', 'LU', 'LKFLF', 'LULU', 'LVLU', 'LUMB', 'LUMN', 'LFT', 'LITE', 'LMGDF', 'LRGR', 'LAZR', 'LMGIF', 'LDXHF', 'LUGDF', 'LUNMF', 'LPKGF', 'LUVU', 'LUXE', 'LXFR', 'LUXHP', 'LUXFF', 'LVMUY', 'LVMHF', 'LXP', 'YAHOF', 'YAHOY', 'LCXEF', 'LYEL', 'LYFT', 'LYSCF', 'LYSDY', 'LYB', 'SLMNP', 'LYBC', 'LYRA', 'LYTHF', 'MFBP', 'MGPUF', 'MTB', 'MHO', 'MTWO', 'MTHRF', 'MTHRY', 'MLGCF', 'MBAVU', 'MBAV', 'MAAS', 'MTAL', 'MAC', 'MNR', 'MACT', 'MKZR', 'MTSI', 'MQBKY', 'DBMBF', 'MRPT', 'MGNX', 'M', 'MADGF', 'MCBK', 'MSET', 'MSGE', 'MSGS', 'MDGL', 'MMCP', 'MAG', 'MGLUY', 'MALJF', 'MAGE', 'MEGL', 'MGA', 'MGMNF', 'BRIOF', 'MX', 'MAGN', 'MNSEF', 'MGY', 'MYTAY', 'MAHMF', 'MAIA', 'MAIN', 'MSWV', 'MNSBP', 'MEQYF', 'MSCH', 'MYNZ', 'MASN', 'MSS', 'MJGCF', 'MJDLF', 'MMYT', 'MKTAY', 'MAKOF', 'MLGF', 'MLYBY', 'MBUU', 'MAMA', 'TUSK', 'MNGPF', 'MAWHF', 'MANU', 'MNDJF', 'MAORF', 'MANDF','MNXXF', 'MGRX', 'MANH', 'MTW', 'MANVF', 'MNKD', 'MAN', 'MFC', 'MPFRF', 'MPFRY', 'MGMLF', 'MLFNF', 'MGWFF', 'CART', 'MAPGF', 'MAQC', 'MARA', 'MBBC', 'MPC', 'MRVI', 'MRPMF', 'MMI', 'MCS', 'MRX', 'MRRTY', 'MAJI', 'MARIF', 'MRMD', 'MRIN', 'MBOF', 'MARPS', 'HZO', 'MTEK', 'MAXQF', 'MRTMD', 'MKL', 'MRKR', 'MKTX', 'MAAL', 'MKTW', 'RVBR', 'MAKSY', 'MRLWF', 'MQ', 'MNAT', 'TMGID', 'MAR', 'VAC', 'MMC', 'MRTN', 'MRT', 'MLM', 'MRETF', 'MARUF', 'MARUY', 'MAURY', 'MBCOF', 'MARVF', 'MRVL', 'MVNC', 'MGLD', 'MAS', 'MASI', 'GNYPF', 'MGPHF', 'MMMW', 'MSSEL', 'MAMO', 'MTZ', 'MHH', 'MBC', 'MA', 'MCFT', 'MMND', 'MTDR', 'MTCH', 'MTLS', 'MTRN', 'MTRN', 'MTRX', 'MATX', 'MAT', 'MATW', 'MTTRF', 'MCHT', 'MKGP', 'MIGI', 'MAXXF', 'MXCT', 'MMS', 'MXL', 'MRTI', 'MAYX', 'MFGCF', 'MAYNF', 'MEC', 'MZDAF', 'MZDAY', 'MBI', 'MBKL', 'MBX', 'MSMY', 'MAMTF', 'MCBRF', 'MKC', 'MCCRF', 'MCDIF', 'MCD', 'MDNDF', 'MUX', 'MCFNF', 'MGRC', 'GLFN', 'MCK', 'MCRAA', 'MCRAB']

len(stocks)

238

In [ ]:
print(len(error), len(stocks) - len(error))
for i in range(len(error)):
  stocks.remove(error[i])

print(len(stocks))
print(stocks)

0 238
238
['LOVE', 'LOWLF', 'LOW', 'LPLA', 'LQWDF', 'LXU', 'LYTS', 'LTC', 'LUCMF', 'LUCRF', 'LGCL', 'LUCN', 'LUCD', 'LCID', 'LKNCY', 'LUCK', 'LDSN', 'LUDG', 'LU', 'LKFLF', 'LULU', 'LVLU', 'LUMB', 'LUMN', 'LFT', 'LITE', 'LMGDF', 'LRGR', 'LAZR', 'LMGIF', 'LDXHF', 'LUGDF', 'LUNMF', 'LPKGF', 'LUVU', 'LUXE', 'LXFR', 'LUXHP', 'LUXFF', 'LVMUY', 'LVMHF', 'LXP', 'YAHOF', 'YAHOY', 'LCXEF', 'LYEL', 'LYFT', 'LYSCF', 'LYSDY', 'LYB', 'SLMNP', 'LYBC', 'LYRA', 'LYTHF', 'MFBP', 'MGPUF', 'MTB', 'MHO', 'MTWO', 'MTHRF', 'MTHRY', 'MLGCF', 'MBAVU', 'MBAV', 'MAAS', 'MTAL', 'MAC', 'MNR', 'MACT', 'MKZR', 'MTSI', 'MQBKY', 'DBMBF', 'MRPT', 'MGNX', 'M', 'MADGF', 'MCBK', 'MSET', 'MSGE', 'MSGS', 'MDGL', 'MMCP', 'MAG', 'MGLUY', 'MALJF', 'MAGE', 'MEGL', 'MGA', 'MGMNF', 'BRIOF', 'MX', 'MAGN', 'MNSEF', 'MGY', 'MYTAY', 'MAHMF', 'MAIA', 'MAIN', 'MSWV', 'MNSBP', 'MEQYF', 'MSCH', 'MYNZ', 'MASN', 'MSS', 'MJGCF', 'MJDLF', 'MMYT', 'MKTAY', 'MAKOF', 'MLGF', 'MLYBY', 'MBUU', 'MAMA', 'TUSK', 'MNGPF', 'MAWHF', 'MANU', 'MNDJF', 'MAORF', 'MANDF', 'MNXXF', 'MGRX', 'MANH', 'MTW', 'MANVF', 'MNKD', 'MAN', 'MFC', 'MPFRF', 'MPFRY', 'MGMLF', 'MLFNF', 'MGWFF', 'CART', 'MAPGF', 'MAQC', 'MARA', 'MBBC', 'MPC', 'MRVI', 'MRPMF', 'MMI', 'MCS', 'MRX', 'MRRTY', 'MAJI', 'MARIF', 'MRMD', 'MRIN', 'MBOF', 'MARPS', 'HZO', 'MTEK', 'MAXQF', 'MRTMD', 'MKL', 'MRKR', 'MKTX', 'MAAL', 'MKTW', 'RVBR', 'MAKSY', 'MRLWF', 'MQ', 'MNAT', 'TMGID', 'MAR', 'VAC', 'MMC', 'MRTN', 'MRT', 'MLM', 'MRETF', 'MARUF', 'MARUY', 'MAURY', 'MBCOF', 'MARVF', 'MRVL', 'MVNC', 'MGLD', 'MAS', 'MASI', 'GNYPF', 'MGPHF', 'MMMW', 'MSSEL', 'MAMO', 'MTZ', 'MHH', 'MBC', 'MA', 'MCFT', 'MMND', 'MTDR', 'MTCH', 'MTLS', 'MTRN', 'MTRN', 'MTRX', 'MATX', 'MAT', 'MATW', 'MTTRF', 'MCHT', 'MKGP', 'MIGI', 'MAXXF', 'MXCT', 'MMS', 'MXL', 'MRTI', 'MAYX', 'MFGCF', 'MAYNF', 'MEC', 'MZDAF', 'MZDAY', 'MBI', 'MBKL', 'MBX', 'MSMY', 'MAMTF', 'MCBRF', 'MKC', 'MCCRF', 'MCDIF', 'MCD', 'MDNDF', 'MUX', 'MCFNF', 'MGRC', 'GLFN', 'MCK', 'MCRAA', 'MCRAB']

In [ ]:
predictions = []
error = []

for i in range(len(stocks)):
  try:
    weighted,final_est,preds = fundemental_model(stocks[i])
    print(i, stocks[i])

    if final_est > 0.9:
      prediction = 1
    elif final_est <0.1:
      prediction = -1
    else:
      prediction = 0

    predictions.append(prediction)
  except:
    error.append(stocks[i])

predictions, error

 LOVE
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4468288549494008 🔹 0.4061109482720391 🔹
0 LOVE
yfinance.Ticker object <LOWLF> balancesheet failed to load
yfinance.Ticker object <LOWLF> cashflow failed to load
yfinance.Ticker object <LOWLF> incomestmt failed to load
yfinance.Ticker object <LOWLF> earnings history failed to load

 LOWLF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
1 LOWLF

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

 LOW
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5597307538127149 🔹 0.9332696601713408 🔹
2 LOW

 LPLA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7082126007222701 🔹 0.9001412527201273 🔹
3 LPLA
yfinance.Ticker object <LQWDF> earnings history failed to load

 LQWDF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.46516417668357724 🔹 0.6381591789377269 🔹
4 LQWDF

 LXU
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3372026939164394 🔹 0.3209963098378987 🔹
5 LXU
yfinance.Ticker object <LYTS> incomestmt failed to load

 LYTS
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.49795142522851077 🔹 0.16009121168393284 🔹
6 LYTS

 LTC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4971813674804405 🔹 0.4224334176242472 🔹
7 LTC
yfinance.Ticker object <LUCMF> earnings history failed to load

 LUCMF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.42448219050637 🔹 0.5825331993969588 🔹
8 LUCMF
yfinance.Ticker object <LUCRF> earnings history failed to load

 LUCRF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4941447363961422 🔹 0.7089187542278808 🔹
9 LUCRF
yfinance.Ticker object <LGCL> balancesheet failed to load
yfinance.Ticker object <LGCL> cashflow failed to load
yfinance.Ticker object <LGCL> earnings history failed to load

 LGCL
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4774005967608582 🔹 0.757027039814911 🔹
10 LGCL
yfinance.Ticker object <LUCN> earnings history failed to load

 LUCN
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4638772770612909 🔹 0.6447308645207822 🔹
11 LUCN
yfinance.Ticker object <LUCD> incomestmt failed to load

 LUCD
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.29717461207203216 🔹 0.1569352808018133 🔹
12 LUCD

 LCID
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5166561067725921 🔹 0.6069486410506952 🔹
13 LCID
yfinance.Ticker object <LKNCY> earnings history failed to load

 LKNCY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.5744032584037251 🔹 0.8887499122051088 🔹
14 LKNCY
yfinance.Ticker object <LUCK> incomestmt failed to load

 LUCK
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2870616101248988 🔹 0.2346607557052426 🔹
15 LUCK
yfinance.Ticker object <LDSN> earnings history failed to load

 LDSN
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4719420561981261 🔹 0.9200322267013091 🔹
16 LDSN
yfinance.Ticker object <LUDG> incomestmt failed to load
yfinance.Ticker object <LUDG> earnings history failed to load

 LUDG
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4156885553851032 🔹 0.31932737244392206 🔹
17 LUDG
yfinance.Ticker object <LU> balancesheet failed to load
yfinance.Ticker object <LU> cashflow failed to load
yfinance.Ticker object <LU> incomestmt failed to load
yfinance.Ticker object <LU> earnings history failed to load

 LU
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4830145436343581 🔹 0.5791860054117007 🔹
18 LU
yfinance.Ticker object <LKFLF> balancesheet failed to load
yfinance.Ticker object <LKFLF> cashflow failed to load
yfinance.Ticker object <LKFLF> incomestmt failed to load
yfinance.Ticker object <LKFLF> earnings history failed to load

 LKFLF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46276287182366177 🔹 0.5028652946344497 🔹
19 LKFLF
yfinance.Ticker object <LULU> incomestmt failed to load

 LULU
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5882677430836314 🔹 0.9401386853777152 🔹
20 LULU

 LVLU
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3494404851647328 🔹 0.1763527196587094 🔹
21 LVLU
yfinance.Ticker object <LUMB> balancesheet failed to load
yfinance.Ticker object <LUMB> cashflow failed to load
yfinance.Ticker object <LUMB> incomestmt failed to load
yfinance.Ticker object <LUMB> earnings history failed to load

 LUMB
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47682771864758267 🔹 0.24224062279566064 🔹
22 LUMB
yfinance.Ticker object <LUMN> incomestmt failed to load

 LUMN
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3771619125108558 🔹 0.3333558539357718 🔹
23 LUMN

 LFT
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2933024979477616 🔹 0.6300631765848578 🔹
24 LFT
yfinance.Ticker object <LITE> incomestmt failed to load

 LITE
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5828775802811942 🔹 0.6203445067785902 🔹
25 LITE
yfinance.Ticker object <LMGDF> earnings history failed to load

 LMGDF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.40366787886737726 🔹 0.4835743826633062 🔹
26 LMGDF
yfinance.Ticker object <LRGR> balancesheet failed to load
yfinance.Ticker object <LRGR> cashflow failed to load
yfinance.Ticker object <LRGR> incomestmt failed to load
yfinance.Ticker object <LRGR> earnings history failed to load

 LRGR
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
27 LRGR

 LAZR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3677721268766254 🔹 0.20642912834307225 🔹
28 LAZR
yfinance.Ticker object <LMGIF> incomestmt failed to load
yfinance.Ticker object <LMGIF> earnings history failed to load

 LMGIF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4522222146339853 🔹 0.8398392187999789 🔹
29 LMGIF
yfinance.Ticker object <LDXHF> balancesheet failed to load
yfinance.Ticker object <LDXHF> cashflow failed to load
yfinance.Ticker object <LDXHF> incomestmt failed to load
yfinance.Ticker object <LDXHF> earnings history failed to load

 LDXHF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45720205613699333 🔹 0.39891602563551265 🔹
30 LDXHF
yfinance.Ticker object <LUGDF> earnings history failed to load

 LUGDF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4378576304459574 🔹 0.9022423007282052 🔹
31 LUGDF

 LUNMF
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.33456987611499334 🔹 0.33640134747619743 🔹
32 LUNMF
yfinance.Ticker object <LPKGF> earnings history failed to load

 LPKGF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4113074742301732 🔹 0.146332890964285 🔹
33 LPKGF
yfinance.Ticker object <LUVU> incomestmt failed to load
yfinance.Ticker object <LUVU> earnings history failed to load

 LUVU
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.500593556499715 🔹 0.7959105838930635 🔹
34 LUVU
yfinance.Ticker object <LUXE> incomestmt failed to load

 LUXE
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.30711039508887605 🔹 0.19773839859037057 🔹
35 LUXE

 LXFR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46728719827736054 🔹 0.4961963519532042 🔹
36 LXFR
yfinance.Ticker object <LUXHP> balancesheet failed to load
yfinance.Ticker object <LUXHP> cashflow failed to load
yfinance.Ticker object <LUXHP> incomestmt failed to load
yfinance.Ticker object <LUXHP> earnings history failed to load

 LUXHP
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
37 LUXHP
yfinance.Ticker object <LUXFF> earnings history failed to load

 LUXFF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4279373209516645 🔹 0.602114366744858 🔹
38 LUXFF
yfinance.Ticker object <LVMUY> balancesheet failed to load
yfinance.Ticker object <LVMUY> cashflow failed to load
yfinance.Ticker object <LVMUY> earnings history failed to load

 LVMUY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.5821376351919271 🔹 0.7597817571462988 🔹
39 LVMUY
yfinance.Ticker object <LVMHF> balancesheet failed to load
yfinance.Ticker object <LVMHF> cashflow failed to load
yfinance.Ticker object <LVMHF> earnings history failed to load

 LVMHF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5085109978207187 🔹 0.42705983254669366 🔹
40 LVMHF

 LXP
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.41509185133543947 🔹 0.5906683577306318 🔹
41 LXP
yfinance.Ticker object <YAHOF> balancesheet failed to load
yfinance.Ticker object <YAHOF> cashflow failed to load
yfinance.Ticker object <YAHOF> earnings history failed to load

 YAHOF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.44365252543718287 🔹 0.5276816426104789 🔹
42 YAHOF
yfinance.Ticker object <YAHOY> balancesheet failed to load
yfinance.Ticker object <YAHOY> cashflow failed to load
yfinance.Ticker object <YAHOY> earnings history failed to load

 YAHOY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.438546145392075 🔹 0.18478484913969562 🔹
43 YAHOY
yfinance.Ticker object <LCXEF> balancesheet failed to load
yfinance.Ticker object <LCXEF> cashflow failed to load
yfinance.Ticker object <LCXEF> incomestmt failed to load
yfinance.Ticker object <LCXEF> earnings history failed to load

 LCXEF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4535640902021692 🔹 0.680491048423369 🔹
44 LCXEF

 LYEL
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- yearAgoEps_1
- yearAgoEps_2

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- yearAgoEps_1
- yearAgoEps_2

🔹 0.5240957834324215 🔹 0.2669326249520167 🔹
45 LYEL

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

 LYFT
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6292758509718143 🔹 0.8311816710073405 🔹
46 LYFT
yfinance.Ticker object <LYSCF> balancesheet failed to load
yfinance.Ticker object <LYSCF> cashflow failed to load
yfinance.Ticker object <LYSCF> incomestmt failed to load
yfinance.Ticker object <LYSCF> earnings history failed to load

 LYSCF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.469751732344323 🔹 0.8292849027044227 🔹
47 LYSCF
yfinance.Ticker object <LYSDY> balancesheet failed to load
yfinance.Ticker object <LYSDY> cashflow failed to load
yfinance.Ticker object <LYSDY> incomestmt failed to load
yfinance.Ticker object <LYSDY> earnings history failed to load

 LYSDY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4709443342215652 🔹 0.818063137188245 🔹
48 LYSDY

 LYB
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.35569813081481927 🔹 0.82633639529526 🔹
49 LYB
yfinance.Ticker object <SLMNP> balancesheet failed to load
yfinance.Ticker object <SLMNP> cashflow failed to load
yfinance.Ticker object <SLMNP> incomestmt failed to load
yfinance.Ticker object <SLMNP> earnings history failed to load

 SLMNP
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5196340885151218 🔹 0.5591639825022132 🔹
50 SLMNP
yfinance.Ticker object <LYBC> cashflow failed to load
yfinance.Ticker object <LYBC> incomestmt failed to load
yfinance.Ticker object <LYBC> earnings history failed to load

 LYBC
 Successful: 4
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 6
       ['cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with cashflow: at least one array or dtype is required
Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

🔹 0.47065175734313713 🔹 0.27485617191148365 🔹
51 LYBC

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

 LYRA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5921203948031395 🔹 0.28931475425488584 🔹
52 LYRA
yfinance.Ticker object <LYTHF> balancesheet failed to load
yfinance.Ticker object <LYTHF> cashflow failed to load
yfinance.Ticker object <LYTHF> incomestmt failed to load
yfinance.Ticker object <LYTHF> earnings history failed to load

 LYTHF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
53 LYTHF
yfinance.Ticker object <MFBP> cashflow failed to load
yfinance.Ticker object <MFBP> earnings history failed to load

 MFBP
 Successful: 5
       ['balancesheet', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 5
       ['cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

🔹 0.46426747743489194 🔹 0.2498095008657228 🔹
54 MFBP
yfinance.Ticker object <MGPUF> balancesheet failed to load
yfinance.Ticker object <MGPUF> cashflow failed to load
yfinance.Ticker object <MGPUF> earnings history failed to load

 MGPUF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4523689182251839 🔹 0.6125521413051257 🔹
55 MGPUF

 MTB
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7113187055190082 🔹 0.9651737364068453 🔹
56 MTB

 MHO
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3757587466692738 🔹 0.7017508681403662 🔹
57 MHO
yfinance.Ticker object <MTWO> earnings history failed to load

 MTWO
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3897223006124375 🔹 0.27478636093851816 🔹
58 MTWO
yfinance.Ticker object <MTHRF> balancesheet failed to load
yfinance.Ticker object <MTHRF> cashflow failed to load
yfinance.Ticker object <MTHRF> earnings history failed to load

 MTHRF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4143047937097434 🔹 0.3551483326786721 🔹
59 MTHRF
yfinance.Ticker object <MTHRY> balancesheet failed to load
yfinance.Ticker object <MTHRY> cashflow failed to load
yfinance.Ticker object <MTHRY> earnings history failed to load

 MTHRY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.40908757990829014 🔹 0.19363131619382318 🔹
60 MTHRY
yfinance.Ticker object <MLGCF> earnings history failed to load

 MLGCF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.3940292155598495 🔹 0.18568039509339046 🔹
61 MLGCF
yfinance.Ticker object <MBAVU> balancesheet failed to load
yfinance.Ticker object <MBAVU> cashflow failed to load
yfinance.Ticker object <MBAVU> incomestmt failed to load
yfinance.Ticker object <MBAVU> earnings history failed to load

 MBAVU
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47669317940285816 🔹 0.770139161784602 🔹
62 MBAVU
yfinance.Ticker object <MBAV> balancesheet failed to load
yfinance.Ticker object <MBAV> cashflow failed to load
yfinance.Ticker object <MBAV> incomestmt failed to load
yfinance.Ticker object <MBAV> earnings history failed to load

 MBAV
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4763058009905413 🔹 0.767388240195794 🔹
63 MBAV

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MAAS> balancesheet failed to load
yfinance.Ticker object <MAAS> cashflow failed to load
yfinance.Ticker object <MAAS> incomestmt failed to load
yfinance.Ticker object <MAAS> earnings history failed to load

 MAAS
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4772868288843968 🔹 0.2967956572876522 🔹
64 MAAS

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MTAL> balancesheet failed to load
yfinance.Ticker object <MTAL> cashflow failed to load
yfinance.Ticker object <MTAL> incomestmt failed to load
yfinance.Ticker object <MTAL> earnings history failed to load

 MTAL
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5716311557198995 🔹 0.30892298439375543 🔹
65 MTAL

 MAC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3896164090597878 🔹 0.6384532605957396 🔹
66 MAC
yfinance.Ticker object <MNR> incomestmt failed to load

 MNR
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.42622898508115437 🔹 0.4382126539799338 🔹
67 MNR
yfinance.Ticker object <MACT> balancesheet failed to load
yfinance.Ticker object <MACT> cashflow failed to load
yfinance.Ticker object <MACT> incomestmt failed to load
yfinance.Ticker object <MACT> earnings history failed to load

 MACT
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47366542813891377 🔹 0.15092328551582643 🔹
68 MACT
yfinance.Ticker object <MKZR> incomestmt failed to load
yfinance.Ticker object <MKZR> earnings history failed to load

 MKZR
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.44442189004795607 🔹 0.6763380110162576 🔹
69 MKZR

 MTSI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5045702134331838 🔹 0.7774147735618433 🔹
70 MTSI
yfinance.Ticker object <MQBKY> balancesheet failed to load
yfinance.Ticker object <MQBKY> cashflow failed to load
yfinance.Ticker object <MQBKY> incomestmt failed to load
yfinance.Ticker object <MQBKY> earnings history failed to load

 MQBKY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4790499571471624 🔹 0.850945634449433 🔹
71 MQBKY
yfinance.Ticker object <DBMBF> incomestmt failed to load
yfinance.Ticker object <DBMBF> earnings history failed to load

 DBMBF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5135470103775416 🔹 0.7441201969255253 🔹
72 DBMBF
yfinance.Ticker object <MRPT> balancesheet failed to load
yfinance.Ticker object <MRPT> cashflow failed to load
yfinance.Ticker object <MRPT> incomestmt failed to load
yfinance.Ticker object <MRPT> earnings history failed to load

 MRPT
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
73 MRPT

 MGNX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3923453161994362 🔹 0.6852582198985564 🔹
74 MGNX

 M
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5003316124111737 🔹 0.1995296051409008 🔹
75 M
yfinance.Ticker object <MADGF> balancesheet failed to load
yfinance.Ticker object <MADGF> cashflow failed to load
yfinance.Ticker object <MADGF> incomestmt failed to load
yfinance.Ticker object <MADGF> earnings history failed to load

 MADGF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47101794161157523 🔹 0.7548393917213847 🔹
76 MADGF
yfinance.Ticker object <MCBK> balancesheet failed to load
yfinance.Ticker object <MCBK> cashflow failed to load
yfinance.Ticker object <MCBK> incomestmt failed to load
yfinance.Ticker object <MCBK> earnings history failed to load

 MCBK
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4761495918010512 🔹 0.2894897012068527 🔹
77 MCBK
yfinance.Ticker object <MSET> balancesheet failed to load
yfinance.Ticker object <MSET> cashflow failed to load
yfinance.Ticker object <MSET> incomestmt failed to load
yfinance.Ticker object <MSET> earnings history failed to load

 MSET
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
78 MSET
yfinance.Ticker object <MSGE> incomestmt failed to load

 MSGE
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6281047173455017 🔹 0.7669476658819556 🔹
79 MSGE
yfinance.Ticker object <MSGS> incomestmt failed to load

 MSGS
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.48540341803740783 🔹 0.6946215269029817 🔹
80 MSGS

 MDGL
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5427227836869772 🔹 0.23027273799785092 🔹
81 MDGL
yfinance.Ticker object <MMCP> incomestmt failed to load
yfinance.Ticker object <MMCP> earnings history failed to load

 MMCP
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46321906489068787 🔹 0.702957467284194 🔹
82 MMCP

 MAG
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5314123435443265 🔹 0.8074969769458444 🔹
83 MAG
yfinance.Ticker object <MGLUY> earnings history failed to load

 MGLUY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5069477804135039 🔹 0.9351620333824073 🔹
84 MGLUY
yfinance.Ticker object <MALJF> earnings history failed to load

 MALJF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4715413448041905 🔹 0.6076111055564694 🔹
85 MALJF
yfinance.Ticker object <MAGE> earnings history failed to load

 MAGE
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.42563823978712834 🔹 0.6006735183173484 🔹
86 MAGE
yfinance.Ticker object <MEGL> balancesheet failed to load
yfinance.Ticker object <MEGL> cashflow failed to load
yfinance.Ticker object <MEGL> earnings history failed to load

 MEGL
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4394286514541855 🔹 0.24038178249093387 🔹
87 MEGL

 MGA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2981850359346966 🔹 0.5837615174455519 🔹
88 MGA
yfinance.Ticker object <MGMNF> incomestmt failed to load
yfinance.Ticker object <MGMNF> earnings history failed to load

 MGMNF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4776461392335021 🔹 0.818620587905724 🔹
89 MGMNF
yfinance.Ticker object <BRIOF> earnings history failed to load

 BRIOF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4484544157565554 🔹 0.8120803196258126 🔹
90 BRIOF

 MX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2999061522646688 🔹 0.32858650683330426 🔹
91 MX
yfinance.Ticker object <MAGN> incomestmt failed to load
yfinance.Ticker object <MAGN> earnings history failed to load

 MAGN
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.465191031481189 🔹 0.8814152939711978 🔹
92 MAGN
yfinance.Ticker object <MNSEF> balancesheet failed to load
yfinance.Ticker object <MNSEF> cashflow failed to load
yfinance.Ticker object <MNSEF> incomestmt failed to load
yfinance.Ticker object <MNSEF> earnings history failed to load

 MNSEF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
93 MNSEF

 MGY
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.39416630108628253 🔹 0.5761597332537388 🔹
94 MGY
yfinance.Ticker object <MYTAY> earnings history failed to load

 MYTAY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.48942731706588816 🔹 0.8896339960522659 🔹
95 MYTAY
yfinance.Ticker object <MAHMF> balancesheet failed to load
yfinance.Ticker object <MAHMF> cashflow failed to load
yfinance.Ticker object <MAHMF> earnings history failed to load

 MAHMF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4477878888870747 🔹 0.42503294436041444 🔹
96 MAHMF

 MAIA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.37094872050279076 🔹 0.2972052839172052 🔹
97 MAIA

 MAIN
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3804942795279267 🔹 0.3083381062957677 🔹
98 MAIN
yfinance.Ticker object <MSWV> cashflow failed to load
yfinance.Ticker object <MSWV> incomestmt failed to load
yfinance.Ticker object <MSWV> earnings history failed to load

 MSWV
 Successful: 4
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 6
       ['cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with cashflow: at least one array or dtype is required
Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

🔹 0.46251810414761807 🔹 0.18749261053300484 🔹
99 MSWV

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MNSBP> incomestmt failed to load
yfinance.Ticker object <MNSBP> earnings history failed to load

 MNSBP
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5162559051390923 🔹 0.6748795383171391 🔹
100 MNSBP
yfinance.Ticker object <MEQYF> incomestmt failed to load
yfinance.Ticker object <MEQYF> earnings history failed to load

 MEQYF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4664599736321159 🔹 0.8388208069113684 🔹
101 MEQYF
yfinance.Ticker object <MSCH> balancesheet failed to load
yfinance.Ticker object <MSCH> cashflow failed to load
yfinance.Ticker object <MSCH> incomestmt failed to load
yfinance.Ticker object <MSCH> earnings history failed to load

 MSCH
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
102 MSCH
yfinance.Ticker object <MYNZ> balancesheet failed to load
yfinance.Ticker object <MYNZ> cashflow failed to load
yfinance.Ticker object <MYNZ> earnings history failed to load

 MYNZ
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.42845294731282146 🔹 0.0708068967140599 🔹
103 MYNZ
yfinance.Ticker object <MASN> balancesheet failed to load
yfinance.Ticker object <MASN> cashflow failed to load
yfinance.Ticker object <MASN> incomestmt failed to load
yfinance.Ticker object <MASN> earnings history failed to load

 MASN
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
104 MASN
yfinance.Ticker object <MSS> incomestmt failed to load
yfinance.Ticker object <MSS> earnings history failed to load

 MSS
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4591053666872986 🔹 0.7125145333828615 🔹
105 MSS
yfinance.Ticker object <MJGCF> earnings history failed to load

 MJGCF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.42831117023889 🔹 0.29886700178615694 🔹
106 MJGCF
yfinance.Ticker object <MJDLF> earnings history failed to load

 MJDLF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.46921732141596073 🔹 0.775363285097963 🔹
107 MJDLF

 MMYT
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4723731817620075 🔹 0.6801143471083204 🔹
108 MMYT
yfinance.Ticker object <MKTAY> balancesheet failed to load
yfinance.Ticker object <MKTAY> cashflow failed to load
yfinance.Ticker object <MKTAY> incomestmt failed to load
yfinance.Ticker object <MKTAY> earnings history failed to load

 MKTAY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44631344726698013 🔹 0.7586470017334183 🔹
109 MKTAY
yfinance.Ticker object <MAKOF> earnings history failed to load

 MAKOF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.49121099009702685 🔹 0.8614927923851072 🔹
110 MAKOF
yfinance.Ticker object <MLGF> balancesheet failed to load
yfinance.Ticker object <MLGF> cashflow failed to load
yfinance.Ticker object <MLGF> earnings history failed to load

 MLGF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4609364347698992 🔹 0.8013270863231996 🔹
111 MLGF
yfinance.Ticker object <MLYBY> earnings history failed to load

 MLYBY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5484001426047753 🔹 0.8870407559156481 🔹
112 MLYBY
yfinance.Ticker object <MBUU> incomestmt failed to load

 MBUU
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5156900013785243 🔹 0.229715631498653 🔹
113 MBUU

 MAMA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5202677415758657 🔹 0.6476990651608519 🔹
114 MAMA
yfinance.Ticker object <TUSK> earnings history failed to load

 TUSK
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4628334344632056 🔹 0.5538779749598024 🔹
115 TUSK
yfinance.Ticker object <MNGPF> balancesheet failed to load
yfinance.Ticker object <MNGPF> cashflow failed to load
yfinance.Ticker object <MNGPF> earnings history failed to load

 MNGPF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.455303106721587 🔹 0.23656588714260268 🔹
116 MNGPF
yfinance.Ticker object <MAWHF> balancesheet failed to load
yfinance.Ticker object <MAWHF> cashflow failed to load
yfinance.Ticker object <MAWHF> earnings history failed to load

 MAWHF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4648464847546845 🔹 0.1083227356435803 🔹
117 MAWHF
yfinance.Ticker object <MANU> incomestmt failed to load

 MANU
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.37638345165247733 🔹 0.3322821949023532 🔹
118 MANU
yfinance.Ticker object <MNDJF> earnings history failed to load

 MNDJF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5066642497630751 🔹 0.5890509397915186 🔹
119 MNDJF
yfinance.Ticker object <MAORF> balancesheet failed to load
yfinance.Ticker object <MAORF> cashflow failed to load
yfinance.Ticker object <MAORF> earnings history failed to load

 MAORF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47158485422205776 🔹 0.17489488866817493 🔹
120 MAORF
yfinance.Ticker object <MANDF> incomestmt failed to load
yfinance.Ticker object <MANDF> earnings history failed to load

 MANDF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1
- high_1_2
- numberOfAnalysts_1_2

🔹 0.4605061314418537 🔹 0.42914974399469275 🔹
121 MANDF
yfinance.Ticker object <MNXXF> incomestmt failed to load
yfinance.Ticker object <MNXXF> earnings history failed to load

 MNXXF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46106722554013646 🔹 0.9264736452379441 🔹
122 MNXXF
yfinance.Ticker object <MGRX> incomestmt failed to load
yfinance.Ticker object <MGRX> earnings history failed to load

 MGRX
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.5086514310751952 🔹 0.814279335891999 🔹
123 MGRX
yfinance.Ticker object <MANH> incomestmt failed to load

 MANH
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5523727802164156 🔹 0.7676515310420214 🔹
124 MANH

 MTW
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3166815324310311 🔹 0.5554107328965994 🔹
125 MTW
yfinance.Ticker object <MANVF> earnings history failed to load

 MANVF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.40296099149865106 🔹 0.12503316909895273 🔹
126 MANVF

 MNKD
 Successful: 7
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est', 'meta']
 Failed: 3
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- surprisePercent_3

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- growth_1
- growth_3
- surprisePercent_3
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- growth_1
- growth_3
- surprisePercent_3
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.37526597554288277 🔹 0.1791096142185364 🔹
127 MNKD
yfinance.Ticker object <MAN> incomestmt failed to load

 MAN
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.35624480519174495 🔹 0.34795255281442605 🔹
128 MAN

 MFC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5357941140653696 🔹 0.74553824621392 🔹
129 MFC
yfinance.Ticker object <MPFRF> balancesheet failed to load
yfinance.Ticker object <MPFRF> cashflow failed to load
yfinance.Ticker object <MPFRF> earnings history failed to load

 MPFRF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.46462998905355424 🔹 0.6911414455887596 🔹
130 MPFRF
yfinance.Ticker object <MPFRY> balancesheet failed to load
yfinance.Ticker object <MPFRY> cashflow failed to load
yfinance.Ticker object <MPFRY> earnings history failed to load

 MPFRY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.46166511282964917 🔹 0.18657330693982976 🔹
131 MPFRY

 MGMLF
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

🔹 0.44611666217793744 🔹 0.6924040645771871 🔹
132 MGMLF

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MLFNF> earnings history failed to load

 MLFNF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4538814142451812 🔹 0.8898443848499288 🔹
133 MLFNF
yfinance.Ticker object <MGWFF> balancesheet failed to load
yfinance.Ticker object <MGWFF> cashflow failed to load
yfinance.Ticker object <MGWFF> incomestmt failed to load
yfinance.Ticker object <MGWFF> earnings history failed to load

 MGWFF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
134 MGWFF

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

 CART
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5720108101636313 🔹 0.7110694612430977 🔹
135 CART
yfinance.Ticker object <MAPGF> earnings history failed to load

 MAPGF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.42568809761043397 🔹 0.7820498541280134 🔹
136 MAPGF
yfinance.Ticker object <MAQC> balancesheet failed to load
yfinance.Ticker object <MAQC> cashflow failed to load
yfinance.Ticker object <MAQC> incomestmt failed to load
yfinance.Ticker object <MAQC> earnings history failed to load

 MAQC
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47643399533305564 🔹 0.19332190104856867 🔹
137 MAQC

 MARA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4825914688911326 🔹 0.863477319140237 🔹
138 MARA
yfinance.Ticker object <MBBC> incomestmt failed to load
yfinance.Ticker object <MBBC> earnings history failed to load

 MBBC
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.425884131589386 🔹 0.24089782489254635 🔹
139 MBBC

 MPC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5788563846754895 🔹 0.6257447052131034 🔹
140 MPC

 MRVI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4397489329583917 🔹 0.2922355232055831 🔹
141 MRVI
yfinance.Ticker object <MRPMF> balancesheet failed to load
yfinance.Ticker object <MRPMF> cashflow failed to load
yfinance.Ticker object <MRPMF> earnings history failed to load

 MRPMF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4487558554984186 🔹 0.2600562969578284 🔹
142 MRPMF
yfinance.Ticker object <MMI> incomestmt failed to load

 MMI
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4836316234019502 🔹 0.22559285373946414 🔹
143 MMI

 MCS
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_3
- yearAgoEps_3

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_3
- yearAgoEps_3

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.36118391402359895 🔹 0.2563283949325743 🔹
144 MCS
yfinance.Ticker object <MRX> cashflow failed to load
yfinance.Ticker object <MRX> incomestmt failed to load

 MRX
 Successful: 7
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est']
 Failed: 3
       ['cashflow', 'incomestmt', 'meta']

Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.38914767420792457 🔹 0.16572845798410568 🔹
145 MRX
yfinance.Ticker object <MRRTY> earnings history failed to load

 MRRTY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4828893478544364 🔹 0.6759474585647346 🔹
146 MRRTY
yfinance.Ticker object <MAJI> balancesheet failed to load
yfinance.Ticker object <MAJI> cashflow failed to load
yfinance.Ticker object <MAJI> incomestmt failed to load
yfinance.Ticker object <MAJI> earnings history failed to load

 MAJI
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
147 MAJI
yfinance.Ticker object <MARIF> earnings history failed to load

 MARIF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4700681194059963 🔹 0.7869521726457204 🔹
148 MARIF

 MRMD
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4473459476854713 🔹 0.2478567571037031 🔹
149 MRMD
yfinance.Ticker object <MRIN> balancesheet failed to load
yfinance.Ticker object <MRIN> cashflow failed to load
yfinance.Ticker object <MRIN> incomestmt failed to load
yfinance.Ticker object <MRIN> earnings history failed to load

 MRIN
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
150 MRIN
yfinance.Ticker object <MBOF> balancesheet failed to load
yfinance.Ticker object <MBOF> cashflow failed to load
yfinance.Ticker object <MBOF> earnings history failed to load

 MBOF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.446919268739986 🔹 0.3257162410861417 🔹
151 MBOF
yfinance.Ticker object <MARPS> cashflow failed to load
yfinance.Ticker object <MARPS> incomestmt failed to load
yfinance.Ticker object <MARPS> earnings history failed to load

 MARPS
 Successful: 4
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 6
       ['cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with cashflow: at least one array or dtype is required
Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44309381258274516 🔹 0.3314293090143834 🔹
152 MARPS
yfinance.Ticker object <HZO> incomestmt failed to load

 HZO
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47104540130707273 🔹 0.21176580687002744 🔹
153 HZO
yfinance.Ticker object <MTEK> balancesheet failed to load
yfinance.Ticker object <MTEK> cashflow failed to load
yfinance.Ticker object <MTEK> earnings history failed to load

 MTEK
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5092801597574156 🔹 0.9625506844300626 🔹
154 MTEK
yfinance.Ticker object <MAXQF> earnings history failed to load

 MAXQF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4015078232029127 🔹 0.22167581726579788 🔹
155 MAXQF
yfinance.Ticker object <MRTMD> earnings history failed to load

 MRTMD
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4612994817917616 🔹 0.7008409138764167 🔹
156 MRTMD
yfinance.Ticker object <MKL> incomestmt failed to load

 MKL
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4825421015022005 🔹 0.33338349136838374 🔹
157 MKL

 MRKR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45842879335691894 🔹 0.6359251545285481 🔹
158 MRKR

 MKTX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.14876608926630883 🔹 0.03250012784714563 🔹
159 MKTX
yfinance.Ticker object <MAAL> balancesheet failed to load
yfinance.Ticker object <MAAL> cashflow failed to load
yfinance.Ticker object <MAAL> incomestmt failed to load
yfinance.Ticker object <MAAL> earnings history failed to load

 MAAL
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
160 MAAL

 MKTW
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3587612518597129 🔹 0.26707936248933284 🔹
161 MKTW
yfinance.Ticker object <RVBR> balancesheet failed to load
yfinance.Ticker object <RVBR> cashflow failed to load
yfinance.Ticker object <RVBR> incomestmt failed to load
yfinance.Ticker object <RVBR> earnings history failed to load

 RVBR
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
162 RVBR
yfinance.Ticker object <MAKSY> balancesheet failed to load
yfinance.Ticker object <MAKSY> cashflow failed to load
yfinance.Ticker object <MAKSY> incomestmt failed to load
yfinance.Ticker object <MAKSY> earnings history failed to load

 MAKSY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4876536587059223 🔹 0.7766563221085787 🔹
163 MAKSY
yfinance.Ticker object <MRLWF> balancesheet failed to load
yfinance.Ticker object <MRLWF> cashflow failed to load
yfinance.Ticker object <MRLWF> incomestmt failed to load
yfinance.Ticker object <MRLWF> earnings history failed to load

 MRLWF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4704857132763709 🔹 0.2705632300921265 🔹
164 MRLWF

 MQ
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.33349082951926245 🔹 0.470453631348419 🔹
165 MQ
yfinance.Ticker object <MNAT> incomestmt failed to load
yfinance.Ticker object <MNAT> earnings history failed to load

 MNAT
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4336067204120737 🔹 0.2843775863736641 🔹
166 MNAT
yfinance.Ticker object <TMGID> incomestmt failed to load
yfinance.Ticker object <TMGID> earnings history failed to load

 TMGID
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.5071210583181022 🔹 0.7590950817271699 🔹
167 TMGID
yfinance.Ticker object <MAR> incomestmt failed to load

 MAR
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7763135465538624 🔹 0.9449766862830773 🔹
168 MAR

 VAC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6906233265123889 🔹 0.9199285125836725 🔹
169 VAC

 MMC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.26166976681882714 🔹 0.06302790371292433 🔹
170 MMC
yfinance.Ticker object <MRTN> incomestmt failed to load

 MRTN
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2570365471392126 🔹 0.16119753995669756 🔹
171 MRTN
yfinance.Ticker object <MRT> balancesheet failed to load
yfinance.Ticker object <MRT> cashflow failed to load
yfinance.Ticker object <MRT> earnings history failed to load

 MRT
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.45915019201248025 🔹 0.1712083242868695 🔹
172 MRT

 MLM
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7909262455658781 🔹 0.9701705168811445 🔹
173 MLM
yfinance.Ticker object <MRETF> earnings history failed to load

 MRETF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.39838409717076506 🔹 0.7658528782677275 🔹
174 MRETF
yfinance.Ticker object <MARUF> balancesheet failed to load
yfinance.Ticker object <MARUF> cashflow failed to load
yfinance.Ticker object <MARUF> incomestmt failed to load
yfinance.Ticker object <MARUF> earnings history failed to load

 MARUF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4288155104248915 🔹 0.7420786630491201 🔹
175 MARUF

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MARUY> balancesheet failed to load
yfinance.Ticker object <MARUY> cashflow failed to load
yfinance.Ticker object <MARUY> earnings history failed to load

 MARUY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4978881531847303 🔹 0.9176177213266891 🔹
176 MARUY
yfinance.Ticker object <MAURY> balancesheet failed to load
yfinance.Ticker object <MAURY> cashflow failed to load
yfinance.Ticker object <MAURY> earnings history failed to load

 MAURY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.44505025976567003 🔹 0.6129260051725327 🔹
177 MAURY
yfinance.Ticker object <MBCOF> earnings history failed to load

 MBCOF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with incomestmt: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Pretax Income_1

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4553588679674516 🔹 0.6517694915681065 🔹
178 MBCOF

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MARVF> earnings history failed to load

 MARVF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44647680164577674 🔹 0.5894714474942365 🔹
179 MARVF

 MRVL
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7789281924506058 🔹 0.9307204728761518 🔹
180 MRVL
yfinance.Ticker object <MVNC> earnings history failed to load

 MVNC
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4870327645504384 🔹 0.9385435673492196 🔹
181 MVNC
yfinance.Ticker object <MGLD> incomestmt failed to load
yfinance.Ticker object <MGLD> earnings history failed to load

 MGLD
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4972400584082225 🔹 0.9601609740260109 🔹
182 MGLD

 MAS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.10405022736081453 🔹 0.03234303629839489 🔹
183 MAS

 MASI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6910398925336829 🔹 0.2417398279982617 🔹
184 MASI
yfinance.Ticker object <GNYPF> incomestmt failed to load
yfinance.Ticker object <GNYPF> earnings history failed to load

 GNYPF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.5003909948900954 🔹 0.8084497024692615 🔹
185 GNYPF
yfinance.Ticker object <MGPHF> incomestmt failed to load
yfinance.Ticker object <MGPHF> earnings history failed to load

 MGPHF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5045749649957334 🔹 0.4284006304723851 🔹
186 MGPHF
yfinance.Ticker object <MMMW> balancesheet failed to load
yfinance.Ticker object <MMMW> cashflow failed to load
yfinance.Ticker object <MMMW> incomestmt failed to load
yfinance.Ticker object <MMMW> earnings history failed to load

 MMMW
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
187 MMMW
yfinance.Ticker object <MSSEL> balancesheet failed to load
yfinance.Ticker object <MSSEL> cashflow failed to load
yfinance.Ticker object <MSSEL> incomestmt failed to load
yfinance.Ticker object <MSSEL> earnings history failed to load

 MSSEL
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4814427286106826 🔹 0.3282261397340851 🔹
188 MSSEL
yfinance.Ticker object <MAMO> incomestmt failed to load
yfinance.Ticker object <MAMO> earnings history failed to load

 MAMO
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4782264527063488 🔹 0.9084842766840645 🔹
189 MAMO

 MTZ
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7098614636221741 🔹 0.9276331628553331 🔹
190 MTZ

 MHH
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.41454888096127807 🔹 0.29820808221199435 🔹
191 MHH
yfinance.Ticker object <MBC> incomestmt failed to load

 MBC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.33216592388624233 🔹 0.14219378303589403 🔹
192 MBC

 MA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7986238246996965 🔹 0.9249082795111795 🔹
193 MA
yfinance.Ticker object <MCFT> incomestmt failed to load

 MCFT
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6574039337434482 🔹 0.805312327086499 🔹
194 MCFT
yfinance.Ticker object <MMND> balancesheet failed to load
yfinance.Ticker object <MMND> cashflow failed to load
yfinance.Ticker object <MMND> incomestmt failed to load
yfinance.Ticker object <MMND> earnings history failed to load

 MMND
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
195 MMND

 MTDR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3349623423384285 🔹 0.24404473330388168 🔹
196 MTDR

 MTCH
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.10844606169930492 🔹 0.02989615276616912 🔹
197 MTCH

 MTLS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4443601112263712 🔹 0.6952879911225368 🔹
198 MTLS

 MTRN
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3281547452652734 🔹 0.7363843545044975 🔹
199 MTRN

 MTRN
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3281547452652734 🔹 0.7363843545044975 🔹
200 MTRN
yfinance.Ticker object <MTRX> incomestmt failed to load

 MTRX
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4108017451017928 🔹 0.31457649784563824 🔹
201 MTRX

 MATX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.40394568156948407 🔹 0.2036829472635543 🔹
202 MATX
yfinance.Ticker object <MAT> incomestmt failed to load

 MAT
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.537979611822946 🔹 0.7850036916841462 🔹
203 MAT

 MATW
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4306849466838797 🔹 0.4153359070083457 🔹
204 MATW
yfinance.Ticker object <MTTRF> earnings history failed to load

 MTTRF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4239009920487238 🔹 0.8592767616330284 🔹
205 MTTRF
yfinance.Ticker object <MCHT> balancesheet failed to load
yfinance.Ticker object <MCHT> cashflow failed to load
yfinance.Ticker object <MCHT> earnings history failed to load

 MCHT
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.4438414108402776 🔹 0.10430703697528154 🔹
206 MCHT
yfinance.Ticker object <MKGP> balancesheet failed to load
yfinance.Ticker object <MKGP> cashflow failed to load
yfinance.Ticker object <MKGP> incomestmt failed to load
yfinance.Ticker object <MKGP> earnings history failed to load

 MKGP
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
207 MKGP

 MIGI
 Successful: 7
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est']
 Failed: 3
       ['earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- high_1_2
- numberOfAnalysts_1_2

🔹 0.4162241236958555 🔹 0.56319188727708 🔹
208 MIGI

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MAXXF> incomestmt failed to load
yfinance.Ticker object <MAXXF> earnings history failed to load

 MAXXF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.44074058215380085 🔹 0.36761020163418456 🔹
209 MAXXF

 MXCT
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3062807808888133 🔹 0.20543108684471567 🔹
210 MXCT

 MMS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5876126420738477 🔹 0.5587789438347703 🔹
211 MMS

 MXL
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4357286097389554 🔹 0.1478190704781283 🔹
212 MXL
yfinance.Ticker object <MRTI> balancesheet failed to load
yfinance.Ticker object <MRTI> cashflow failed to load
yfinance.Ticker object <MRTI> incomestmt failed to load
yfinance.Ticker object <MRTI> earnings history failed to load

 MRTI
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4819258748351435 🔹 0.317123584993316 🔹
213 MRTI
yfinance.Ticker object <MAYX> balancesheet failed to load
yfinance.Ticker object <MAYX> cashflow failed to load
yfinance.Ticker object <MAYX> incomestmt failed to load
yfinance.Ticker object <MAYX> earnings history failed to load

 MAYX
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47653380960329283 🔹 0.7740547899256951 🔹
214 MAYX
yfinance.Ticker object <MFGCF> earnings history failed to load

 MFGCF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.37668815188764637 🔹 0.05314815118172386 🔹
215 MFGCF
yfinance.Ticker object <MAYNF> balancesheet failed to load
yfinance.Ticker object <MAYNF> cashflow failed to load
yfinance.Ticker object <MAYNF> incomestmt failed to load
yfinance.Ticker object <MAYNF> earnings history failed to load

 MAYNF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46735423609324994 🔹 0.6512095642976966 🔹
216 MAYNF

 MEC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3141908706384569 🔹 0.3208587913991305 🔹
217 MEC
yfinance.Ticker object <MZDAF> balancesheet failed to load
yfinance.Ticker object <MZDAF> cashflow failed to load
yfinance.Ticker object <MZDAF> incomestmt failed to load
yfinance.Ticker object <MZDAF> earnings history failed to load

 MZDAF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4334892672835975 🔹 0.2746859742332818 🔹
218 MZDAF
yfinance.Ticker object <MZDAY> balancesheet failed to load
yfinance.Ticker object <MZDAY> cashflow failed to load
yfinance.Ticker object <MZDAY> incomestmt failed to load
yfinance.Ticker object <MZDAY> earnings history failed to load

 MZDAY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.43303172820538766 🔹 0.2295910337389517 🔹
219 MZDAY

 MBI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3322868844671142 🔹 0.0987836916057935 🔹
220 MBI
yfinance.Ticker object <MBKL> balancesheet failed to load
yfinance.Ticker object <MBKL> cashflow failed to load
yfinance.Ticker object <MBKL> earnings history failed to load

 MBKL
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.450996743409642 🔹 0.557306089816349 🔹
221 MBKL
yfinance.Ticker object <MBX> incomestmt failed to load
yfinance.Ticker object <MBX> earnings history failed to load

 MBX
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5641965919889308 🔹 0.8854729308149407 🔹
222 MBX
yfinance.Ticker object <MSMY> balancesheet failed to load
yfinance.Ticker object <MSMY> cashflow failed to load
yfinance.Ticker object <MSMY> incomestmt failed to load
yfinance.Ticker object <MSMY> earnings history failed to load

 MSMY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
223 MSMY
yfinance.Ticker object <MAMTF> earnings history failed to load

 MAMTF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4870765793046213 🔹 0.7481448405802236 🔹
224 MAMTF
yfinance.Ticker object <MCBRF> balancesheet failed to load
yfinance.Ticker object <MCBRF> cashflow failed to load
yfinance.Ticker object <MCBRF> incomestmt failed to load
yfinance.Ticker object <MCBRF> earnings history failed to load

 MCBRF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45053675222894946 🔹 0.8321304154460575 🔹
225 MCBRF
yfinance.Ticker object <MKC> incomestmt failed to load

 MKC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3559302315701991 🔹 0.20692157652643672 🔹
226 MKC
yfinance.Ticker object <MCCRF> earnings history failed to load

 MCCRF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.41861649565969283 🔹 0.30347499871992245 🔹
227 MCCRF
yfinance.Ticker object <MCDIF> balancesheet failed to load
yfinance.Ticker object <MCDIF> cashflow failed to load
yfinance.Ticker object <MCDIF> incomestmt failed to load
yfinance.Ticker object <MCDIF> earnings history failed to load

 MCDIF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47366542813891377 🔹 0.15092328551582643 🔹
228 MCDIF

 MCD
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7199388422199533 🔹 0.9601788526932831 🔹
229 MCD
yfinance.Ticker object <MDNDF> balancesheet failed to load
yfinance.Ticker object <MDNDF> cashflow failed to load
yfinance.Ticker object <MDNDF> incomestmt failed to load
yfinance.Ticker object <MDNDF> earnings history failed to load

 MDNDF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.43646520128880534 🔹 0.7986769615370293 🔹
230 MDNDF

 MUX
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- yearAgoEps_1
- yearAgoEps_2
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- yearAgoEps_1
- yearAgoEps_2
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4984857650110611 🔹 0.3002081457112199 🔹
231 MUX
yfinance.Ticker object <MCFNF> earnings history failed to load

 MCFNF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

🔹 0.4393483703588329 🔹 0.7522801291730754 🔹
232 MCFNF
yfinance.Ticker object <MGRC> incomestmt failed to load

 MGRC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4823594796124996 🔹 0.19433198028895787 🔹
233 MGRC
yfinance.Ticker object <GLFN> balancesheet failed to load
yfinance.Ticker object <GLFN> cashflow failed to load
yfinance.Ticker object <GLFN> incomestmt failed to load
yfinance.Ticker object <GLFN> earnings history failed to load

 GLFN
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.45806042407909303 🔹
234 GLFN

 MCK
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7230488047885801 🔹 0.9551774205152748 🔹
235 MCK
yfinance.Ticker object <MCRAA> balancesheet failed to load
yfinance.Ticker object <MCRAA> cashflow failed to load
yfinance.Ticker object <MCRAA> incomestmt failed to load
yfinance.Ticker object <MCRAA> earnings history failed to load

 MCRAA
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4798729026779899 🔹 0.2310260550903793 🔹
236 MCRAA
yfinance.Ticker object <MCRAB> balancesheet failed to load
yfinance.Ticker object <MCRAB> cashflow failed to load
yfinance.Ticker object <MCRAB> incomestmt failed to load
yfinance.Ticker object <MCRAB> earnings history failed to load

 MCRAB
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.48081440835603495 🔹 0.2960819784882573 🔹
237 MCRAB

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

([np.float64(0.4061109482720391),
  np.float64(0.45806042407909303),
  np.float64(0.9332696601713408),
  np.float64(0.9001412527201273),
  np.float64(0.6381591789377269),
  np.float64(0.3209963098378987),
  np.float64(0.16009121168393284),
  np.float64(0.4224334176242472),
  np.float64(0.5825331993969588),
  np.float64(0.7089187542278808),
  np.float64(0.757027039814911),
  np.float64(0.6447308645207822),
  np.float64(0.1569352808018133),
  np.float64(0.6069486410506952),
  np.float64(0.8887499122051088),
  np.float64(0.2346607557052426),
  np.float64(0.9200322267013091),
  np.float64(0.31932737244392206),
  np.float64(0.5791860054117007),
  np.float64(0.5028652946344497),
  np.float64(0.9401386853777152),
  np.float64(0.1763527196587094),
  np.float64(0.24224062279566064),
  np.float64(0.3333558539357718),
  np.float64(0.6300631765848578),
  np.float64(0.6203445067785902),
  np.float64(0.4835743826633062),
  np.float64(0.45806042407909303),
  np.float64(0.20642912834307225),
  np.float64(0.8398392187999789),
  np.float64(0.39891602563551265),
  np.float64(0.9022423007282052),
  np.float64(0.33640134747619743),
  np.float64(0.146332890964285),
  np.float64(0.7959105838930635),
  np.float64(0.19773839859037057),
  np.float64(0.4961963519532042),
  np.float64(0.45806042407909303),
  np.float64(0.602114366744858),
  np.float64(0.7597817571462988),
  np.float64(0.42705983254669366),
  np.float64(0.5906683577306318),
  np.float64(0.5276816426104789),
  np.float64(0.18478484913969562),
  np.float64(0.680491048423369),
  np.float64(0.2669326249520167),
  np.float64(0.8311816710073405),
  np.float64(0.8292849027044227),
  np.float64(0.818063137188245),
  np.float64(0.82633639529526),
  np.float64(0.5591639825022132),
  np.float64(0.27485617191148365),
  np.float64(0.28931475425488584),
  np.float64(0.45806042407909303),
  np.float64(0.2498095008657228),
  np.float64(0.6125521413051257),
  np.float64(0.9651737364068453),
  np.float64(0.7017508681403662),
  np.float64(0.27478636093851816),
  np.float64(0.3551483326786721),
  np.float64(0.19363131619382318),
  np.float64(0.18568039509339046),
  np.float64(0.770139161784602),
  np.float64(0.767388240195794),
  np.float64(0.2967956572876522),
  np.float64(0.30892298439375543),
  np.float64(0.6384532605957396),
  np.float64(0.4382126539799338),
  np.float64(0.15092328551582643),
  np.float64(0.6763380110162576),
  np.float64(0.7774147735618433),
  np.float64(0.850945634449433),
  np.float64(0.7441201969255253),
  np.float64(0.45806042407909303),
  np.float64(0.6852582198985564),
  np.float64(0.1995296051409008),
  np.float64(0.7548393917213847),
  np.float64(0.2894897012068527),
  np.float64(0.45806042407909303),
  np.float64(0.7669476658819556),
  np.float64(0.6946215269029817),
  np.float64(0.23027273799785092),
  np.float64(0.702957467284194),
  np.float64(0.8074969769458444),
  np.float64(0.9351620333824073),
  np.float64(0.6076111055564694),
  np.float64(0.6006735183173484),
  np.float64(0.24038178249093387),
  np.float64(0.5837615174455519),
  np.float64(0.818620587905724),
  np.float64(0.8120803196258126),
  np.float64(0.32858650683330426),
  np.float64(0.8814152939711978),
  np.float64(0.45806042407909303),
  np.float64(0.5761597332537388),
  np.float64(0.8896339960522659),
  np.float64(0.42503294436041444),
  np.float64(0.2972052839172052),
  np.float64(0.3083381062957677),
  np.float64(0.18749261053300484),
  np.float64(0.6748795383171391),
  np.float64(0.8388208069113684),
  np.float64(0.45806042407909303),
  np.float64(0.0708068967140599),
  np.float64(0.45806042407909303),
  np.float64(0.7125145333828615),
  np.float64(0.29886700178615694),
  np.float64(0.775363285097963),
  np.float64(0.6801143471083204),
  np.float64(0.7586470017334183),
  np.float64(0.8614927923851072),
  np.float64(0.8013270863231996),
  np.float64(0.8870407559156481),
  np.float64(0.229715631498653),
  np.float64(0.6476990651608519),
  np.float64(0.5538779749598024),
  np.float64(0.23656588714260268),
  np.float64(0.1083227356435803),
  np.float64(0.3322821949023532),
  np.float64(0.5890509397915186),
  np.float64(0.17489488866817493),
  np.float64(0.42914974399469275),
  np.float64(0.9264736452379441),
  np.float64(0.814279335891999),
  np.float64(0.7676515310420214),
  np.float64(0.5554107328965994),
  np.float64(0.12503316909895273),
  np.float64(0.1791096142185364),
  np.float64(0.34795255281442605),
  np.float64(0.74553824621392),
  np.float64(0.6911414455887596),
  np.float64(0.18657330693982976),
  np.float64(0.6924040645771871),
  np.float64(0.8898443848499288),
  np.float64(0.45806042407909303),
  np.float64(0.7110694612430977),
  np.float64(0.7820498541280134),
  np.float64(0.19332190104856867),
  np.float64(0.863477319140237),
  np.float64(0.24089782489254635),
  np.float64(0.6257447052131034),
  np.float64(0.2922355232055831),
  np.float64(0.2600562969578284),
  np.float64(0.22559285373946414),
  np.float64(0.2563283949325743),
  np.float64(0.16572845798410568),
  np.float64(0.6759474585647346),
  np.float64(0.45806042407909303),
  np.float64(0.7869521726457204),
  np.float64(0.2478567571037031),
  np.float64(0.45806042407909303),
  np.float64(0.3257162410861417),
  np.float64(0.3314293090143834),
  np.float64(0.21176580687002744),
  np.float64(0.9625506844300626),
  np.float64(0.22167581726579788),
  np.float64(0.7008409138764167),
  np.float64(0.33338349136838374),
  np.float64(0.6359251545285481),
  np.float64(0.03250012784714563),
  np.float64(0.45806042407909303),
  np.float64(0.26707936248933284),
  np.float64(0.45806042407909303),
  np.float64(0.7766563221085787),
  np.float64(0.2705632300921265),
  np.float64(0.470453631348419),
  np.float64(0.2843775863736641),
  np.float64(0.7590950817271699),
  np.float64(0.9449766862830773),
  np.float64(0.9199285125836725),
  np.float64(0.06302790371292433),
  np.float64(0.16119753995669756),
  np.float64(0.1712083242868695),
  np.float64(0.9701705168811445),
  np.float64(0.7658528782677275),
  np.float64(0.7420786630491201),
  np.float64(0.9176177213266891),
  np.float64(0.6129260051725327),
  np.float64(0.6517694915681065),
  np.float64(0.5894714474942365),
  np.float64(0.9307204728761518),
  np.float64(0.9385435673492196),
  np.float64(0.9601609740260109),
  np.float64(0.03234303629839489),
  np.float64(0.2417398279982617),
  np.float64(0.8084497024692615),
  np.float64(0.4284006304723851),
  np.float64(0.45806042407909303),
  np.float64(0.3282261397340851),
  np.float64(0.9084842766840645),
  np.float64(0.9276331628553331),
  np.float64(0.29820808221199435),
  np.float64(0.14219378303589403),
  np.float64(0.9249082795111795),
  np.float64(0.805312327086499),
  np.float64(0.45806042407909303),
  np.float64(0.24404473330388168),
  np.float64(0.02989615276616912),
  np.float64(0.6952879911225368),
  np.float64(0.7363843545044975),
  np.float64(0.7363843545044975),
  np.float64(0.31457649784563824),
  np.float64(0.2036829472635543),
  np.float64(0.7850036916841462),
  np.float64(0.4153359070083457),
  np.float64(0.8592767616330284),
  np.float64(0.10430703697528154),
  np.float64(0.45806042407909303),
  np.float64(0.56319188727708),
  np.float64(0.36761020163418456),
  np.float64(0.20543108684471567),
  np.float64(0.5587789438347703),
  np.float64(0.1478190704781283),
  np.float64(0.317123584993316),
  np.float64(0.7740547899256951),
  np.float64(0.05314815118172386),
  np.float64(0.6512095642976966),
  np.float64(0.3208587913991305),
  np.float64(0.2746859742332818),
  np.float64(0.2295910337389517),
  np.float64(0.0987836916057935),
  np.float64(0.557306089816349),
  np.float64(0.8854729308149407),
  np.float64(0.45806042407909303),
  np.float64(0.7481448405802236),
  np.float64(0.8321304154460575),
  np.float64(0.20692157652643672),
  np.float64(0.30347499871992245),
  np.float64(0.15092328551582643),
  np.float64(0.9601788526932831),
  np.float64(0.7986769615370293),
  np.float64(0.3002081457112199),
  np.float64(0.7522801291730754),
  np.float64(0.19433198028895787),
  np.float64(0.45806042407909303),
  np.float64(0.9551774205152748),
  np.float64(0.2310260550903793),
  np.float64(0.2960819784882573)],
 [])

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Used for testing//Final Estimator Predictions Test-2.csv")
df.shape

(238, 1)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/SP/Financial Data/Used Files/Used for testing//Final Estimator Predictions Test-2.csv")
df["label"] = np.where(df["label"] > 0.91, 1, np.where(df["label"] < 0.1, -1, 0))
print(df.to_string())

     label
0        0
1        0
2        1
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       1
17       0
18       0
19       0
20       1
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37       0
38       0
39       0
40       0
41       0
42       0
43       0
44       0
45       0
46       0
47       0
48       0
49       0
50       0
51       0
52       0
53       0
54       0
55       0
56       1
57       0
58       0
59       0
60       0
61       0
62       0
63       0
64       0
65       0
66       0
67       0
68       0
69       0
70       0
71       0
72       0
73       0
74       0
75       0
76       0
77       0
78       0
79       0
80       0
81       0
82       0
83       0
84       1
85       0
86       0
87       0
88       0
89       0
90       0
91       0
92       0
93       0
94       0
95       0
96       0
97       0
98       0
99       0
100      0
101      0
102      0
103     -1
104      0
105      0
106      0
107      0
108      0
109      0
110      0
111      0
112      0
113      0
114      0
115      0
116      0
117      0
118      0
119      0
120      0
121      0
122      1
123      0
124      0
125      0
126      0
127      0
128      0
129      0
130      0
131      0
132      0
133      0
134      0
135      0
136      0
137      0
138      0
139      0
140      0
141      0
142      0
143      0
144      0
145      0
146      0
147      0
148      0
149      0
150      0
151      0
152      0
153      0
154      1
155      0
156      0
157      0
158      0
159     -1
160      0
161      0
162      0
163      0
164      0
165      0
166      0
167      0
168      1
169      1
170     -1
171      0
172      0
173      1
174      0
175      0
176      1
177      0
178      0
179      0
180      1
181      1
182      1
183     -1
184      0
185      0
186      0
187      0
188      0
189      0
190      1
191      0
192      0
193      1
194      0
195      0
196      0
197     -1
198      0
199      0
200      0
201      0
202      0
203      0
204      0
205      0
206      0
207      0
208      0
209      0
210      0
211      0
212      0
213      0
214      0
215     -1
216      0
217      0
218      0
219      0
220     -1
221      0
222      0
223      0
224      0
225      0
226      0
227      0
228      0
229      1
230      0
231      0
232      0
233      0
234      0
235      1
236      0
237      0

In [ ]:
y = pd.DataFrame({"":label})

cr = classification_report(y[""],df)
print(cr)
cm = confusion_matrix(y[""],df)
print(cm)

              precision    recall  f1-score   support

          -1       0.86      0.06      0.11       106
           0       0.00      0.00      0.00         0
           1       0.83      0.11      0.20       132

    accuracy                           0.09       238
   macro avg       0.56      0.06      0.10       238
weighted avg       0.84      0.09      0.16       238

[[  6  97   3]
 [  0   0   0]
 [  1 116  15]]

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
label = []
error = []

for i in range(len(stocks)):
    try:
        data = yf.Ticker(stocks[i]).history(start="2025-06-01", end="2025-06-04")
        recent_close = float(data["Close"].tail(1).iloc[0])

        data = yf.Ticker(stocks[i]).history(start="2025-03-25", end="2025-03-31")
        past_close = float(data["Close"].tail(1).iloc[0])

        change = (recent_close - past_close)/past_close
        print(i, stocks[i], change)

        if change > 0.0000:
            label.append(1)
        elif change == 0.0:
            error.append(stocks[i])
        elif change<-0.0000:
            label.append(-1)
        else:
            label.append(0)
    except Exception as e:
        print(stocks[i], "failed:", e)
        error.append(stocks[i])

print(len(label))

0 LOVE 0.04825735318707736
1 LOWLF 0.07692308794464563
2 LOW 0.006949564002780175
3 LPLA 0.14669185462674197
4 LQWDF 1.394736941171156
5 LXU 0.18664643256350544
6 LYTS -0.05171033025650752
7 LTC 0.0056460123889593
8 LUCMF 0.14609429737206772
9 LUCRF -0.3199999928474426
10 LGCL 0.17021279428921557
11 LUCN 0.16898147918191966
12 LUCD -0.20253167326605756
13 LCID -0.05603443093234513
14 LKNCY -0.041279125600454394
15 LUCK -0.13491020082212826
16 LDSN 0.11111118297242212
17 LUDG -0.3088235906405812
18 LU -0.027027000903735277
19 LKFLF 0.17073178106940157
20 LULU 0.14280354347968705
21 LVLU 0.04370181881299501
22 LUMB 0.16099582416064603
23 LUMN 0.04314722685914751
24 LFT -0.02307699260727251
25 LITE 0.24081174902340582
26 LMGDF 1.1333334657881036
27 LRGR 0.35294116787706953
28 LAZR -0.4289276776349257
29 LMGIF 0.19215079872861893
30 LDXHF 0.33200005190571263
31 LUGDF 0.6642528890713504
32 LUNMF 0.1778846815140314
33 LPKGF 0.6250366863900143
34 LUVU -0.20000002980232195
35 LUXE 0.2771084644981321
36 LXFR 0.012084746519986077
37 LUXHP -0.7096774181143674
38 LUXFF 0.6806723167379092
39 LVMUY -0.14658444357568864
40 LVMHF -0.1445031797915296
41 LXP 0.0005803809634593991
42 YAHOF 0.038461561974218274
43 YAHOY 0.04291848362777176
44 LCXEF -0.3436960315453724
45 LYEL -0.26155268054765235
46 LYFT 0.3267070688287461
47 LYSCF 0.1406593054191126
48 LYSDY 0.17149231559357414
49 LYB -0.18240600319883318
50 SLMNP -0.003692181522624346
51 LYBC 0.01615332149625337
52 LYRA 2.968345421670198
53 LYTHF -0.8469387749283699
54 MFBP -0.0237729462417336
55 MGPUF 0.20300749790554662
56 MTB 0.049576828837697005
57 MHO -0.06266526236315287
58 MTWO 0.26086950606344433
59 MTHRF 0.37037037784577176
60 MTHRY 0.3303571314531928
61 MLGCF -0.4326777498841271
62 MBAVU 0.25603860104920756
63 MBAV 0.14926826663133574
64 MAAS -0.6505747093677458
65 MTAL 0.21335996014915354
66 MAC -0.06392930395745525
67 MNR -0.08941831063119986
68 MACT -0.36363636363636365
69 MKZR -0.41999995072682306
70 MTSI 0.28831115098716475
71 MQBKY 0.11267035492713719
72 DBMBF 0.1711409353016787
73 MRPT 0.021951227046987903
74 MGNX 0.19841269991445315
75 M -0.10304454039760415
76 MADGF -0.019999980926513672
77 MCBK 0.008208609533353194
78 MSET -0.6357142838136275
79 MSGE 0.10175023430231098
80 MSGS -0.028876262232975108
81 MDGL -0.132552511978245
82 MMCP -0.15384608918628043
83 MAG 0.27006374371357017
84 MGLUY 0.038402180465306836
85 MALJF 0.3777777353922526
86 MAGE -0.4277311229527339
87 MEGL -0.03262411695293947
88 MGA 0.06911760218003217
89 MGMNF 0.03750562244431289
90 BRIOF -0.03333333954215063
91 MX 0.04972377691923669
92 MAGN -0.3211160075897448
93 MNSEF -0.3333333333333333
94 MGY -0.10385143307080852
95 MYTAY 0.08522482820588746
96 MAHMF 0.1173553466796875
97 MAIA 0.08024691040060576
98 MAIN 0.0061589658572384215
99 MSWV 0.007786440505402328
100 MNSBP -0.04372465916879907
101 MEQYF 0.07578122615814209
102 MSCH -0.024880558519060455
103 MYNZ -0.444134063702249
104 MASN 0.14285715473625776
105 MSS -0.1666667218561504
106 MJGCF 0.7061539047004225
107 MJDLF 0.06690775253549311
108 MMYT -0.015747317642475125
109 MKTAY -0.07747324739049596
110 MAKOF 0.34519574674821657
111 MLGF -0.004358428089630025
112 MLYBY -0.07034227115896807
113 MBUU 0.039228943503004154
114 MAMA 0.3091482635606769
115 TUSK 0.26540294267298425
116 MNGPF -0.20136523520317778
117 MAWHF -0.15254233521108176
118 MANU 0.05658966924331519
119 MNDJF 0.04162015950336476
120 MAORF 0.08108106714865881
121 MANDF -0.061666647593180336
122 MNXXF -0.23636364252114103
123 MGRX -0.11764714132130367
124 MANH 0.0778187706506667
125 MTW 0.21259834833054972
126 MANVF -0.12741935076841324
127 MNKD -0.1212723872903469
128 MAN -0.29093268700357516
129 MFC 0.038361518088281095
130 MPFRF 0.04347821880453609
131 MPFRY 0.5285794682311117
132 MGMLF 0.7714285349359319
133 MLFNF 0.15542853219168526
134 MGWFF -0.2857142920498135
135 CART 0.15882208522511948
136 MAPGF -0.052691869940347566
137 MAQC -0.027409408321419432
138 MARA 0.22935040861540335
139 MBBC 0.018001556469437116
140 MPC 0.1303792595416555
141 MRVI -0.05932197996132164
142 MRPMF -0.19105689517941363
143 MMI -0.14662410329462297
144 MCS 0.06710479244202426
145 MRX 0.239643838675953
146 MRRTY 0.4448051686672153
147 MAJI 1.4761904874536365
148 MARIF -0.08563534601649962
149 MRMD -0.2474227136703556
150 MRIN -0.43695651253740514
151 MBOF -0.0125
152 MARPS 0.015989117786374865
153 HZO -0.009541162636869162
154 MTEK -0.11240308931345058
155 MAXQF 0.12311013937091032
156 MRTMD 0.22162155776468623
157 MKL 0.05515138261357216
158 MRKR 0.19685039665718373
159 MKTX -0.005834302090870387
160 MAAL 0.031999969482421876
161 MKTW 0.8130855194057303
162 RVBR 0.8279999222159398
163 MAKSY 0.10851794141875636
164 MRLWF 0.16931711254360507
165 MQ 0.27684960180683726
166 MNAT 0.055830366767000254
167 TMGID -0.5
168 MAR 0.11843920456558857
169 VAC 0.006625688289233653
170 MMC -0.027813622598191753
171 MRTN -0.0372807358482453
172 MRT -0.09493676664125798
173 MLM 0.14294608773821563
174 MRETF 0.22440942590682603
175 MARUF 0.2177996453719216
176 MARUY 0.21482602118003025
177 MAURY 0.04513254246015238
178 MBCOF 0.11126759661802417
179 MARVF -0.6296296475151107
180 MRVL 0.006300029510210595
181 MVNC 1.017543829550979
182 MGLD -0.005813947847045612
183 MAS -0.08415545478612077
184 MASI 0.0017120071786746788
185 GNYPF -0.32623208499584533
186 MGPHF -0.11860466224396753
187 MMMW -0.6372500116042791
188 MSSEL 0.017373621494678762
189 MAMO -0.17666666284019572
190 MTZ 0.38490239141302873
191 MHH -0.33953034993781056
192 MBC -0.22137408303489153
193 MA 0.07821349304565006
194 MCFT -0.015661279660571598
195 MMND -0.4000000223517415
196 MTDR -0.08654833021220859
197 MTCH -2.3946817395497507e-06
198 MTLS 0.08064517989739156
199 MTRN -0.06797055533858594
200 MTRN -0.06797055533858594
201 MTRX -0.009577006234351045
202 MATX -0.1040479144485056
203 MAT -0.02901551751707077
204 MATW -0.0042328540471795375
205 MTTRF -0.004160916733650934
206 MCHT 0.014087884546541234
207 MKGP -0.3428571443776695
208 MIGI 0.2745097810055187
209 MAXXF 0.17969926319920757
210 MXCT -0.1648351811500858
211 MMS 0.05612249940031426
212 MXL 0.09645135957167092
213 MRTI -0.21540654497582593
214 MAYX -0.04166672461562456
215 MFGCF 0.022823389971687036
216 MAYNF -0.2948571341378348
217 MEC 0.17738363781013536
218 MZDAF -0.12769229595477766
219 MZDAY -0.06191951904108196
220 MBI -0.10179644822005549
221 MBKL 0.012048265378223932
222 MBX 0.7603092067666631
223 MSMY 0.14285715473625776
224 MAMTF 0.104615358205942
225 MCBRF 0.39705879130371746
226 MKC -0.09422715610023841
227 MCCRF 0.34905662711467167
228 MCDIF -0.12121212121212122
229 MCD 0.02302834056651151
230 MDNDF 0.13360326220973423
231 MUX 0.167532466728222
232 MCFNF -0.27710842237899563
233 MGRC 0.029083980706134646
234 GLFN -0.9803921580656139
235 MCK 0.07114053671735121
236 MCRAA -0.0867938787418714
237 MCRAB -0.11187439417045922
238

In [ ]:
X = pd.DataFrame({"":predictions})
y = pd.DataFrame({"":label})

cr = classification_report(y[""],X[""])
print(cr)
cm = confusion_matrix(y[""],X[""])
print(cm)

              precision    recall  f1-score   support

          -1       0.57      0.04      0.08        97
           0       0.06      0.67      0.11        18
           1       0.67      0.11      0.19       123

    accuracy                           0.13       238
   macro avg       0.43      0.27      0.13       238
weighted avg       0.58      0.13      0.14       238

[[  4  90   3]
 [  2  12   4]
 [  1 108  14]]

#Other

In [ ]:
df = pd.DataFrame()
error = []

for i in range(len(stocks)):
  try:
    weighted_pred,final_est, predictions = fundemental_model(stocks[i])
    df = pd.concat([df,predictions])
  except:
    print(stocks[i])
    error.append(stocks[i])
print(df)

yfinance.Ticker object <MNXXF> incomestmt failed to load
yfinance.Ticker object <MNXXF> earnings history failed to load

 MNXXF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46106722554013646 🔹 0.9143349674402002 🔹
yfinance.Ticker object <MGRX> incomestmt failed to load
yfinance.Ticker object <MGRX> earnings history failed to load

 MGRX
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5086514310751952 🔹 0.8011598839693006 🔹
yfinance.Ticker object <MANH> incomestmt failed to load

 MANH
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5523727802164156 🔹 0.7595380745132652 🔹
LOAN

 MTW
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3166815324310311 🔹 0.5339644321053779 🔹
yfinance.Ticker object <MTEX> earnings history failed to load
MTEX
yfinance.Ticker object <MANVF> earnings history failed to load

 MANVF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.40296099149865106 🔹 0.12944964123300137 🔹

 MNKD
 Successful: 7
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est', 'meta']
 Failed: 3
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- surprisePercent_3

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- growth_1
- growth_3
- surprisePercent_3
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_3
- epsDifference_3
- growth_1
- growth_3
- surprisePercent_3
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.37526597554288277 🔹 0.18191876192334233 🔹
yfinance.Ticker object <MAN> incomestmt failed to load

 MAN
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.35624480519174495 🔹 0.39359415389342534 🔹

 MFC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5357941140653696 🔹 0.785960014065038 🔹
yfinance.Ticker object <MPFRF> balancesheet failed to load
yfinance.Ticker object <MPFRF> cashflow failed to load
yfinance.Ticker object <MPFRF> earnings history failed to load

 MPFRF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46462998905355424 🔹 0.6623931133593546 🔹
yfinance.Ticker object <MPFRY> balancesheet failed to load
yfinance.Ticker object <MPFRY> cashflow failed to load
yfinance.Ticker object <MPFRY> earnings history failed to load

 MPFRY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46166511282964917 🔹 0.19843099527727892 🔹

 MGMLF
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44611666217793744 🔹 0.7093626773858409 🔹
yfinance.Ticker object <MLFNF> earnings history failed to load

 MLFNF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4538814142451812 🔹 0.875214093372593 🔹
yfinance.Ticker object <MGWFF> balancesheet failed to load
yfinance.Ticker object <MGWFF> cashflow failed to load
yfinance.Ticker object <MGWFF> incomestmt failed to load
yfinance.Ticker object <MGWFF> earnings history failed to load

 MGWFF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹

 CART
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5720108101636313 🔹 0.7647392629039007 🔹
yfinance.Ticker object <MAPGF> earnings history failed to load

 MAPGF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.42568809761043397 🔹 0.789500891806423 🔹
yfinance.Ticker object <MAQC> balancesheet failed to load
yfinance.Ticker object <MAQC> cashflow failed to load
yfinance.Ticker object <MAQC> incomestmt failed to load
yfinance.Ticker object <MAQC> earnings history failed to load

 MAQC
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47643399533305564 🔹 0.21080325321942744 🔹

 MARA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4825914688911326 🔹 0.8862913172414153 🔹
yfinance.Ticker object <MBBC> incomestmt failed to load
yfinance.Ticker object <MBBC> earnings history failed to load

 MBBC
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.425884131589386 🔹 0.2009885356694174 🔹

 MPC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5788563846754895 🔹 0.6316081508851034 🔹

 MRVI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4397489329583917 🔹 0.3180652795462826 🔹
yfinance.Ticker object <MRPMF> balancesheet failed to load
yfinance.Ticker object <MRPMF> cashflow failed to load
yfinance.Ticker object <MRPMF> earnings history failed to load

 MRPMF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4487558554984186 🔹 0.23769179732722495 🔹
yfinance.Ticker object <MMI> incomestmt failed to load

 MMI
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4836316234019502 🔹 0.27696390502008805 🔹

 MCS
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_3
- yearAgoEps_3

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_3
- yearAgoEps_3

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.36118391402359895 🔹 0.21714678241911184 🔹
yfinance.Ticker object <MRX> cashflow failed to load
yfinance.Ticker object <MRX> incomestmt failed to load

 MRX
 Successful: 7
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est']
 Failed: 3
       ['cashflow', 'incomestmt', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with cashflow: at least one array or dtype is required
Error occurred with incomestmt: at least one array or dtype is required
Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

🔹 0.38914767420792457 🔹 0.19002793820798888 🔹

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MRRTY> earnings history failed to load

 MRRTY
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4828893478544364 🔹 0.615939440619248 🔹
yfinance.Ticker object <MAJI> balancesheet failed to load
yfinance.Ticker object <MAJI> cashflow failed to load
yfinance.Ticker object <MAJI> incomestmt failed to load
yfinance.Ticker object <MAJI> earnings history failed to load

 MAJI
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹
yfinance.Ticker object <MARIF> earnings history failed to load

 MARIF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4700681194059963 🔹 0.7462045144226224 🔹

 MRMD
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4473459476854713 🔹 0.2400140035270364 🔹
yfinance.Ticker object <MRIN> balancesheet failed to load
yfinance.Ticker object <MRIN> cashflow failed to load
yfinance.Ticker object <MRIN> incomestmt failed to load
yfinance.Ticker object <MRIN> earnings history failed to load

 MRIN
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹
yfinance.Ticker object <MBOF> balancesheet failed to load
yfinance.Ticker object <MBOF> cashflow failed to load
yfinance.Ticker object <MBOF> earnings history failed to load

 MBOF
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.446919268739986 🔹 0.31926706240933106 🔹
yfinance.Ticker object <MARPS> cashflow failed to load
yfinance.Ticker object <MARPS> incomestmt failed to load
yfinance.Ticker object <MARPS> earnings history failed to load

 MARPS
 Successful: 4
       ['balancesheet', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 6
       ['cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Free Cash Flow_1
- Free Cash Flow_2
- Free Cash Flow_3
- Free Cash Flow_4
- Free Cash Flow_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44309381258274516 🔹 0.3891571914845223 🔹
yfinance.Ticker object <MPX> incomestmt failed to load
MPX
yfinance.Ticker object <HZO> incomestmt failed to load

 HZO
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47104540130707273 🔹 0.26694300018742007 🔹
yfinance.Ticker object <MTEK> balancesheet failed to load
yfinance.Ticker object <MTEK> cashflow failed to load
yfinance.Ticker object <MTEK> earnings history failed to load

 MTEK
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5092801597574156 🔹 0.9625693259401794 🔹
yfinance.Ticker object <MAXQF> earnings history failed to load

 MAXQF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4015078232029127 🔹 0.2657187088180629 🔹
yfinance.Ticker object <MRTMD> earnings history failed to load

 MRTMD
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4612994817917616 🔹 0.7363707881461573 🔹
yfinance.Ticker object <MKL> incomestmt failed to load

 MKL
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4825421015022005 🔹 0.3133131817868886 🔹

 MRKR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45842879335691894 🔹 0.563501711412442 🔹

 MKTX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.14876608926630883 🔹 0.029873217568569085 🔹
yfinance.Ticker object <MAAL> balancesheet failed to load
yfinance.Ticker object <MAAL> cashflow failed to load
yfinance.Ticker object <MAAL> incomestmt failed to load
yfinance.Ticker object <MAAL> earnings history failed to load

 MAAL
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹

 MKTW
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3587612518597129 🔹 0.2717549409731758 🔹
yfinance.Ticker object <RVBR> balancesheet failed to load
yfinance.Ticker object <RVBR> cashflow failed to load
yfinance.Ticker object <RVBR> incomestmt failed to load
yfinance.Ticker object <RVBR> earnings history failed to load

 RVBR
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹
yfinance.Ticker object <MAKSY> balancesheet failed to load
yfinance.Ticker object <MAKSY> cashflow failed to load
yfinance.Ticker object <MAKSY> incomestmt failed to load
yfinance.Ticker object <MAKSY> earnings history failed to load

 MAKSY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4876536587059223 🔹 0.8547038998228434 🔹
yfinance.Ticker object <MRLWF> balancesheet failed to load
yfinance.Ticker object <MRLWF> cashflow failed to load
yfinance.Ticker object <MRLWF> incomestmt failed to load
yfinance.Ticker object <MRLWF> earnings history failed to load

 MRLWF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4704857132763709 🔹 0.16989430591222532 🔹
yfinance.Ticker object <MRAI> balancesheet failed to load
yfinance.Ticker object <MRAI> cashflow failed to load
yfinance.Ticker object <MRAI> incomestmt failed to load
MRAI

 MQ
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.33349082951926245 🔹 0.5147155223755023 🔹
yfinance.Ticker object <MNAT> incomestmt failed to load
yfinance.Ticker object <MNAT> earnings history failed to load

 MNAT
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4336067204120737 🔹 0.23020372852371718 🔹
yfinance.Ticker object <TMGID> incomestmt failed to load
yfinance.Ticker object <TMGID> earnings history failed to load

 TMGID
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5071210583181022 🔹 0.8013359272930107 🔹
yfinance.Ticker object <MAR> incomestmt failed to load

 MAR
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7763135465538624 🔹 0.9446664460469045 🔹

 VAC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6906233265123889 🔹 0.92985494234486 🔹

 MMC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.26166976681882714 🔹 0.06269524152439725 🔹
yfinance.Ticker object <MRTN> incomestmt failed to load

 MRTN
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.2570365471392126 🔹 0.15965683983248113 🔹
yfinance.Ticker object <MRT> balancesheet failed to load
yfinance.Ticker object <MRT> cashflow failed to load
yfinance.Ticker object <MRT> earnings history failed to load

 MRT
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45915019201248025 🔹 0.15197016033621508 🔹

 MLM
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7909262455658781 🔹 0.9676603218560473 🔹
yfinance.Ticker object <MMLP> earnings history failed to load
MMLP
yfinance.Ticker object <MRETF> earnings history failed to load

 MRETF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.39838409717076506 🔹 0.8018134340924341 🔹
yfinance.Ticker object <MARUF> balancesheet failed to load
yfinance.Ticker object <MARUF> cashflow failed to load
yfinance.Ticker object <MARUF> incomestmt failed to load
yfinance.Ticker object <MARUF> earnings history failed to load

 MARUF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4288155104248915 🔹 0.7378390289946781 🔹
yfinance.Ticker object <MARUY> balancesheet failed to load
yfinance.Ticker object <MARUY> cashflow failed to load
yfinance.Ticker object <MARUY> earnings history failed to load

 MARUY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4978881531847303 🔹 0.9301193945656626 🔹
yfinance.Ticker object <MAURY> balancesheet failed to load
yfinance.Ticker object <MAURY> cashflow failed to load
yfinance.Ticker object <MAURY> earnings history failed to load

 MAURY
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44505025976567003 🔹 0.5976380179414544 🔹
yfinance.Ticker object <MBCOF> earnings history failed to load

 MBCOF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with incomestmt: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Pretax Income_1

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4553588679674516 🔹 0.6800032032463802 🔹
yfinance.Ticker object <MARVF> earnings history failed to load

 MARVF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44647680164577674 🔹 0.6513906641384701 🔹

 MRVL
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7789281924506058 🔹 0.9397615315522345 🔹
yfinance.Ticker object <MVNC> earnings history failed to load

 MVNC
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4870327645504384 🔹 0.9478585297631784 🔹
yfinance.Ticker object <MGLD> incomestmt failed to load
yfinance.Ticker object <MGLD> earnings history failed to load

 MGLD
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4972400584082225 🔹 0.9501555353648654 🔹

 MAS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.10405022736081453 🔹 0.029921922020343224 🔹

 MASI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6910398925336829 🔹 0.25431292021036433 🔹
yfinance.Ticker object <GNYPF> incomestmt failed to load
yfinance.Ticker object <GNYPF> earnings history failed to load

 GNYPF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5003909948900954 🔹 0.8269829819508165 🔹
yfinance.Ticker object <MGPHF> incomestmt failed to load
yfinance.Ticker object <MGPHF> earnings history failed to load

 MGPHF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5045749649957334 🔹 0.6110620224143736 🔹
yfinance.Ticker object <MMMW> balancesheet failed to load
yfinance.Ticker object <MMMW> cashflow failed to load
yfinance.Ticker object <MMMW> incomestmt failed to load
yfinance.Ticker object <MMMW> earnings history failed to load

 MMMW
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹
yfinance.Ticker object <MSSEL> balancesheet failed to load
yfinance.Ticker object <MSSEL> cashflow failed to load
yfinance.Ticker object <MSSEL> incomestmt failed to load
yfinance.Ticker object <MSSEL> earnings history failed to load

 MSSEL
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4814427286106826 🔹 0.3458968138215811 🔹
yfinance.Ticker object <MAMO> incomestmt failed to load
yfinance.Ticker object <MAMO> earnings history failed to load

 MAMO
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4782264527063488 🔹 0.9077332148507454 🔹

 MTZ
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7098614636221741 🔹 0.9326269726517925 🔹

 MHH
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.41454888096127807 🔹 0.34180271105340115 🔹
yfinance.Ticker object <MBC> incomestmt failed to load

 MBC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.33216592388624233 🔹 0.17515644591671997 🔹

 MA
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7986238246996965 🔹 0.9074832454137804 🔹
yfinance.Ticker object <MCFT> incomestmt failed to load

 MCFT
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.6574039337434482 🔹 0.7814762640442817 🔹
yfinance.Ticker object <MMND> balancesheet failed to load
yfinance.Ticker object <MMND> cashflow failed to load
yfinance.Ticker object <MMND> incomestmt failed to load
yfinance.Ticker object <MMND> earnings history failed to load

 MMND
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹

 MTDR
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3349623423384285 🔹 0.2265864520256633 🔹

 MTCH
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.10844606169930492 🔹 0.029993278288100018 🔹

 MTLS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4443601112263712 🔹 0.7319505960017803 🔹

 MTRN
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3281547452652734 🔹 0.7509084864310882 🔹

 MTRN
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3281547452652734 🔹 0.7509084864310882 🔹
yfinance.Ticker object <MTRX> incomestmt failed to load

 MTRX
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4108017451017928 🔹 0.3498481669061559 🔹

 MATX
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.40394568156948407 🔹 0.20357514501550522 🔹
yfinance.Ticker object <MAT> incomestmt failed to load

 MAT
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.537979611822946 🔹 0.8332978763321456 🔹

 MATW
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4306849466838797 🔹 0.43237744026311803 🔹
yfinance.Ticker object <MTTRF> earnings history failed to load

 MTTRF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4239009920487238 🔹 0.8294959161334292 🔹
yfinance.Ticker object <MCHT> balancesheet failed to load
yfinance.Ticker object <MCHT> cashflow failed to load
yfinance.Ticker object <MCHT> earnings history failed to load

 MCHT
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4438414108402776 🔹 0.1588751421483559 🔹
MLP
yfinance.Ticker object <MKGP> balancesheet failed to load
yfinance.Ticker object <MKGP> cashflow failed to load
yfinance.Ticker object <MKGP> incomestmt failed to load
yfinance.Ticker object <MKGP> earnings history failed to load

 MKGP
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹

 MIGI
 Successful: 7
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est']
 Failed: 3
       ['earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- growth_4
- yearAgoEps_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- high_1_2
- numberOfAnalysts_1_2

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4162241236958555 🔹 0.42206142765935767 🔹
yfinance.Ticker object <MAXXF> incomestmt failed to load
yfinance.Ticker object <MAXXF> earnings history failed to load

 MAXXF
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.44074058215380085 🔹 0.40345126163357814 🔹

 MXCT
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3062807808888133 🔹 0.24191641419074644 🔹
MAXN

 MMS
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5876126420738477 🔹 0.5535375142019572 🔹

 MXL
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4357286097389554 🔹 0.14142653897109264 🔹
yfinance.Ticker object <MRTI> balancesheet failed to load
yfinance.Ticker object <MRTI> cashflow failed to load
yfinance.Ticker object <MRTI> incomestmt failed to load
yfinance.Ticker object <MRTI> earnings history failed to load

 MRTI
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4819258748351435 🔹 0.34923014715491446 🔹
yfinance.Ticker object <MAYX> balancesheet failed to load
yfinance.Ticker object <MAYX> cashflow failed to load
yfinance.Ticker object <MAYX> incomestmt failed to load
yfinance.Ticker object <MAYX> earnings history failed to load

 MAYX
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47653380960329283 🔹 0.8124826161935559 🔹
yfinance.Ticker object <MFGCF> earnings history failed to load

 MFGCF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.37668815188764637 🔹 0.07433531403581495 🔹
yfinance.Ticker object <MAYNF> balancesheet failed to load
yfinance.Ticker object <MAYNF> cashflow failed to load
yfinance.Ticker object <MAYNF> incomestmt failed to load
yfinance.Ticker object <MAYNF> earnings history failed to load

 MAYNF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.46735423609324994 🔹 0.6287964916750328 🔹

 MEC
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3141908706384569 🔹 0.30955650112100497 🔹
yfinance.Ticker object <MZDAF> balancesheet failed to load
yfinance.Ticker object <MZDAF> cashflow failed to load
yfinance.Ticker object <MZDAF> incomestmt failed to load
yfinance.Ticker object <MZDAF> earnings history failed to load

 MZDAF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4334892672835975 🔹 0.2276207562018546 🔹
yfinance.Ticker object <MZDAY> balancesheet failed to load
yfinance.Ticker object <MZDAY> cashflow failed to load
yfinance.Ticker object <MZDAY> incomestmt failed to load
yfinance.Ticker object <MZDAY> earnings history failed to load

 MZDAY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.43303172820538766 🔹 0.2142985536814873 🔹

 MBI
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3322868844671142 🔹 0.08450635742207752 🔹
yfinance.Ticker object <MBKL> balancesheet failed to load
yfinance.Ticker object <MBKL> cashflow failed to load
yfinance.Ticker object <MBKL> earnings history failed to load

 MBKL
 Successful: 4
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 6
       ['balancesheet', 'cashflow', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.450996743409642 🔹 0.72257737548919 🔹
yfinance.Ticker object <MBX> incomestmt failed to load
yfinance.Ticker object <MBX> earnings history failed to load

 MBX
 Successful: 5
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 5
       ['incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.5641965919889308 🔹 0.8808273927193082 🔹
yfinance.Ticker object <MSMY> balancesheet failed to load
yfinance.Ticker object <MSMY> cashflow failed to load
yfinance.Ticker object <MSMY> incomestmt failed to load
yfinance.Ticker object <MSMY> earnings history failed to load

 MSMY
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4575668832202 🔹 0.2959523845370976 🔹
yfinance.Ticker object <MAMTF> earnings history failed to load

 MAMTF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4870765793046213 🔹 0.8178366193049736 🔹
yfinance.Ticker object <MCBRF> balancesheet failed to load
yfinance.Ticker object <MCBRF> cashflow failed to load
yfinance.Ticker object <MCBRF> incomestmt failed to load
yfinance.Ticker object <MCBRF> earnings history failed to load

 MCBRF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.45053675222894946 🔹 0.8021037372231695 🔹
yfinance.Ticker object <MKC> incomestmt failed to load

 MKC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.3559302315701991 🔹 0.22820083392084634 🔹
yfinance.Ticker object <MCCRF> earnings history failed to load

 MCCRF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.41861649565969283 🔹 0.2909775350485774 🔹
yfinance.Ticker object <MCDIF> balancesheet failed to load
yfinance.Ticker object <MCDIF> cashflow failed to load
yfinance.Ticker object <MCDIF> incomestmt failed to load
yfinance.Ticker object <MCDIF> earnings history failed to load

 MCDIF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.47366542813891377 🔹 0.2010252472673143 🔹

 MCD
 Successful: 10
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 0
       []

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.7199388422199533 🔹 0.9601791780116977 🔹
yfinance.Ticker object <MDNDF> balancesheet failed to load
yfinance.Ticker object <MDNDF> cashflow failed to load
yfinance.Ticker object <MDNDF> incomestmt failed to load
yfinance.Ticker object <MDNDF> earnings history failed to load

 MDNDF
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.43646520128880534 🔹 0.7506699919041909 🔹

 MUX
 Successful: 8
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'rev_est', 'meta']
 Failed: 2
       ['earnings_hist_est', 'earnings_hist_est_eps']

Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- yearAgoEps_1
- yearAgoEps_2
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- growth_1
- growth_2
- growth_3
- yearAgoEps_1
- yearAgoEps_2
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4984857650110611 🔹 0.3341478619921648 🔹
yfinance.Ticker object <MCFNF> earnings history failed to load

 MCFNF
 Successful: 6
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'rev_est']
 Failed: 4
       ['earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_4
- epsEstimate_1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4393483703588329 🔹 0.7916860762114297 🔹
yfinance.Ticker object <MGRC> incomestmt failed to load

 MGRC
 Successful: 9
       ['balancesheet', 'cashflow', 'analyst_target_eps', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
 Failed: 1
       ['incomestmt']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4823594796124996 🔹 0.19930768208030838 🔹
yfinance.Ticker object <GLFN> balancesheet failed to load
yfinance.Ticker object <GLFN> cashflow failed to load
yfinance.Ticker object <GLFN> incomestmt failed to load
yfinance.Ticker object <GLFN> earnings history failed to load

 GLFN
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
Exception ignored from cffi callback <function buffer_callback at 0x7b09a3bd4c20>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/curl_cffi/curl.py", line 68, in buffer_callback
    @ffi.def_extern()

KeyboardInterrupt:

GLFN
yfinance.Ticker object <MCK> balancesheet failed to load

Exception ignored from cffi callback <function buffer_callback at 0x7b09a3bd4c20>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/curl_cffi/curl.py", line 68, in buffer_callback
    @ffi.def_extern()

KeyboardInterrupt:

yfinance.Ticker object <MCK> cashflow failed to load

 MCK
 Successful: 7
       ['analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est']
 Failed: 3
       ['balancesheet', 'cashflow', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

🔹 0.6655652581960002 🔹 0.7367560462344941 🔹

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

yfinance.Ticker object <MCRAA> balancesheet failed to load
yfinance.Ticker object <MCRAA> cashflow failed to load
yfinance.Ticker object <MCRAA> incomestmt failed to load
yfinance.Ticker object <MCRAA> earnings history failed to load

 MCRAA
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

🔹 0.4798729026779899 🔹 0.24919396082007148 🔹
yfinance.Ticker object <MCRAB> balancesheet failed to load
yfinance.Ticker object <MCRAB> cashflow failed to load
yfinance.Ticker object <MCRAB> incomestmt failed to load
yfinance.Ticker object <MCRAB> earnings history failed to load

 MCRAB
 Successful: 3
       ['analyst_target_eps', 'earnings_est', 'rev_est']
 Failed: 7
       ['balancesheet', 'cashflow', 'incomestmt', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'meta']

Error occurred with balancesheet: at least one array or dtype is required
Error occurred with cashflow: at least one array or dtype is required

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

Error occurred with incomestmt: at least one array or dtype is required
Error occurred with earnings_hist: at least one array or dtype is required
Error occurred with earnings_hist_est: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with earnings_hist_est_eps: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- epsActual_1
- epsActual_2
- epsActual_3
- epsActual_4
- epsDifference_1
- ...

Error occurred with meta: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Common Stock Equity_1
- Common Stock Equity_2
- Common Stock Equity_3
- Common Stock Equity_4
- Common Stock Equity_5
- ...

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

🔹 0.48081440835603495 🔹 0.3230059901565094 🔹
             0       1         2           3         4           5  \
      0.528077    0.51  0.119555 -100.000000  0.119203 -100.000000
      0.625699    0.93  0.119555 -100.000000  0.119203 -100.000000
      0.775064    0.50  0.861756 -100.000000  0.880797    0.268696
      0.347257    0.55  0.615668    0.687325  0.119203    0.095745
      0.248270    0.53  0.119555    0.176493  0.119203 -100.000000
..         ...     ...       ...         ...       ...         ...
      0.894095    0.31  0.119555    0.150421  0.119203 -100.000000
      0.607414    0.43  0.092968 -100.000000  0.119203    0.835533
   -100.000000 -100.00  0.671120    0.447968  0.880797    0.780457
   -100.000000 -100.00  0.362200 -100.000000  0.119203 -100.000000
   -100.000000 -100.00  0.372442 -100.000000  0.119203 -100.000000

             6       7         8           9
   -100.000000 -100.00  0.860245 -100.000000
   -100.000000 -100.00  0.860245 -100.000000
      0.230191    0.27  0.609268    0.880797
      0.125040    0.36  0.185812    0.119203
   -100.000000 -100.00  0.860245 -100.000000
..         ...     ...       ...         ...
   -100.000000 -100.00  0.860245 -100.000000
      0.716703    0.59  0.691408    0.119203
      0.934128    0.60  0.821922 -100.000000
   -100.000000 -100.00  0.860245 -100.000000
   -100.000000 -100.00  0.860245 -100.000000

[115 rows x 10 columns]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

In [ ]:
for i in range(len(l)):
  x = est_date(l[i])
  print(x)

2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30
2025-09-30

In [ ]:
est_date("aapl")

'2025-09-30'

In [ ]:
df = pd.DataFrame({"":predictions})
df.shape

(238, 1)

In [ ]:
df.to_csv('Final Estimator Predictions Test.csv', index=False)

In [ ]:
X[""].corr(y[""])

np.float64(0.17142024712767748)

In [ ]:
df = pd.DataFrame({"":label})
df.to_csv("Labels for final estimator.csv")

In [ ]:
print((X[""]==1).sum().sum())

9

In [ ]:
K = pd.DataFrame({"pred":predictions, "label":label})
K.to_csv("RESULTS FROM FUNDEMENTAL MODEL(UNCHECKED, SUPER POSITIVE).csv")

In [ ]:
K["pred"].corr(K["label"])

np.float64(0.9444371145462145)

In [ ]:
#THE ORIGINAL ONE DONT EDIT THIS, ALL OF THESE STOCKS HAVE LABELS!
stocks = ['LAZ', 'LZB', 'GORV', 'LCII', 'LCNB', 'LRE', 'LEMIF', 'LBUY', 'LFLY', 'LPTX', 'LCCN', 'LEA', 'LTRE', 'LEAT', 'LDTC', 'LFGP', 'LMPMY', 'LEE', 'LEEEF', 'LPPI', 'LTESF', 'LEGIF', 'LGCY', 'LEGH', 'LGGNF', 'LGGNY', 'LZ', 'LEGT', 'LEGN', 'LPSIF', 'LGBS', 'LEG', 'LEBGF', 'LGRDY', 'LEHKQ', 'LEHLQ', 'LHHMQ', 'LEHNQ', 'LSE', 'LEJUY', 'LNTO', 'LMAT', 'LMND', 'LC', 'TREE', 'LDWY', 'LNVGF', 'LNVGY', 'LNSR', 'LASLY', 'LENZ', 'LNZNF', 'LLLAF', 'LECRF', 'DRS', 'FINMF', 'FINMY', 'LEFUF', 'LEEN', 'LYSFY', 'LSAK', 'LESL', 'AIUG', 'LEVI', 'LVXFF', 'LWCL', 'LEXX', 'LXEO', 'LXRX', 'LX', 'LIFD', 'LPL', 'LGIH', 'LGL', 'LI', 'LBGJ', 'LNNGY', 'LIANY', 'LBRDA', 'LBRDB', 'LBRDK', 'LBRDP', 'LDDFF', 'LBYE', 'LBRT', 'LBTYA', 'LBTYB', 'LBTYK', 'LGDTF', 'LILA', 'LILAK', 'FWONA', 'LLYVA', 'FWONB', 'LLYVB', 'FWONK', 'LLYVK', 'LBNW', 'LBSR', 'LICN', 'LICT', 'LICYQ', 'LFCBY', 'LFABF', 'LTGHY', 'LINS', 'LTH', 'LIF', 'LFCR', 'LFSWF', 'LLBO', 'LCTC', 'LFMD', 'LFMDP', 'LQWC', 'LTCP', 'LFST', 'LCUT', 'LFVN', 'LFWD', 'LWAY', 'LZM', 'LIFFF', 'LIGA', 'LGND', 'LGNZZ', 'LNW', 'OHCFF', 'LGSXY', 'LTBR', 'LHGI', 'LITB', 'ZEVY', 'LPTH', 'KORE', 'KOREF', 'KEP', 'KFY', 'KRNT', 'KRRO', 'KRMD', 'KRYXF', 'KSRYY', 'KOS', 'KOSS', 'KPTSF', 'KROEF', 'KHC', 'KBLB', 'UUSAF', 'KRKNF', 'KTOS', 'DNUT', 'JPX', 'KRNTY', 'KRYAY', 'KRYPF', 'KRYPY', 'KKOYY', 'KSSRF', 'KSTBF', 'KG', 'KDP', 'KEQU', 'KEWL', 'KTCC', 'KYCCF', 'KEYUF', 'KEYS', 'KZR', 'KFRC', 'KGHPF', 'KOGMF', 'KHDHF', 'KHRNF', 'KDOZF', 'JYNT', 'JBFCF', 'JBFCY', 'JLL', 'JSDA', 'JSHG', 'JRNGF', 'DERM', 'JWEL', 'JOYY', 'JPEX', 'JRJRQ', 'JRSS', 'JFWV', 'JTCPF', 'JTNB', 'JFIL', 'JUBPF', 'JSCIF', 'JUGRF', 'JBAXY', 'JBARF', 'JUMT', 'JMIA', 'JGHAF', 'JUVF', 'JPPYY', 'JMXXF', 'JUNS', 'JUSHF', 'TKAYF', 'JTKWY', 'JUTOY', 'JUVAF', 'JVTSF', 'JVSAU', 'JVSA', 'JXG', 'JZRIF', 'KPLUF', 'KPLUY', 'KTGDF', 'WDFCF', 'KNTNF', 'KANP', 'KAI', 'KNNNF', 'KAIFF', 'JPHLF', 'KATX', 'IPT', 'KMPB', 'KMT', 'KW', 'KEN', 'KLDCF', 'KFFB', 'KPELF', 'KPELY', 'KPLIF', 'KREVF', 'PPRUF', 'PPRUY', 'KMDRF', 'KARNF', 'KROS', 'ITOS', 'ITRM', 'ITEX', 'ITMPF', 'ITOCF', 'ITOCY', 'IKTO', 'ITNS', 'ITRI', 'ITRO', 'ITT', 'ITRN', 'ITVPY', 'IE', 'IVPAF', 'IVCGF', 'IVDA', 'IWAL', 'IXAQF', 'IZEA', 'IZNN', 'IZOZF', 'JSNSF', 'JSAIY', 'JJSF', 'BWEL', 'JILL', 'JAGL', 'JACK', 'JPOTF', 'JKSM', 'JXN', 'JACO', 'JADA', 'JBIO', 'MCKRF', 'TNSTF', 'JDSEF', 'JAGX', 'JAGGF', 'JAKK', 'JHX', 'JRVR', 'JAMF', 'JWLLF', 'JAMN', 'JANL', 'GDYMF', 'JHG', 'JBI', 'JANX', 'JPNRF', 'JAPSY', 'JNNDF', 'OSCUF', 'JPXGY', 'JFTH', 'JGLDF', 'JPTXF', 'JPSTF', 'JPPHY', 'JPSWY', 'JAPAF', 'JAPAY', 'JCYGY', 'JARLF', 'JMHLY', 'JSPR', 'JWSUF', 'JWSMF', 'JWSWF', 'JDNRF', 'JYD', 'JAZZ', 'JBZY', 'JBDI', 'JBGS', 'JBTC', 'JBTM', 'JCDXY', 'JCRRF', 'JDVB', 'JDDSF', 'JDSPY', 'JDCMF', 'JD', 'JDEPY', 'JCSE', 'JEF', 'JFBC', 'JFBR', 'JELD', 'JNPKF', 'JRSH', 'JROOF', 'JRONY', 'JTAI', 'DRTGF', 'JTBK', 'JBLU', 'JCTC', 'JFEEF', 'FROG', 'JGSMY', 'JGCCY', 'JDZG', 'JELCF', 'JMPLF', 'JMPLY', 'JOUT', 'INCR', 'IDCC', 'TILE', 'IFSPF', 'INTG', 'LINK', 'ITMSF', 'ICGUF', 'IBOC', 'IBATF', 'BABWF', 'ICAGY', 'INCC', 'ICTEF', 'ILDO', 'IDIG', 'IDVV', 'IFRTF', 'IGT', 'IGIC', 'INIS', 'ILAL', 'ILHMF', 'IMAQ', 'IMXI', 'INPAP', 'IPCFF', 'IPWG', 'URANF', 'INSW', 'ILST', 'ISCO', 'THM', 'IWGFF', 'IIJIY', 'IDXG', 'IPAR', 'ITRX', 'IIPZF', 'IRCKF', 'IKTSF', 'IKTSY', 'IITSF', 'ISNPY', 'INTT', 'ITOR', 'INXSF', 'IMTCF', 'IPI', 'INJJQ', 'ITJTQ', 'INTZ', 'LUNR', 'INUV', 'IVF', 'IVR', 'MHIVF', 'ISTR', 'IVCBF', 'IVTJF', 'IVSXF', 'IVSBF', 'ITIC', 'INVU', 'INVUP', 'IVCTF', 'IESVF', 'IVRO', 'IVVD', 'IRMD', 'IRTC', 'IRIX', 'IRDM', 'RSHPF', 'IRME', 'IRBT', 'IROH', 'IRWD', 'IRS', 'IRVRF', 'ISBA', 'ISOU', 'ISON', 'ISPC', 'ISPR', 'ISCNF', 'ISRL', 'ISRLU', 'ISDAY', 'ISUNQ', 'ISUZF', 'ISUZY', 'ITP', 'MBCF', 'ITGGF', 'IFBC', 'ITUB', 'INLB', 'IDEXY', 'IDCBF', 'IDCBY', 'ILPT', 'IPOAF', 'INEOF', 'IFCNF', 'IFNNF', 'IFNNY', 'CDTAF', 'INFT', 'INFIQ', 'IFRX', 'AUCUF', 'IFBD', 'IFJPY', 'INFA', 'IRMTF', 'III', 'INFY', 'IFSUF', 'IFXY', 'INFU', 'INGVF', 'ING', 'INGEF', 'NGVT', 'IMKTA', 'INGM', 'INGR', 'IKT', 'INTI', 'INBX', 'INRE', 'INM', 'INMD', 'INMB', 'IPHYF', 'IPHA', 'INEO', 'INGXF', 'INND', 'INHD', 'INNPF', 'INOD', 'IOSP', 'MPEG', 'INNV', 'IVBT', 'IVDN', 'LUCY', 'LUCYW', 'IVFH', 'IHAI', 'IIPR', 'IMTH', 'IPSI', 'ISSC', 'IVBXF', 'IVRN', 'INVX', 'INVA', 'INVZ', 'INV', 'INGN', 'NOTV', 'IVREF', 'INO', 'INZY', 'IPXHF', 'IPXHY', 'IPOOF', 'INPOY', 'IBTN', 'INSG', 'NSIT', 'INSM', 'NSP', 'IINN', 'ISPO', 'ISPOW', 'INSP', 'INSSF', 'IVP', 'INSE', 'NSPR', 'IBP', 'IIIN', 'TIL', 'MRES', 'IAUGY', 'IFCZF', 'INTA', 'ICG', 'ITGR', 'IART', 'ITRG', 'INTE', 'IAS', 'ITGLF', 'INBP', 'IGPK', 'IGCRF', 'IMTE', 'IRRX', 'INTV', 'WELNF', 'INTC', 'KASHF', 'NTLA', 'IDN', 'INBS', 'INTJ', 'ILAG', 'IPM', 'INLX', 'INTS', 'INTR', 'IHGP', 'IBKR', 'TRNR', 'ITVI', 'IESFY', 'ICHGF', 'IHG', 'IFS', 'IBDSF', 'IBDRY', 'IBEX', 'IBIDF', 'IBIO', 'IBXS', 'IBTA', 'IBWC', 'ICABY', 'ICAD', 'IEP', 'ICCM', 'ICFI', 'ICHR', 'IBN', 'ICL', 'ICON', 'ICNM', 'ICLR', 'ICNB', 'ICMFF', 'ICCT', 'ICTSF', 'ICUI', 'IZM', 'IDA', 'COPR', 'IDR', 'IDGR', 'IPWR', 'IDEXQ', 'IDYA', 'IDKOF', 'IDKOY', 'IDTA', 'INVE', 'IEX', 'IDGC', 'IDT', 'IDWM', 'IEHC', 'IESC', 'IROQ', 'IFAN', 'IFMK', 'IGGHY', 'IGPTF', 'IGC', 'IGEN', 'IGGGF', 'IGMS', 'IGIFF', 'IPGDF', 'IIDDY', 'IHRT', 'IHICY', 'IHS', 'IH', 'ITOX', 'IJJP', 'IKNA', 'ILIM', 'ILIKF', 'ILLMF', 'ILMN', 'ILKAF', 'ILKAY', 'ILUS', 'IMCC', 'IMAB', 'BACK', 'IFLXF', 'IMTL', 'IAGX', 'IWSY', 'ARXRF', 'IPNFF', 'IMXCF', 'IMAX', 'IMCDY', 'IMRFF', 'IMIAF', 'IMIUY', 'IMTX', 'IMMR', 'IMMX', 'ICCC', 'IMRX', 'IMUX', 'IBRX', 'IMNM', 'IPA', 'IMVT', 'IMRN', 'IHLDF', 'IMPM', 'IBO', 'IFUS', 'ISVLF', 'IMPUF', 'IMPUY', 'IPXAF', 'IMBBF', 'IMBBY', 'IPMLF', 'IMO', 'IMPP', 'IMPPP', 'IPRC', 'IPGGF', 'PI', 'IUGNF', 'IMNN', 'IMVIF', 'INOH', 'IVME', 'INAB', 'INBC', 'IXHL', 'IGTA', 'IOR', 'INDP', 'IEGCF', 'IRT', 'INDB', 'IBCP', 'IFLM', 'INDI', 'INDV', 'IGEX', 'ITAYY', 'IDCN', 'PIFMY', 'INDO', 'INQD', 'PTITF', 'ISMAF', 'ISMAY', 'IDEXF', 'HTLM', 'HMST', 'HWIN', 'HTB', 'HNHPF', 'HONT', 'HNDAF', 'HMC', 'HNST', 'HBEIF', 'HOKCY', 'HKSHF', 'HKXCF', 'HKXCY', 'HKTVY', 'HGYN', 'HCIL', 'HKHGF', 'HNGKY', 'HLP', 'HOFT', 'HOOK', 'HOPE', 'HPNN', 'HPTO', 'HMN', 'HBNC', 'HNCUF', 'HGPI', 'HKHC', 'HZNFF', 'HSPOU', 'HSPO', 'HSPTU', 'HRZN', 'HTFB', 'HTFC', 'HRL', 'HHLKF', 'HOTH', 'HLI', 'HOUR', 'HUSA', 'HOV', 'HOVNP', 'HHH', 'HWDJF', 'HOCPF', 'HOCPY', 'HPIL', 'KICK', 'HPQFF', 'HQGE', 'HBCYF', 'HSBC', 'HSTC', 'HTGMQ', 'HUDI', 'HHEGF', 'HUNGF', 'HUBC', 'HUBG', 'HUBS', 'HBM', 'HSON', 'HPP', 'HDSN', 'HUGPF', 'BOSSY', 'HGTXU', 'HUHU', 'HUMT', 'HMBL', 'HUML', 'HBANM', 'HBANP', 'HBANL', 'HUN', 'BBBMF', 'HURC', 'HURN', 'HSQVY', 'HUT', 'HUPHY', 'HUTCY', 'HCM', 'HUYA', 'HWGG', 'HWH', 'H', 'HPSIF', 'HYMC', 'HYMCL', 'HYDTF', 'HRNNF', 'PYBX', 'HYFM', 'HYEG', 'HUIPF', 'HGRAF', 'HYLN']
len(stocks)

816

In [ ]:
stocks = ["H"]

In [ ]:
#SECOND BATCH OF STOCKS, CAN BE CHANGED ['LAZ', 'LZB', 'LCII', 'LCNB', 'LEMIF', 'LBUY', 'LFLY', 'LPTX', 'LEA', 'LEAT', 'LEE', 'LEEEF', 'LEGIF', 'LGCY', 'LEGH', 'LZ', 'LEGT', 'LEGN', 'LPSIF', 'LEG', 'LEBGF', 'LGRDY', 'LDOS', 'LMAT', 'LMND', 'LC', 'TREE', 'LEN', 'LII', 'LNSR', 'LENZ', 'LNZNF', 'LECRF', 'DRS', 'LEFUF', 'LYSFY', 'LESL', 'LEVI', 'LVXFF', 'LEXX', 'LXEO', 'LXRX', 'LIFD', 'LGIH', 'LGL', 'LI', 'LBRDA', 'LBRDB', 'LBRDK', 'LBRDP', 'LDDFF', 'LBRT', 'LBTYA', 'LBTYB', 'LBTYK', 'LGDTF', 'LILA', 'LILAK', 'FWONA', 'LLYVA', 'FWONB', 'LLYVB', 'FWONK', 'LLYVK', 'LBSR', 'LFCBY', 'LFABF', 'LTH', 'LIF', 'LFCR', 'LFSWF', 'LCTC', 'LFMD', 'LFMDP', 'LFST', 'LCUT', 'LFVN', 'LFWD', 'LWAY', 'LIFFF', 'LGND', 'LNW', 'OHCFF', 'LGSXY', 'LTBR', 'LPTH', 'KORE', 'KEP', 'KFY', 'KRNT', 'KRRO', 'KRMD', 'KRYXF', 'KOS', 'KPTSF', 'KHC', 'KBLB', 'UUSAF', 'KRKNF', 'KTOS', 'DNUT', 'KR', 'KRNTY', 'KKOYY', 'KSSRF', 'KSTBF', 'KDP', 'KTCC', 'KEY', 'KEYUF', 'KEYS', 'KZR', 'KFRC', 'KGHPF', 'KOGMF', 'KDOZF', 'JYNT', 'JBFCF', 'JBFCY', 'JLL', 'JRNGF', 'DERM', 'JPM', 'JFIL', 'JUGRF', 'JMIA', 'JUVF', 'JNPR', 'JUNS', 'JUSHF', 'JVSAU', 'JVSA', 'JZRIF', 'KPLUF', 'KPLUY', 'KTGDF', 'WDFCF', 'KNTNF', 'KANP', 'KAI', 'KATX', 'KMT', 'KW', 'KLDCF', 'KFFB', 'KVUE', 'KMDRF', 'KARNF', 'KROS', 'ITOS', 'ITRM', 'ITRI', 'ITT', 'ITRN', 'IE', 'IVPAF', 'IVCGF', 'IWAL', 'IXAQF', 'IZEA', 'IZOZF', 'JJSF', 'JBHT', 'JILL', 'SJM', 'JKHY', 'JXN', 'J', 'MCKRF', 'TNSTF', 'JAGX', 'JAGGF', 'JAKK', 'JHX', 'JRVR', 'JAMF', 'JWLLF', 'JHG', 'JBI', 'JANX', 'JGLDF', 'JSPR', 'JDNRF', 'JAZZ', 'JBGS', 'JBTM', 'JDCMF', 'JD', 'JEF', 'JELD', 'JNPKF', 'JRSH', 'JROOF', 'JRONY', 'JTAI', 'JBLU', 'FROG', 'JGSMY', 'JBL', 'JCI', 'JOUT', 'IDCC', 'TILE', 'IFSPF', 'ITMSF', 'IBATF', 'IBM', 'ICTEF', 'IFF', 'IFRTF', 'IGT', 'IMAQ', 'IMXI', 'IP', 'INPAP', 'IPCFF', 'URANF', 'INSW', 'THM', 'IIJIY', 'IPAR', 'IPG', 'IIPZF', 'IRCKF', 'INTT', 'ITOR', 'INXSF', 'IMTCF', 'IPI', 'INJJQ', 'ITJTQ', 'INTZ', 'INTU', 'LUNR', 'ISRG', 'INUV', 'IVF', 'IVZ', 'IVR', 'MHIVF', 'ISTR', 'IVSXF', 'IVSBF', 'INVU', 'INVUP', 'INVH', 'IVVD', 'IRMD', 'IRTC', 'IRDM', 'IRME', 'IRBT', 'IROH', 'IRM', 'IRWD', 'IRS', 'IRVRF', 'ISBA', 'ISOU', 'ISPC', 'ISPR', 'ISRL', 'ISRLU', 'ISDAY', 'MBCF', 'ITUB', 'IDCBF', 'IDCBY', 'ILPT', 'IPOAF', 'INEOF', 'IFNNF', 'IFNNY', 'CDTAF', 'IFRX', 'AUCUF', 'INFA', 'IRMTF', 'III', 'IFSUF', 'INFU', 'IR', 'NGVT', 'INGM', 'INGR', 'IKT', 'INTI', 'INBX', 'INRE', 'INM', 'INMD', 'INMB', 'INGXF', 'INHD', 'INNPF', 'INOD', 'IOSP', 'INNV', 'IVDN', 'LUCY', 'LUCYW', 'IVFH', 'IIPR', 'IMTH', 'IPSI', 'ISSC', 'INVA', 'INVZ', 'INV', 'INGN', 'NOTV', 'IVREF', 'INO', 'INZY', 'IPOOF', 'INPOY', 'INSG', 'NSIT', 'INSM', 'NSP', 'ISPO', 'ISPOW', 'INSP', 'IVP', 'INSE', 'NSPR', 'IBP', 'IIIN', 'TIL', 'PODD', 'IFCZF', 'INTA', 'ITGR', 'IART', 'ITRG', 'IAS', 'INBP', 'IGCRF', 'IRRX', 'INTV', 'WELNF', 'INTC', 'KASHF', 'NTLA', 'IDN', 'INBS', 'IPM', 'INLX', 'INTS', 'INTR', 'IBKR', 'ICE', 'IFS', 'IBEX', 'IBIO', 'IBTA', 'ICAD', 'IEP', 'ICCM', 'ICFI', 'ICHR', 'ICL', 'ICON', 'ICLR', 'ICMFF', 'ICCT', 'ICUI', 'IDA', 'COPR', 'IDR', 'IPWR', 'IDYA', 'IDTA', 'INVE', 'IEX', 'IDXX', 'IDT', 'IEHC', 'IESC', 'IROQ', 'IGC', 'IGMS', 'IGIFF', 'IHRT', 'IHS', 'ITOX', 'IKNA', 'ITW', 'ILLMF', 'ILMN', 'IMCC', 'IFLXF', 'ARXRF', 'IPNFF', 'IMAX', 'IMRFF', 'IMTX', 'IMMX', 'IMRX', 'IMUX', 'IBRX', 'IMNM', 'IPA', 'IMVT', 'IHLDF', 'IBO', 'ISVLF', 'IPMLF', 'IMO', 'IMPP', 'IMPPP', 'PI', 'IMNN', 'INAB', 'IXHL', 'IGTA', 'IOR', 'INCY', 'INDP', 'IEGCF', 'IRT', 'INDB', 'IBCP', 'INDI', 'INDV', 'ITAYY', 'PIFMY', 'PTITF', 'ISMAF', 'ISMAY', 'HMST', 'HTB', 'HNHPF', 'HNDAF', 'HMC', 'HNST', 'HBEIF', 'HON', 'HGYN', 'HCIL', 'HOFT', 'HOPE', 'HMN', 'HBNC', 'HNCUF', 'HKHC', 'HSPOU', 'HSPO', 'HRZN', 'HRL', 'HST', 'HOTH', 'HLI', 'HOV', 'HOVNP', 'HHH', 'HWM', 'HPQ', 'HPQFF', 'HUNGF', 'HUBG', 'HUBB', 'HUBS', 'HBM', 'HSON', 'HPP', 'HDSN', 'HUGPF', 'BOSSY', 'HMBL', 'HBAN', 'HBANM', 'HBANP', 'HBANL', 'HII', 'HUN', 'BBBMF', 'HURN', 'HSQVY', 'HUT', 'HWH', 'H', 'HPSIF', 'HYMC', 'HYMCL', 'HYDTF', 'HRNNF', 'HYFM', 'HGRAF', 'HYLN', 'HUM']
print(stocks)

['LAZ', 'LZB', 'LCNB', 'LFLY', 'LPTX', 'LEA', 'LEGH', 'LZ', 'LEGN', 'LEG', 'LGRDY', 'LDOS', 'LMAT', 'LMND', 'LC', 'TREE', 'LEN', 'LII', 'LNSR', 'LESL', 'LEVI', 'LEXX', 'LXEO', 'LXRX', 'LGIH', 'LGL', 'LI', 'LBRT', 'LBTYA', 'LILA', 'LILAK', 'FWONA', 'FWONK', 'LTH', 'LIF', 'LFMD', 'LCUT', 'LFWD', 'LWAY', 'LGND', 'LNW', 'KRNT', 'KRMD', 'KOS', 'KHC', 'KTOS', 'KR', 'KDP', 'KEY', 'KEYS', 'KFRC', 'JYNT', 'JLL', 'DERM', 'JPM', 'JNPR', 'JUSHF', 'KAI', 'KW', 'KVUE', 'KROS', 'ITOS', 'ITRM', 'ITT', 'ITRN', 'IVPAF', 'IZEA', 'JJSF', 'JBHT', 'JILL', 'SJM', 'JXN', 'J', 'JAGX', 'JAGGF', 'JAKK', 'JRVR', 'JAMF', 'JHG', 'JBI', 'JANX', 'JSPR', 'JAZZ', 'JBTM', 'JD', 'JEF', 'JELD', 'JRSH', 'JRONY', 'JBLU', 'FROG', 'JBL', 'JCI', 'IBM', 'IFF', 'IGT', 'IMXI', 'IP', 'INSW', 'IPAR', 'INTT', 'IPI', 'INTZ', 'LUNR', 'ISRG', 'INUV', 'IVZ', 'IVR', 'ISTR', 'IRMD', 'IRDM', 'IRME', 'IRM', 'IRWD', 'ISBA', 'ISPC', 'ITUB', 'INFA', 'INFU', 'IR', 'NGVT', 'INGR', 'IKT', 'INMD', 'INMB', 'INOD', 'IOSP', 'LUCY', 'IIPR', 'INVA', 'INVZ', 'NOTV', 'INO', 'INZY', 'IPOOF', 'INSG', 'NSIT', 'INSM', 'NSP', 'INSE', 'NSPR', 'TIL', 'PODD', 'ITGR', 'ITRG', 'IAS', 'INTC', 'IDN', 'IPM', 'INLX', 'INTS', 'INTR', 'IBKR', 'IFS', 'ICAD', 'IEP', 'ICCM', 'ICFI', 'ICL', 'ICLR', 'ICUI', 'IDA', 'IDR', 'IDYA', 'INVE', 'IDXX', 'IGC', 'IGMS', 'IHRT', 'IKNA', 'ILLMF', 'ILMN', 'IMCC', 'IMAX', 'IMTX', 'IMMX', 'IMRX', 'IBRX', 'IMNM', 'IMVT', 'IMO', 'IMNN', 'INAB', 'INDP', 'INDB', 'IBCP', 'INDI', 'INDV', 'HMST', 'HNST', 'HON', 'HOPE', 'HMN', 'HBNC', 'HRZN', 'HRL', 'HST', 'HOTH', 'HLI', 'HHH', 'HWM', 'HPQ', 'HUBG', 'HUBB', 'HBM', 'HSON', 'HPP', 'HDSN', 'HBAN', 'HII', 'HUN', 'HURN', 'H', 'HYMC', 'HYFM', 'HYLN', 'HUM']

In [ ]:
#X = pd.DataFrame({"":predictions})
y = pd.DataFrame({"":label})


cr = classification_report(X,y)
print(cr)

cm = confusion_matrix(X,y)
print(cm)

              precision    recall  f1-score   support

           0       0.86      0.50      0.63       616
           1       0.22      0.64      0.33       136

    accuracy                           0.52       752
   macro avg       0.54      0.57      0.48       752
weighted avg       0.75      0.52      0.58       752

[[306 310]
 [ 49  87]]

In [ ]:
X = pd.read_excel("/content/asdf-1.xlsx")
X = X.iloc[:,1]

In [ ]:
df = pd.DataFrame({"y":label})
df.shape

(966, 1)

In [ ]:
for i in error:
  p = stocks.index(i)
  print(p)

115
141
210
399

In [ ]:
df.to_excel("predictions_labels.xlsx")

In [ ]:
X.to_excel("asdf.xlsx")

In [ ]:
df = pd.read_csv("/content/Unseen_Data_Balanced_Answer.csv")
stock_list = df["stock"].tolist()
print(stock_list)
len(stock_list)

['JYNT', 'HST', 'LBGJ', 'LICN', 'INPAP', 'LXRX', 'HONT', 'KMPB', 'IESVF', 'LRE', 'IFJPY', 'IDCC', 'INFA', 'IVREF', 'KORE', 'IFSPF', 'IDTA', 'KICK', 'HPSIF', 'LSE', 'IDR', 'JBFCF', 'TNSTF', 'HHLKF', 'JNPR', 'LCTC', 'INEOF', 'INDB', 'HWH', 'JFBR', 'LDDFF', 'LEGH', 'KMT', 'LFLY', 'INBC', 'HNST', 'LFGP', 'INLX', 'IDGR', 'IJJP', 'LBYE', 'KNTNF', 'LQWC', 'KSSRF', 'HOKCY', 'JBTM', 'PODD', 'INVZ', 'LBTYA', 'JUGRF', 'IRTC', 'HUBG', 'HUT', 'HSQVY', 'LEGIF', 'HUBS', 'IDGC', 'OSCUF', 'JXN', 'ILPT', 'INFU', 'HOCPY', 'IWAL', 'INVU', 'IPXHY', 'LHHMQ', 'LEE', 'LEHLQ', 'HYDTF', 'JUVAF', 'LIFD', 'ICLR', 'INTZ', 'LBRDP', 'IGPK', 'IDEXQ', 'INGN', 'IDN', 'HRL', 'III', 'INJJQ', 'IFRX', 'LUCYW', 'LZ', 'ICCM', 'KARNF', 'IBP', 'LFABF', 'IFF', 'LTH', 'KG', 'JHG', 'IPCFF', 'HDSN', 'IBDRY', 'IVSBF', 'IHS', 'WDFCF', 'LEXX', 'LIFFF', 'ITW', 'IFBC', 'ITGLF', 'ILKAY', 'DRS', 'JDSPY', 'HNGKY', 'IMVT', 'IHLDF', 'JPEX', 'INXSF', 'INTI', 'IDCBY', 'HUHU', 'HSON', 'JDSEF', 'ILMN', 'IDEXF', 'ICFI', 'HKXCF', 'ICTEF', 'JACK', 'JAZZ', 'ICGUF', 'TREE', 'KAIFF', 'IBTN', 'IGIC', 'INTJ', 'HKHGF', 'IGEX', 'INFY', 'JAPAF', 'WELNF', 'LBSR', 'LBRDB', 'INMB', 'ILHMF', 'HWM', 'LGGNF', 'ISUZF', 'JFTH', 'IPNFF', 'LLBO', 'FINMY', 'HZNFF', 'JROOF', 'SJM', 'HGYN', 'HRNNF', 'IVVD', 'INAB', 'JBGS', 'IPXAF', 'HPNN', 'ITJTQ', 'LGSXY', 'HUBB', 'ISRG', 'ISCNF', 'JCDXY', 'INM', 'JUVF', 'KEYUF', 'KBLB', 'IART', 'KRYPF', 'IGTA', 'KPTSF', 'PPRUF', 'IEX', 'JPTXF', 'MBCF', 'LLYVA', 'IFUS', 'INUV', 'HUBC', 'IKNA', 'HUIPF', 'ISPOW', 'KHRNF', 'INQD', 'IVME', 'HBANM', 'ITVI', 'JFWV', 'IPGDF', 'LBTYB', 'INOH', 'JGHAF', 'IPHA', 'HOV', 'IVR', 'ISPC', 'IMTE', 'HKTVY', 'INDI', 'JANX', 'ILIKF', 'ISNPY', 'LLYVB', 'LWAY', 'ITOX', 'JAPSY', 'JVSAU', 'HBCYF', 'HUNGF', 'HMN', 'IPM', 'ISRL', 'LGIH', 'HHH', 'ICMFF', 'IMCC', 'IBN', 'JJSF', 'LII', 'JNNDF', 'IKT', 'HSPOU', 'HUM', 'IINN', 'INBX', 'JSAIY', 'JMXXF', 'IFLM', 'KSRYY', 'IMMX', 'LYSFY', 'JRNGF', 'HNHPF', 'INVH', 'NSIT', 'IMRN', 'IPGGF', 'INSG', 'LMPMY', 'IMTX', 'INTC', 'IVZ', 'INBS', 'HSPTU', 'HUPHY', 'JKSM', 'ING', 'IRWD', 'LITB', 'ITRM', 'HBNC', 'FROG', 'IFRTF', 'HPIL', 'BOSSY', 'IBO', 'JBDI', 'JDDSF', 'INTS', 'JYD', 'KEWL', 'IPAR', 'INV', 'FWONB', 'HUGPF', 'KRYXF', 'NTLA', 'LHGI', 'LLLAF', 'IHAI', 'HLI', 'JBFCY', 'LEEEF', 'INSSF', 'LEGN', 'IOR', 'JKHY', 'IVRO', 'KTOS', 'LXEO', 'IGGGF', 'JD', 'IVF', 'KTCC', 'DRTGF', 'AUCUF', 'IDXX', 'IMPP', 'IXHL', 'IZNN', 'IVTJF', 'PI', 'JPPHY', 'IMMR', 'IBM', 'JCRRF', 'KDP', 'JSHG', 'LEBGF', 'LUNR', 'HLP', 'LESL', 'IZM', 'JAGGF', 'HUMT', 'LBNW', 'IMXI', 'J', 'ICUI', 'KRMD', 'IVP', 'INFT', 'IMIUY', 'HNCUF', 'ISVLF', 'IROQ', 'KRYPY', 'HON', 'IMTH', 'JVSA', 'LLYVK', 'TKAYF', 'LNTO', 'IMTCF', 'IMPUF', 'H', 'HOTH', 'JCI', 'IDIG', 'IGGHY', 'IIDDY', 'HRZN', 'INTA', 'JCYGY', 'HOVNP', 'INTU', 'IKTSF', 'HWDJF', 'LAZ', 'IDKOF', 'KZR', 'LNNGY', 'NOTV', 'KRRO', 'HWIN', 'KPLUY', 'LPTH', 'JNPKF', 'NGVT', 'INNV', 'IAS', 'IBRX', 'IPOAF', 'IFBD', 'KNNNF', 'IZEA', 'JWSWF', 'INGXF', 'INTT', 'IPWR', 'IFLXF', 'LEFUF', 'IBXS', 'IXAQF', 'JVTSF', 'JDCMF', 'LPPI', 'JBTC', 'ICON', 'IHGP', 'HSPO', 'IPWG', 'IDYA', 'KRNTY', 'HURN', 'IAUGY', 'LFST', 'HKSHF', 'INMD', 'HPQ', 'HQGE', 'HMC', 'ISMAY', 'JEF', 'LCUT', 'JBL', 'INVE', 'ISOU', 'HYFM', 'JBHT', 'JOUT', 'OHCFF', 'JMPLY', 'NSP', 'BABWF', 'ITRI', 'ISRLU', 'IR', 'ICABY', 'ARXRF', 'JBIO', 'LEA', 'INND', 'INZY', 'KSTBF', 'ITGGF', 'AIUG', 'KREVF', 'LDOS', 'LFWD', 'HPQFF', 'LEAT', 'JFEEF', 'ITMPF', 'LGCY', 'JRSS', 'LNVGY', 'LEG', 'COPR', 'JAGL', 'LEHKQ', 'IVRN', 'IDEXY', 'KHC', 'ILKAF', 'JMIA', 'IBTA', 'IGT', 'INCY', 'JPM', 'LILAK', 'KEP', 'LGRDY', 'IPG', 'KFY', 'IGPTF', 'HTFC', 'JSCIF', 'HNDAF', 'LNVGF', 'IEGCF', 'ICE', 'IUGNF', 'PPRUY', 'IBIDF', 'IRMTF', 'JBI', 'INGEF', 'JLL', 'ITOR', 'INSP', 'TIL', 'INRE', 'IGCRF', 'HUN', 'IPXHF', 'INHD', 'ITAYY', 'KPELF', 'HCIL', 'LVXFF', 'LBUY', 'IGIFF', 'KPLUF', 'HOPE', 'MHIVF', 'KOREF', 'HUDI', 'KRNT', 'LNZNF', 'IMO', 'JACO', 'LEN', 'INTR', 'IMXCF', 'IPHYF', 'IPSI', 'IMIAF', 'KGHPF', 'IDCBF', 'HYLN', 'KYCCF', 'ILST', 'ILIM', 'KFFB', 'PYBX', 'IRDM', 'ILAG', 'LEVI', 'LPTX', 'IRMD', 'LI', 'JRONY', 'LBTYK', 'HUYA', 'IMCDY', 'KPELY', 'IOSP', 'IEHC', 'LIGA', 'JMHLY', 'ISPO', 'IMAX', 'JBAXY', 'IMTL', 'IKTSY', 'IROH', 'LENZ', 'KEYS', 'IBDSF', 'IRVRF', 'IESFY', 'JBLU', 'IMRFF', 'IIPZF', 'IHICY', 'IRCKF', 'HSBC', 'LEGT', 'ITRX', 'INOD', 'IBCP', 'INGM', 'KMDRF', 'INNPF', 'HTB', 'IRME', 'HBANP', 'HMBL', 'HYMCL', 'JUTOY', 'IZOZF', 'LILA', 'IVCGF', 'LBRT', 'BBBMF', 'IRM', 'KATX', 'HBAN', 'IMAQ', 'JRVR', 'ITOS', 'ISSC', 'JFIL', 'HWGG', 'HGPI', 'HUML', 'IBEX', 'ITRO', 'PIFMY', 'ITNS', 'IP', 'KRYAY', 'JAGX', 'IKTO', 'IHG', 'ICNB', 'LFVN', 'HOCPF', 'IVFH', 'IFNNF', 'LNW', 'JUMT', 'GDYMF', 'IRRX', 'HHEGF', 'IBATF', 'INVUP', 'IVCBF', 'INO', 'KDOZF', 'LNSR', 'LICT', 'JXG', 'IEP', 'INTE', 'JGSMY', 'DNUT', 'JTAI', 'LUCY', 'UUSAF', 'IRT', 'IDCN', 'MPEG', 'ICL', 'JPNRF', 'LCNB', 'IIPR', 'IFS', 'JUSHF', 'JCSE', 'IMRX', 'TILE', 'INGR', 'IHRT', 'LWCL', 'IITSF', 'IMNN', 'HCM', 'HBANL', 'JARLF', 'JWSMF', 'JTBK', 'IVCTF', 'JBARF', 'ITVPY', 'ILLMF', 'HOFT', 'JILL', 'JPSTF', 'ICNM', 'ITGR', 'KROEF', 'LPSIF', 'IFCNF', 'JELD', 'JAMF', 'LINS', 'MCKRF', 'IMPUY', 'ISPR', 'JSPR', 'ICHR', 'KKOYY', 'HUTCY', 'HBM', 'KASHF', 'HSTC', 'INSM', 'KLDCF', 'ISDAY', 'IVBT', 'ISUZY', 'JHX', 'ITUB', 'IRBT', 'IVPAF', 'IFNNY', 'JPHLF', 'KANP', 'KHDHF', 'JBZY', 'IDKOY', 'INDP', 'JWEL', 'FWONA', 'LTCP', 'LBRDK', 'IVSXF', 'ISBA', 'JWSUF', 'JAKK', 'IBIO', 'LX', 'ITRG', 'IDVV', 'JTCPF', 'LGL', 'KAI', 'KVUE', 'LCII', 'INTV', 'ITRN', 'HPP', 'ITT', 'IPOOF', 'LGND', 'JDZG', 'LZB', 'FWONK', 'PTITF', 'IMUX', 'FINMF', 'IRS', 'ITOCY', 'ICAGY', 'LFMDP', 'HGRAF', 'ITOCF', 'LC', 'JUBPF', 'KOGMF', 'ILDO', 'JELCF', 'LGBS', 'ICTSF', 'BWEL', 'LGDTF', 'IFAN', 'LEHNQ', 'IGMS', 'JPXGY', 'IPI', 'ISTR', 'KTGDF', 'NSPR', 'LECRF', 'LFCR', 'INCC', 'IWGFF', 'LBRDA', 'KFRC', 'KW', 'KRKNF', 'IGEN', 'LCCN', 'HTLM', 'INSE', 'JRSH', 'HTFB', 'LEMIF', 'JWLLF', 'LFCBY', 'ICG', 'JDNRF', 'KPLIF', 'KOS', 'KEY', 'IPRC', 'IMNM', 'JDVB', 'IBWC', 'HKXCY', 'IBKR', 'ICAD', 'JGLDF', 'INVX', 'LZM', 'IIIN', 'INBP']

728

In [ ]:
df = pd.read_csv("/content/Final_estimator_features.csv")
y = pd.read_csv("/content/Final_Estimators_labels.csv")
df = pd.concat([df,y], axis=1)
df.shape

(1415, 13)

In [ ]:
df.to_csv("Final Estimators Training Data.csv")

In [ ]:
df = df.drop(columns=["Unnamed: 0"])
df.head()

,0,1,2,3,4,5,6,7,8,9,Unnamed: 1
0,0.043535,0.05,0.029715,0.106218,0.119203,0.607856,0.157564,0.14,0.174578,0.880797,0
1,0.710010,0.42,0.297501,0.923283,0.119203,-100.000000,-100.000000,-100.00,0.834503,-100.000000,1
2,0.866327,0.95,0.945596,0.713986,0.880797,0.502028,0.462447,0.91,0.909576,0.119203,1
3,0.897831,1.00,0.344744,0.915353,0.119203,-100.000000,-100.000000,-100.00,0.895557,-100.000000,1
4,0.897831,1.00,0.137375,0.915353,0.119203,-100.000000,-100.000000,-100.00,0.895557,-100.000000,1

In [ ]:
df = pd.read_csv("/content/Meta Test 3 (40,96).csv")
#y = df.pop("label")
#df.shape, y.shape

In [ ]:
# Separate the DataFrame into two groups based on the label
df_0 = df[df['label'] == 0]
df_1 = df[df['label'] == 1]

# Get the number of rows in the minority class
n_0 = len(df_0)
n_1 = len(df_1)

# If there are more 0s than 1s, randomly sample the 0s
if n_0 > n_1:
    df_0 = df_0.sample(n=n_1, random_state=42)

# If there are more 1s than 0s, randomly sample the 1s
elif n_1 > n_0:
    df_1 = df_1.sample(n=n_0, random_state=42)

# Concatenate the balanced DataFrame
df = pd.concat([df_0, df_1])

df = df.sample(frac=1)

In [ ]:

df.head()

     stock  label
706  HNGKY      1
5    LEMIF      1
306  JCDXY      0
98     LTH      0
565    IEP      0

In [ ]:
stocks = ['LSPD', 'LVPR', 'LWLG', 'LILMF', 'LMB', 'LVGI', 'LIMX', 'LMNR', 'LIMAF', 'LINC', 'LECO', 'LNC', 'LIND', 'LIN', 'LINIF', 'LNN', 'LNDAF', 'LCTX', 'LINE', 'LINMF', 'BOTY', 'LNMG', 'LINUF', 'PSBXP', 'PSBYP', 'PSBZP', 'LKREF', 'LGCB', 'LNKB', 'LNKS', 'LCGMF', 'LEVGQ', 'LEVWQ', 'LGHL', 'LOMLF', 'LRRIF', 'CUB', 'LION', 'LINRF', 'LIPO', 'LPCN', 'LIQT', 'YVRLF', 'LQDA', 'LQDT', 'LQMT', 'LSTA', 'LSIIF', 'LAD', 'LAC', 'LAR', 'LTMCF', 'LTUM', 'LXENF', 'IONGF', 'LTHCF', 'LOMEF', 'LITRF', 'LISMF', 'LUVSF', 'LBNKF', 'LITSD', 'LFUS', 'LIVN', 'GTREF', 'LYV', 'LOB', 'LIVE', 'LVCE', 'LVO', 'LPSN', 'RAMP', 'LVVV', 'LVWR', 'LVWD', 'LMMFF', 'LXEH', 'JSGRY', 'LIXT', 'LIXTW', 'LKQ', 'LLDTF', 'LYG', 'LMFA', 'LMPX', 'LNGNF', 'LDI', 'LOAR', 'LOBEF', 'LBLCF', 'LOBO', 'LCFY', 'LOCL', 'LOCLW', 'LOCM', 'LZRFY', 'LBAS', 'LMT', 'L', 'LOECF', 'LRFC', 'LGMK', 'LPA', 'LOGI', 'LOMA', 'LMRMF', 'LONCF', 'LDNXF', 'LNSTY', 'PPLFY', 'LNSPF', 'LGVN', 'XAGE', 'LFIN', 'LGFRY', 'LZAGF', 'LZAGY', 'LOOP', 'LPTV', 'LRLCF', 'LRLCY', 'LSANF', 'LOTE', 'LTRY', 'LTUS', 'LTSRF', 'LOT', 'LPX']

df = df_meta.iloc[0].to_frame().T
df["label"] = 0

print(df.shape)

for i in range(len(stocks)):
  try:
    successful, failed, balancesheet, cashflow, analyst_target_eps, incomestmt, earnings_est, earnings_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta = transformed_testing_data(stocks[i])
    try:
      change = (float(yf.Ticker(stocks[i]).history(start = "2025-06-01", end = "2025-06-04")["Close"].tail(1).iloc[0]) - float(yf.Ticker(stocks[i]).history(start = "2025-03-25", end = "2025-03-31")["Close"].tail(1).iloc[0]))/float(yf.Ticker(stocks[i]).history(start = "2025-03-25", end = "2025-03-31")["Close"].tail(1).iloc[0])
      print(i, stocks[i], change)
      if change > 0:
          meta["label"] = 1
      elif change == 0:
        pass
      else:
          meta["label"] = 0
      df = pd.concat([df, meta])
    except:
      print(stocks[i], " failed")
  except:
    print("🔴", stocks[i])

(1, 96)
0 LSPD 0.215621562733304
yfinance.Ticker object <LVPR> balancesheet failed to load
yfinance.Ticker object <LVPR> cashflow failed to load

ERROR:yfinance:HTTP Error 404:
ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LVPR> eps trend failed to load
yfinance.Ticker object <LVPR> incomestmt failed to load
yfinance.Ticker object <LVPR> earnings estimates failed to load

ERROR:yfinance:HTTP Error 404:
ERROR:yfinance:$LVPR: possibly delisted; no price data found  (1d 2025-06-01 -> 2025-06-04)

yfinance.Ticker object <LVPR> earnings history failed to load
yfinance.Ticker object <LVPR> revenue estimates failed to load
LVPR  failed
yfinance.Ticker object <LWLG> earnings history failed to load
🔴 LWLG
yfinance.Ticker object <LILMF> balancesheet failed to load
yfinance.Ticker object <LILMF> cashflow failed to load
yfinance.Ticker object <LILMF> incomestmt failed to load
yfinance.Ticker object <LILMF> earnings history failed to load
🔴 LILMF
4 LMB 0.7698662134783766
yfinance.Ticker object <LVGI> balancesheet failed to load
yfinance.Ticker object <LVGI> cashflow failed to load
yfinance.Ticker object <LVGI> incomestmt failed to load
yfinance.Ticker object <LVGI> earnings history failed to load
5 LVGI 0.33333323632056977
yfinance.Ticker object <LIMX> incomestmt failed to load
yfinance.Ticker object <LIMX> earnings history failed to load
6 LIMX -0.6025333404541016
7 LMNR -0.09579634205518742
yfinance.Ticker object <LIMAF> earnings history failed to load
8 LIMAF 0.3284229664175507
9 LINC 0.47740286620714256
10 LECO 0.026537962014757003
11 LNC -0.05579430864378679
12 LIND 0.1469045762258493
13 LIN 0.02768405087979105
yfinance.Ticker object <LINIF> balancesheet failed to load
yfinance.Ticker object <LINIF> cashflow failed to load

ERROR:yfinance:HTTP Error 404:
ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LINIF> eps trend failed to load
yfinance.Ticker object <LINIF> incomestmt failed to load
yfinance.Ticker object <LINIF> earnings estimates failed to load

ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LINIF> earnings history failed to load
yfinance.Ticker object <LINIF> revenue estimates failed to load
14 LINIF 0.0
15 LNN 0.1017704422365973
yfinance.Ticker object <LNDAF> balancesheet failed to load
yfinance.Ticker object <LNDAF> cashflow failed to load
yfinance.Ticker object <LNDAF> earnings history failed to load
16 LNDAF 0.28983302026216856
17 LCTX 0.3877550896283541
yfinance.Ticker object <LINE> incomestmt failed to load
18 LINE -0.264353580515823
yfinance.Ticker object <LINMF> incomestmt failed to load
yfinance.Ticker object <LINMF> earnings history failed to load
19 LINMF -0.4583333268658155
yfinance.Ticker object <BOTY> earnings history failed to load
20 BOTY 0.0
yfinance.Ticker object <LNMG> balancesheet failed to load
yfinance.Ticker object <LNMG> cashflow failed to load
yfinance.Ticker object <LNMG> incomestmt failed to load
yfinance.Ticker object <LNMG> earnings history failed to load
21 LNMG -0.4845361091993929
yfinance.Ticker object <LINUF> balancesheet failed to load
yfinance.Ticker object <LINUF> cashflow failed to load
yfinance.Ticker object <LINUF> incomestmt failed to load
yfinance.Ticker object <LINUF> earnings history failed to load
🔴 LINUF
yfinance.Ticker object <PSBXP> balancesheet failed to load
yfinance.Ticker object <PSBXP> cashflow failed to load
yfinance.Ticker object <PSBXP> incomestmt failed to load
yfinance.Ticker object <PSBXP> earnings history failed to load
23 PSBXP 0.011804406234274123
yfinance.Ticker object <PSBYP> balancesheet failed to load
yfinance.Ticker object <PSBYP> cashflow failed to load
yfinance.Ticker object <PSBYP> incomestmt failed to load
yfinance.Ticker object <PSBYP> earnings history failed to load
24 PSBYP -0.02083339289543278
yfinance.Ticker object <PSBZP> balancesheet failed to load
yfinance.Ticker object <PSBZP> cashflow failed to load
yfinance.Ticker object <PSBZP> incomestmt failed to load
yfinance.Ticker object <PSBZP> earnings history failed to load
25 PSBZP 0.04347823127272034
yfinance.Ticker object <LKREF> balancesheet failed to load
yfinance.Ticker object <LKREF> cashflow failed to load
yfinance.Ticker object <LKREF> incomestmt failed to load
yfinance.Ticker object <LKREF> earnings history failed to load
26 LKREF 0.16556290623918762
yfinance.Ticker object <LGCB> balancesheet failed to load
yfinance.Ticker object <LGCB> cashflow failed to load
yfinance.Ticker object <LGCB> incomestmt failed to load
yfinance.Ticker object <LGCB> earnings history failed to load
27 LGCB 0.5153374452981113
yfinance.Ticker object <LNKB> incomestmt failed to load
28 LNKB 0.005290708403871803
yfinance.Ticker object <LNKS> balancesheet failed to load
yfinance.Ticker object <LNKS> cashflow failed to load
yfinance.Ticker object <LNKS> incomestmt failed to load
yfinance.Ticker object <LNKS> earnings history failed to load
29 LNKS 0.18867930045286038
yfinance.Ticker object <LCGMF> earnings history failed to load
30 LCGMF 0.09999997764825855
yfinance.Ticker object <LEVGQ> balancesheet failed to load
yfinance.Ticker object <LEVGQ> cashflow failed to load
yfinance.Ticker object <LEVGQ> incomestmt failed to load
🔴 LEVGQ
yfinance.Ticker object <LEVWQ> balancesheet failed to load
yfinance.Ticker object <LEVWQ> cashflow failed to load

ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LEVWQ> eps trend failed to load
yfinance.Ticker object <LEVWQ> incomestmt failed to load
yfinance.Ticker object <LEVWQ> earnings estimates failed to load

ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LEVWQ> earnings history failed to load
yfinance.Ticker object <LEVWQ> revenue estimates failed to load
32 LEVWQ 0.0
yfinance.Ticker object <LGHL> balancesheet failed to load
yfinance.Ticker object <LGHL> cashflow failed to load
yfinance.Ticker object <LGHL> earnings history failed to load
33 LGHL -0.18857145309448242
yfinance.Ticker object <LOMLF> incomestmt failed to load
yfinance.Ticker object <LOMLF> earnings history failed to load
34 LOMLF -0.04347828340440215
yfinance.Ticker object <LRRIF> earnings history failed to load
35 LRRIF 0.14210523921697063
yfinance.Ticker object <CUB> cashflow failed to load
yfinance.Ticker object <CUB> incomestmt failed to load
yfinance.Ticker object <CUB> earnings history failed to load
36 CUB 0.027343817666407325
yfinance.Ticker object <LION> balancesheet failed to load
yfinance.Ticker object <LION> cashflow failed to load
yfinance.Ticker object <LION> incomestmt failed to load
37 LION -0.0201883744274344
yfinance.Ticker object <LINRF> balancesheet failed to load
yfinance.Ticker object <LINRF> cashflow failed to load
yfinance.Ticker object <LINRF> incomestmt failed to load
yfinance.Ticker object <LINRF> earnings history failed to load
38 LINRF -0.0165651548479341
39 LIPO 0.13127419453870467
40 LPCN -0.02439022085483674
41 LIQT 0.1062499715946619
yfinance.Ticker object <YVRLF> balancesheet failed to load
yfinance.Ticker object <YVRLF> cashflow failed to load
yfinance.Ticker object <YVRLF> incomestmt failed to load
yfinance.Ticker object <YVRLF> earnings history failed to load
42 YVRLF 5.0000004365574675
yfinance.Ticker object <LQDA> incomestmt failed to load
43 LQDA 0.09542746981421742
44 LQDT -0.2609110795143826
yfinance.Ticker object <LQMT> earnings history failed to load
45 LQMT 0.2500000465661298
yfinance.Ticker object <LSTA> incomestmt failed to load
46 LSTA 0.10638298304062632
yfinance.Ticker object <LSIIF> balancesheet failed to load
yfinance.Ticker object <LSIIF> cashflow failed to load
yfinance.Ticker object <LSIIF> earnings history failed to load
47 LSIIF 0.09839018825828703
48 LAD 0.1061838896412827
49 LAC -0.02222220063700145
50 LAR -0.12558143635322055
yfinance.Ticker object <LTMCF> earnings history failed to load
51 LTMCF -0.07276992579081792
yfinance.Ticker object <LTUM> earnings history failed to load
52 LTUM 0.0
yfinance.Ticker object <LXENF> incomestmt failed to load
yfinance.Ticker object <LXENF> earnings history failed to load
53 LXENF -0.40849670537032245
yfinance.Ticker object <IONGF> incomestmt failed to load
🔴 IONGF
yfinance.Ticker object <LTHCF> incomestmt failed to load
yfinance.Ticker object <LTHCF> earnings history failed to load
55 LTHCF -0.375507360765379
yfinance.Ticker object <LOMEF> incomestmt failed to load
yfinance.Ticker object <LOMEF> earnings history failed to load
56 LOMEF 0.26760557098796406
yfinance.Ticker object <LITRF> incomestmt failed to load
yfinance.Ticker object <LITRF> earnings history failed to load
57 LITRF 0.08967395547235092
yfinance.Ticker object <LISMF> earnings history failed to load
58 LISMF 0.05405406221758272
yfinance.Ticker object <LUVSF> balancesheet failed to load
yfinance.Ticker object <LUVSF> cashflow failed to load
yfinance.Ticker object <LUVSF> earnings history failed to load
59 LUVSF 0.0
yfinance.Ticker object <LBNKF> incomestmt failed to load
60 LBNKF -0.3080645085699103
yfinance.Ticker object <LITSD> incomestmt failed to load
yfinance.Ticker object <LITSD> earnings history failed to load
61 LITSD -0.6458715374963807
yfinance.Ticker object <LFUS> incomestmt failed to load
62 LFUS 0.060447357048357325
63 LIVN 0.12701245260265587
yfinance.Ticker object <GTREF> incomestmt failed to load
yfinance.Ticker object <GTREF> earnings history failed to load
64 GTREF -0.3354385798701727
65 LYV 0.09285771993684133
66 LOB 0.04405409210358285
67 LIVE 1.6788125222974466
yfinance.Ticker object <LVCE> balancesheet failed to load
yfinance.Ticker object <LVCE> cashflow failed to load
yfinance.Ticker object <LVCE> incomestmt failed to load
yfinance.Ticker object <LVCE> earnings history failed to load
68 LVCE 0.5
yfinance.Ticker object <LVO> incomestmt failed to load
69 LVO 0.04269974883128511
70 LPSN -0.03750003818422499
71 RAMP 0.24107814872192435
yfinance.Ticker object <LVVV> balancesheet failed to load
yfinance.Ticker object <LVVV> cashflow failed to load
yfinance.Ticker object <LVVV> incomestmt failed to load
yfinance.Ticker object <LVVV> earnings history failed to load
72 LVVV -0.5
yfinance.Ticker object <LVWR> earnings history failed to load
🔴 LVWR
yfinance.Ticker object <LVWD> balancesheet failed to load
yfinance.Ticker object <LVWD> cashflow failed to load
yfinance.Ticker object <LVWD> incomestmt failed to load
yfinance.Ticker object <LVWD> earnings history failed to load
74 LVWD -0.23076919109158117
yfinance.Ticker object <LMMFF> balancesheet failed to load
yfinance.Ticker object <LMMFF> cashflow failed to load
yfinance.Ticker object <LMMFF> incomestmt failed to load
yfinance.Ticker object <LMMFF> earnings history failed to load
75 LMMFF 0.019230736510486558
yfinance.Ticker object <LXEH> balancesheet failed to load
yfinance.Ticker object <LXEH> cashflow failed to load
yfinance.Ticker object <LXEH> earnings history failed to load
76 LXEH -0.8844192631193439
yfinance.Ticker object <JSGRY> balancesheet failed to load
yfinance.Ticker object <JSGRY> cashflow failed to load
yfinance.Ticker object <JSGRY> incomestmt failed to load
yfinance.Ticker object <JSGRY> earnings history failed to load
77 JSGRY -0.030263678382581493
yfinance.Ticker object <LIXT> earnings history failed to load
78 LIXT 0.11023621086415285
yfinance.Ticker object <LIXTW> earnings history failed to load
79 LIXTW 0.17647049800335407
80 LKQ -0.02235418136487641
yfinance.Ticker object <LLDTF> cashflow failed to load
yfinance.Ticker object <LLDTF> earnings history failed to load
81 LLDTF 0.02105267450750093
yfinance.Ticker object <LYG> cashflow failed to load
yfinance.Ticker object <LYG> earnings history failed to load
82 LYG 0.12647440674106591
83 LMFA 0.4661654020772352
yfinance.Ticker object <LMPX> balancesheet failed to load
yfinance.Ticker object <LMPX> cashflow failed to load
yfinance.Ticker object <LMPX> incomestmt failed to load
yfinance.Ticker object <LMPX> earnings history failed to load
🔴 LMPX
yfinance.Ticker object <LNGNF> balancesheet failed to load
yfinance.Ticker object <LNGNF> cashflow failed to load
yfinance.Ticker object <LNGNF> incomestmt failed to load
yfinance.Ticker object <LNGNF> earnings history failed to load
85 LNGNF -0.5800000119209288
yfinance.Ticker object <LDI> incomestmt failed to load
86 LDI 0.008403352926397583
yfinance.Ticker object <LOAR> incomestmt failed to load
87 LOAR 0.3342427620790071
yfinance.Ticker object <LOBEF> earnings history failed to load
88 LOBEF 0.0
yfinance.Ticker object <LBLCF> earnings history failed to load
89 LBLCF 0.2132160682727663
yfinance.Ticker object <LOBO> balancesheet failed to load
yfinance.Ticker object <LOBO> cashflow failed to load
yfinance.Ticker object <LOBO> earnings history failed to load
90 LOBO -0.224744560940744
yfinance.Ticker object <LCFY> balancesheet failed to load
yfinance.Ticker object <LCFY> cashflow failed to load
yfinance.Ticker object <LCFY> incomestmt failed to load
yfinance.Ticker object <LCFY> earnings history failed to load
91 LCFY -0.16700200377152302
92 LOCL -0.027295317068888058

ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LOCLW> eps trend failed to load
yfinance.Ticker object <LOCLW> earnings estimates failed to load

ERROR:yfinance:HTTP Error 404:

yfinance.Ticker object <LOCLW> earnings history failed to load
yfinance.Ticker object <LOCLW> revenue estimates failed to load
93 LOCLW 0.0
yfinance.Ticker object <LOCM> balancesheet failed to load
yfinance.Ticker object <LOCM> cashflow failed to load
yfinance.Ticker object <LOCM> incomestmt failed to load
🔴 LOCM
yfinance.Ticker object <LZRFY> earnings history failed to load
95 LZRFY 0.2414355614100129
yfinance.Ticker object <LBAS> balancesheet failed to load
yfinance.Ticker object <LBAS> cashflow failed to load
yfinance.Ticker object <LBAS> incomestmt failed to load
yfinance.Ticker object <LBAS> earnings history failed to load
96 LBAS -0.033942573508067765
97 LMT 0.0951041413785961
yfinance.Ticker object <L> earnings history failed to load
98 L -0.010553435855553121
yfinance.Ticker object <LOECF> incomestmt failed to load
yfinance.Ticker object <LOECF> earnings history failed to load
99 LOECF -0.036796578125818435
100 LRFC -0.17832173049559719
101 LGMK -0.8399999947845936
yfinance.Ticker object <LPA> incomestmt failed to load
yfinance.Ticker object <LPA> earnings history failed to load
102 LPA -0.10428099287235723
103 LOGI -0.041978079638772946
yfinance.Ticker object <LOMA> earnings history failed to load
104 LOMA 0.1527138790146114
yfinance.Ticker object <LMRMF> earnings history failed to load
105 LMRMF -0.21999999552965172
yfinance.Ticker object <LONCF> earnings history failed to load
106 LONCF 0.04761907465063339
yfinance.Ticker object <LDNXF> balancesheet failed to load
yfinance.Ticker object <LDNXF> cashflow failed to load
yfinance.Ticker object <LDNXF> earnings history failed to load
107 LDNXF 0.017402986678279962
yfinance.Ticker object <LNSTY> balancesheet failed to load
yfinance.Ticker object <LNSTY> cashflow failed to load
yfinance.Ticker object <LNSTY> earnings history failed to load
108 LNSTY 0.021791659263581876
yfinance.Ticker object <PPLFY> earnings history failed to load
109 PPLFY 0.3622640398021483
yfinance.Ticker object <LNSPF> balancesheet failed to load
yfinance.Ticker object <LNSPF> cashflow failed to load
yfinance.Ticker object <LNSPF> earnings history failed to load
110 LNSPF 0.16379315748934953
111 LGVN -0.25316461044480076
yfinance.Ticker object <XAGE> incomestmt failed to load
yfinance.Ticker object <XAGE> earnings history failed to load
112 XAGE -0.11924120606976218
yfinance.Ticker object <LFIN> balancesheet failed to load
yfinance.Ticker object <LFIN> cashflow failed to load
yfinance.Ticker object <LFIN> incomestmt failed to load
yfinance.Ticker object <LFIN> earnings history failed to load
113 LFIN 0.0
yfinance.Ticker object <LGFRY> balancesheet failed to load
yfinance.Ticker object <LGFRY> cashflow failed to load
yfinance.Ticker object <LGFRY> incomestmt failed to load
yfinance.Ticker object <LGFRY> earnings history failed to load
114 LGFRY -0.1289376794427356
yfinance.Ticker object <LZAGF> balancesheet failed to load
yfinance.Ticker object <LZAGF> cashflow failed to load
yfinance.Ticker object <LZAGF> earnings history failed to load
115 LZAGF 0.03159150950933682
yfinance.Ticker object <LZAGY> balancesheet failed to load
yfinance.Ticker object <LZAGY> cashflow failed to load
yfinance.Ticker object <LZAGY> earnings history failed to load
116 LZAGY 0.07943257746615967
yfinance.Ticker object <LOOP> earnings history failed to load
117 LOOP 0.041666625274553885
🔴 LPTV
yfinance.Ticker object <LRLCF> balancesheet failed to load
yfinance.Ticker object <LRLCF> cashflow failed to load
yfinance.Ticker object <LRLCF> incomestmt failed to load
yfinance.Ticker object <LRLCF> earnings history failed to load
119 LRLCF 0.13541239680750475
yfinance.Ticker object <LRLCY> balancesheet failed to load
yfinance.Ticker object <LRLCY> cashflow failed to load
yfinance.Ticker object <LRLCY> earnings history failed to load
120 LRLCY 0.14748158236415937
yfinance.Ticker object <LSANF> earnings history failed to load
121 LSANF -0.01694913713180618
yfinance.Ticker object <LOTE> balancesheet failed to load
yfinance.Ticker object <LOTE> cashflow failed to load
yfinance.Ticker object <LOTE> incomestmt failed to load
yfinance.Ticker object <LOTE> earnings history failed to load
122 LOTE 9.0
yfinance.Ticker object <LTRY> incomestmt failed to load
yfinance.Ticker object <LTRY> earnings history failed to load
🔴 LTRY
yfinance.Ticker object <LTUS> balancesheet failed to load
yfinance.Ticker object <LTUS> cashflow failed to load
yfinance.Ticker object <LTUS> incomestmt failed to load
yfinance.Ticker object <LTUS> earnings history failed to load
124 LTUS 0.2291666545400712
yfinance.Ticker object <LTSRF> balancesheet failed to load
yfinance.Ticker object <LTSRF> cashflow failed to load
yfinance.Ticker object <LTSRF> incomestmt failed to load
yfinance.Ticker object <LTSRF> earnings history failed to load
125 LTSRF 0.07339450920905455
yfinance.Ticker object <LOT> cashflow failed to load
yfinance.Ticker object <LOT> incomestmt failed to load
yfinance.Ticker object <LOT> earnings history failed to load
126 LOT 0.20555562987739853
127 LPX -0.0013120786290993264

#The Model

In [ ]:
#These are all the S&P500 stocks
stocks= ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK-B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'XYZ', 'BK', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF-B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CAT', 'CBOE', 'CBRE', 'CDW', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COIN', 'CL', 'CMCSA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DDOG', 'DVA', 'DAY', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXE', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LII', 'LLY', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL', 'TXT', 'TMO', 'TJX', 'TKO', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WBA', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB', 'WTW', 'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']
len(stocks)

503

In [ ]:
# no earnings 28th
stocks = ['ACN', 'AZO', 'KMX', 'CCL', 'CTAS', 'CAG', 'STZ', 'CPRT', 'COST', 'DRI', 'FDS', 'JBL', 'LW', 'LEN', 'MKC', 'MU', 'NKE', 'PAYX', 'WBA']
len(stocks)

20

In [ ]:
l = []
l2 = []
for i in range(len(stocks)):
  if datetime.strptime(est_date(stocks[i]), "%Y-%m-%d")>datetime.strptime("2025-09-01","%Y-%m-%d"):
    print(stocks[i], i)
    l.append(stocks[i])
  else:
    l2.append(stocks[i])

len(l)

ADBE 1

1

In [ ]:
stocks = l
print(len(stocks),stocks)

1 ['ADBE']

In [ ]:
l = ['MMM', 'AOS', 'ABT', 'ABBV', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK-B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'XYZ', 'BK', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF-B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'CARR', 'CAT', 'CBOE', 'CBRE', 'CDW', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COIN', 'CL', 'CMCSA', 'COP', 'ED', 'CEG', 'COO', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'CTRA', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DDOG', 'DVA', 'DAY', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXE', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LVS', 'LDOS', 'LII', 'LLY', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PARA', 'PH', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL', 'TXT', 'TMO', 'TJX', 'TKO', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB', 'WTW', 'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

In [ ]:
for i in l:
  stocks.remove(i)
len(stocks)

20

In [ ]:
print(stocks)

['ACN', 'ADBE', 'AZO', 'KMX', 'CCL', 'CTAS', 'CAG', 'STZ', 'CPRT', 'COST', 'DRI', 'FDS', 'JBL', 'LW', 'LEN', 'MKC', 'MU', 'NKE', 'PAYX', 'WBA']

In [ ]:
bull_stocks = []
bull_stocks_proba = []
bear_stocks = []
bear_stocks_proba = []

bullish_stocks = []
bearish_stocks = []
uncertain_stocks = []

for i in range(len(stocks)):
  prediction, proba = fundemental_model(stocks[i])

  if proba > 0.91:
    bull_stocks_proba.append(proba)
    bull_stocks.append(stocks[i])
  if proba < 0.1:
    bear_stocks_proba.append(proba)
    bear_stocks.append(stocks[i])
  if proba > 0.8:
    bullish_stocks.append(stocks[i])
  if proba < 0.15:
    bearish_stocks.append(stocks[i])

  else:
    uncertain_stocks.append(stocks[i])

for i in bull_stocks_proba:
  print(i)

  ADBE
  Successful: 10
        ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
  Failed: 0
        []

🔹 1 🔹 ~83% accuracy 🔹
0.9521009321832054

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

In [ ]:
len(bull_stocks), len(bear_stocks), len(bullish_stocks), len(bearish_stocks)

(132, 74, 231, 119)

In [ ]:
print(f'''
Bull Stocks (91%+ Bull Confidence): {bull_stocks}
Bear Stocks (10%- Bull Confidence): {bear_stocks}
Bullish Stocks (80-91% Bull Confidence): {bullish_stocks}
Bearish Stocks (10-15% Bull Confidence): {bearish_stocks}
''')

Bull Stocks (91%+ Bull Confidence): ['MMM', 'ABT', 'AMD', 'ABNB', 'ALLE', 'ALL', 'GOOGL', 'MO', 'AXP', 'AMP', 'ADI', 'APTV', 'ADSK', 'AVY', 'BKR', 'BALL', 'BX', 'XYZ', 'BK', 'BKNG', 'BSX', 'COF', 'CBOE', 'CDW', 'COR', 'SCHW', 'CMG', 'CFG', 'CTSH', 'CEG', 'GLW', 'CTVA', 'CSX', 'DDOG', 'DAY', 'DE', 'DXCM', 'DOV', 'ECL', 'FAST', 'FIS', 'FITB', 'FSLR', 'F', 'BEN', 'FCX', 'GNRC', 'GD', 'GM', 'GPC', 'GS', 'HLT', 'HOLX', 'HON', 'HST', 'HWM', 'HUBB', 'HII', 'IBM', 'IDXX', 'IR', 'ISRG', 'IRM', 'J', 'JCI', 'JPM', 'KEY', 'KR', 'LVS', 'LDOS', 'LII', 'LIN', 'LYV', 'LMT', 'LOW', 'MTB', 'MLM', 'MCD', 'META', 'MET', 'MGM', 'MCHP', 'MSFT', 'MS', 'NTAP', 'NWSA', 'NWS', 'NDSN', 'NUE', 'ON', 'PLTR', 'PANW', 'PAYC', 'PYPL', 'PNR', 'PM', 'PNC', 'PPG', 'PTC', 'PSA', 'PWR', 'RL', 'RTX', 'RF', 'RSG', 'ROK', 'ROL', 'SBAC', 'NOW', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'TTWO', 'TPR', 'TEL', 'TDY', 'TXT', 'TJX', 'TKO', 'TT', 'TDG', 'USB', 'ULTA', 'VLO', 'VRSK', 'WAB', 'WFC', 'WDAY', 'XYL', 'ZBRA']
Bear Stocks (10%- Bull Confidence): ['ABBV', 'AFL', 'APD', 'ALB', 'ARE', 'AEP', 'AWK', 'AON', 'AIZ', 'AVB', 'BAX', 'BDX', 'BRK-B', 'BMY', 'CPT', 'CNC', 'CL', 'CMCSA', 'COP', 'CCI', 'DVA', 'DVN', 'DTE', 'DD', 'EMN', 'EIX', 'FRT', 'FI', 'FTV', 'GEHC', 'GL', 'DOC', 'HSY', 'HPQ', 'IQV', 'LLY', 'L', 'MKTX', 'MAS', 'MTCH', 'MAA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'NOC', 'NVR', 'OKE', 'PCAR', 'PFE', 'PCG', 'PPL', 'PLD', 'PHM', 'QCOM', 'RVTY', 'ROP', 'SLB', 'SNA', 'SOLV', 'LUV', 'SBUX', 'TGT', 'TER', 'TMO', 'TFC', 'TSN', 'UPS', 'UNH', 'VTR', 'VICI', 'WBD', 'WY', 'WTW']
Bullish Stocks (80-91% Bull Confidence): ['MMM', 'ABT', 'AMD', 'ABNB', 'ALGN', 'ALLE', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AXP', 'AIG', 'AMP', 'ADI', 'AMAT', 'APTV', 'ANET', 'AJG', 'T', 'ADSK', 'AVY', 'BKR', 'BALL', 'BAC', 'BLK', 'BX', 'XYZ', 'BK', 'BKNG', 'BSX', 'AVGO', 'BR', 'BG', 'BXP', 'CHRW', 'CZR', 'COF', 'CAH', 'CARR', 'CBOE', 'CDW', 'COR', 'CNP', 'CF', 'SCHW', 'CHTR', 'CMG', 'CINF', 'C', 'CFG', 'CLX', 'CME', 'KO', 'CTSH', 'CEG', 'GLW', 'CTVA', 'CRWD', 'CSX', 'DDOG', 'DAY', 'DE', 'DAL', 'DXCM', 'DLR', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'ECL', 'EW', 'EA', 'EPAM', 'EQT', 'EFX', 'EQIX', 'ES', 'EXPE', 'FFIV', 'FICO', 'FAST', 'FIS', 'FITB', 'FSLR', 'FE', 'F', 'FTNT', 'FOXA', 'BEN', 'FCX', 'IT', 'GE', 'GNRC', 'GD', 'GM', 'GPC', 'GDDY', 'GS', 'HAS', 'HCA', 'HSIC', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HST', 'HWM', 'HUBB', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'IR', 'PODD', 'ICE', 'ISRG', 'IRM', 'J', 'JCI', 'JPM', 'KEY', 'KEYS', 'KIM', 'KMI', 'KKR', 'KR', 'LHX', 'LRCX', 'LVS', 'LDOS', 'LII', 'LIN', 'LYV', 'LMT', 'LOW', 'MTB', 'MAR', 'MLM', 'MA', 'MCD', 'MCK', 'META', 'MET', 'MGM', 'MCHP', 'MSFT', 'MPWR', 'MCO', 'MS', 'MOS', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NDSN', 'NTRS', 'NRG', 'NUE', 'NVDA', 'NXPI', 'ON', 'ORCL', 'PLTR', 'PANW', 'PAYC', 'PYPL', 'PNR', 'PM', 'PNC', 'PPG', 'PGR', 'PEG', 'PTC', 'PSA', 'PWR', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'RF', 'RSG', 'ROK', 'ROL', 'SPGI', 'SBAC', 'SRE', 'NOW', 'SHW', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'TTWO', 'TPR', 'TEL', 'TDY', 'TSLA', 'TXT', 'TJX', 'TKO', 'TTD', 'TT', 'TDG', 'USB', 'ULTA', 'UAL', 'UHS', 'VLO', 'VRSN', 'VRSK', 'VTRS', 'VST', 'VMC', 'WRB', 'WAB', 'WMT', 'WM', 'WFC', 'WMB', 'WDAY', 'WYNN', 'XYL', 'ZBRA']
Bearish Stocks (10-15% Bull Confidence): ['ABBV', 'AFL', 'APD', 'AKAM', 'ALB', 'ARE', 'LNT', 'AEP', 'AWK', 'AON', 'ADM', 'AIZ', 'ATO', 'AVB', 'BAX', 'BDX', 'BRK-B', 'BIIB', 'BMY', 'CPT', 'CNC', 'CRL', 'CB', 'CMS', 'CL', 'CMCSA', 'COP', 'COO', 'CSGP', 'CTRA', 'CCI', 'DVA', 'DVN', 'FANG', 'DOW', 'DHI', 'DTE', 'DD', 'EMN', 'EIX', 'ELV', 'EQR', 'EG', 'EXC', 'EXE', 'XOM', 'FRT', 'FI', 'FTV', 'GRMN', 'GEHC', 'GIS', 'GL', 'DOC', 'HSY', 'HPQ', 'IPG', 'IVZ', 'INVH', 'IQV', 'KVUE', 'KMB', 'LLY', 'LKQ', 'L', 'MKTX', 'MAS', 'MTCH', 'MDT', 'MAA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MSI', 'NOC', 'NCLH', 'NVR', 'ORLY', 'OKE', 'OTIS', 'PCAR', 'PFE', 'PCG', 'PSX', 'PPL', 'PFG', 'PLD', 'PHM', 'QCOM', 'REGN', 'RVTY', 'ROP', 'SLB', 'SJM', 'SNA', 'SOLV', 'LUV', 'SWK', 'SBUX', 'SMCI', 'TRGP', 'TGT', 'TER', 'TMO', 'TFC', 'TSN', 'UDR', 'UNP', 'UPS', 'UNH', 'VTR', 'VZ', 'VICI', 'WBD', 'WAT', 'WY', 'WTW', 'YUM']

In [ ]:
#as of sep28, added to TAx
good_stocks = ['ADBE', 'ADSK', 'DLTR', 'PANW', 'TJX','wmt' ,'DE', 'LOW', 'NTAP', 'ULTA',"hd","wday","ndsn","adi",'ABT', 'AMD', 'ABNB', 'ALLE', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AXP', 'AIG', 'AMP', 'APTV', 'AVY', 'BALL', 'BLK', 'BX', 'XYZ', 'BK', 'BKNG', 'BSX', 'BR', 'COF', 'CAH', 'CARR', 'CBOE', 'CDW', 'COR', 'SCHW', 'CHTR', 'CMG', 'CFG', 'CTSH', 'CEG', 'GLW', 'CTVA', 'CSX', 'DDOG', 'DAY', 'DAL', 'DXCM', 'D', 'DOV', 'EXPE', 'FAST', 'FIS', 'FITB', 'FSLR', 'F', 'BEN', 'FCX', 'GE', 'GNRC', 'GD', 'GPC', 'GS', 'HCA', 'HLT', 'HOLX', 'HON', 'HST', 'HWM', 'HUBB', 'HII', 'IBM', 'IDXX', 'IR', 'ISRG', 'IRM', 'J', 'JCI', 'JPM', 'KEY', 'KKR', 'LVS', 'LDOS', 'LII', 'LIN', 'LYV', 'LMT', 'MTB', 'MLM', 'MA', 'MCD', 'META', 'MET', 'MGM', 'MCHP', 'MSFT', 'MCO', 'MS', 'NWSA', 'NWS', 'NRG', 'NUE', 'ON', 'PLTR', 'PAYC', 'PYPL', 'PNR', 'PM', 'PNC', 'PPG', 'PTC', 'PSA', 'PWR', 'RL', 'RTX', 'RF', 'RSG', 'ROK', 'ROL', 'SBAC', 'NOW', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'TTWO', 'TEL', 'TDY', 'TXT', 'TKO', 'TDG', 'USB', 'VLO', 'VRSK', 'WAB', 'WFC', 'XYL', 'ZBRA']
len(good_stocks)

145

In [ ]:
stock = input("Enter stock symbol: ")
prediction, proba = fundemental_model(stock)

print(f''' {prediction}

⛋ Prediction made for {est_date(stock)} ⛋


⛋ Predicted Probabilities:  ⛋
               Bull: {proba},
               Bear: {1-proba}


''')

Enter stock symbol: hd

  hd
  Successful: 10
        ['balancesheet', 'cashflow', 'analyst_target_eps', 'incomestmt', 'earnings_est', 'earnings_hist', 'earnings_hist_est', 'earnings_hist_est_eps', 'rev_est', 'meta']
  Failed: 0
        []

🔹 1 🔹 ~69% accuracy 🔹
 1

⛋ Prediction made for 2025-10-31 ⛋


⛋ Predicted Probabilities:  ⛋
               Bull: 0.8593330493237588,
               Bear: 0.14066695067624124

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

#Debugging

In [ ]:
stock = "aapl"

weighted_prediction = []
predictions = []

successful, failed, balancesheet, cashflow, analyst_target_eps, incomestmt, earnings_est, earnings_hist, earnings_hist_est, earnings_hist_est_eps, rev_est, meta = transformed_testing_data(stock)
print(f'''
{stock}
Successful: {len(successful)}
    {successful}
Failed: {len(failed)}
    {failed}
''')
if len(failed)==10:
  print("🔺🔺🔺 error occured 🔺🔺🔺")
  return f"error with {stock}",f"error with {stock}",f"error with {stock}",f"error with {stock}"

else:
#if "balancesheet" in successful:
  try:
      pred = clf_balancesheet.predict_proba(balancesheet)
      #weighted_prediction.append(pred[0,1]*(3025/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3025/32906))
      predictions.append(-100)
      print(f"Error occurred with balancesheet: {e}")

  #if "cashflow" in successful:
  try:
      pred = clf_cashflow.predict_proba(cashflow)
      #weighted_prediction.append(pred[0,1]*(3025/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3025/32906))
      predictions.append(-100)
      print(f"Error occurred with cashflow: {e}")

  #if "analyst_target_eps" in successful:
  try:
      pred = clf_analystpricetarget_eps.predict_proba(analyst_target_eps)
      #weighted_prediction.append(pred[0,1]*(3025/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3025/32906))
      predictions.append(-100)
      print(f"Error occurred with analyst_target_eps: {e}")

  #if "incomestmt" in successful:
  try:
      pred = clf_income_statement.predict_proba(incomestmt)
      #weighted_prediction.append(pred[0,1]*(3481/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3481/32906))
      predictions.append(-100)
      print(f"Error occurred with incomestmt: {e}")

  #if "earnings_est" in successful:
  try:
      pred = clf_earnings_est.predict_proba(earnings_est)
      #weighted_prediction.append(pred[0,1]*(2916/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(2916/32906))
      predictions.append(-100)
      print(f"Error occurred with earnings_est: {e}")

  #if "earnings_hist" in successful:
  try:
      pred = clf_earnings_hist.predict_proba(earnings_hist)
      #weighted_prediction.append(pred[0,1]*(3600/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3600/32906))
      predictions.append(-100)
      print(f"Error occurred with earnings_hist: {e}")

  #if "earnings_hist_est" in successful:
  try:
      pred = clf_earnings_hist_est.predict_proba(earnings_hist_est)
      #weighted_prediction.append(pred[0,1]*(4225/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(4225/32906))
      predictions.append(-100)
      print(f"Error occurred with earnings_hist_est: {e}")

  #if "earnings_hist_est_eps" in successful:
  try:
      pred = clf_earnings_hist_est_eps.predict_proba(earnings_hist_est_eps)
      #weighted_prediction.append(pred[0,1]*(3844/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3844/32906))
      predictions.append(-100)
      print(f"Error occurred with earnings_hist_est_eps: {e}")

  #if "rev_est" in successful:
  try:
      pred = clf_rev_est.predict_proba(rev_est)
      #weighted_prediction.append(pred[0,1]*(2401/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(2401/32906))
      predictions.append(-100)
      print(f"Error occurred with rev_est: {e}")

  #if "meta" in successful:
  try:
      pred = clf_meta.predict_proba(meta)
      #weighted_prediction.append(pred[0,1]*(3364/32906))
      predictions.append(pred[0,1])
  except Exception as e:
      #weighted_prediction.append(0.5*(3364/32906))
      predictions.append(-100)
      print(f"Error occurred with meta: {e}")


predictions = pd.DataFrame({"":predictions}).transpose()
final_estimator_pred = clf_final_estimator.predict_proba(predictions)
if final_estimator_pred[0,1] >0.91:
  prediction = 1
  print("🔹", prediction,"🔹", "~83% accuracy 🔹")

elif final_estimator_pred[0,1]<0.1:
  prediction = -1
  print("🔹", prediction,"🔹", "~86% accuracy 🔹")

else:
    if final_estimator_pred[0,1] >0.8:
      prediction = 1
      print("🔹", prediction,"🔹", "~69% accuracy 🔹")

    elif final_estimator_pred[0,1]<0.15:
      prediction = -1
      print("🔹", prediction,"🔹", "~69% accuracy 🔹")
    else:
      prediction = "unknown"
      print("🔸 Uncertain 🔸")

In [ ]:
ticker = yf.Ticker("aapl")
ticker = ticker.earnings_estimate
print(ticker.shape, ticker)

(4, 6)             avg   low  high  yearAgoEps  numberOfAnalysts  growth
period
0q      1.75844  1.63  1.82      0.9700                29  0.8128
+1q     2.48513  2.29  2.67      2.4000                23  0.0355
0y      7.36760  7.09  7.47      6.0800                40  0.2118
+1y     7.98158  7.13  9.00      7.3676                40  0.0833

In [ ]:
df_earnings_est

,avg_1,low_1,high_1,numberOfAnalysts_1,avg_2,low_2,high_2,numberOfAnalysts_2,avg_3,low_3,high_3,numberOfAnalysts_3,avg_4,low_4,high_4,numberOfAnalysts_4
0,0.42604,-0.08,0.6777,18,0.59582,0.09,1.00345,18,3.28272,2.040,4.09855,19,4.67772,2.84000,7.33553,18
1,-0.25083,-0.40,-0.1400,12,-0.02905,-0.22,0.05000,12,-0.42807,-0.880,-0.24000,17,-0.19185,-0.84000,0.07000,16
2,1.29455,1.25,1.3200,33,1.20223,1.12,1.30000,31,5.09029,4.740,5.52000,43,5.62721,4.70000,6.22000,43
3,2.21126,2.01,2.3800,8,1.20013,0.92,1.41000,8,7.16837,6.300,9.38000,12,5.98424,4.05758,7.23000,14
4,0.92636,0.46,1.3000,10,1.51123,1.33,1.69000,10,3.87868,3.803,3.95000,18,4.36711,4.30000,4.64000,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,4.70333,4.14,4.9600,33,3.84581,3.74,4.10392,32,15.00808,14.900,15.38465,37,16.32581,15.66000,17.50000,37
540,0.13000,0.13,0.1300,1,0.15000,0.15,0.15000,1,0.65000,0.650,0.65000,1,0.60500,0.56000,0.65000,2
541,0.02000,0.02,0.0200,1,-0.03000,-0.03,-0.03000,1,1.25000,1.250,1.25000,1,1.29000,1.29000,1.29000,1
542,0.41592,0.38,0.4500,14,0.43831,0.40,0.48000,13,1.64035,1.550,1.75000,18,1.90951,1.71000,2.04000,18
543,1.80612,1.70,2.0500,15,1.92237,1.80,2.17000,14,7.39730,6.750,8.11000,17,8.23348,7.17000,8.99986,16

In [ ]:
ticker = yf.Ticker('ko')
df = ticker.quarterly_cash_flow

In [ ]:
df

,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Free Cash Flow,4.564000e+09,3.369000e+09,-5.511000e+09,3.148000e+09,-1.728000e+09
Repurchase Of Capital Stock,-1.720000e+08,-1.020000e+08,-3.700000e+08,-5.670000e+08,-3.540000e+08
Repayment Of Debt,-1.536000e+09,-1.031000e+09,-1.599000e+09,-1.608000e+09,-3.191000e+09
Issuance Of Debt,-4.660000e+08,-1.160000e+08,5.436000e+09,7.630000e+08,4.466000e+09
Issuance Of Capital Stock,2.000000e+07,6.400000e+07,1.590000e+08,3.000000e+07,2.800000e+08
Capital Expenditure,-4.790000e+08,-4.420000e+08,-3.090000e+08,-8.030000e+08,-4.690000e+08
End Cash Position,1.336400e+10,1.020300e+10,8.417000e+09,1.148800e+10,1.416100e+10
Other Cash Adjustment Outside Changein Cash,NaN,NaN,-3.970000e+08,NaN,NaN
Beginning Cash Position,1.020300e+10,8.417000e+09,1.148800e+10,1.416100e+10,1.391300e+10
Effect Of Exchange Rate Changes,3.000000e+06,1.690000e+08,1.630000e+08,-3.570000e+08,9.100000e+07
Changes In Cash,3.158000e+09,1.220000e+09,-2.837000e+09,-2.316000e+09,1.570000e+08
Financing Cash Flow,-3.140000e+09,-3.380000e+09,3.432000e+09,-5.484000e+09,-8.940000e+08
Cash Flow From Continuing Financing Activities,-3.140000e+09,-3.380000e+09,3.432000e+09,-5.484000e+09,-8.940000e+08
Net Other Financing Charges,1.122000e+09,-1.000000e+06,-1.050000e+08,-1.700000e+07,-5.000000e+06
Cash Dividends Paid,-2.108000e+09,-2.194000e+09,-8.900000e+07,-4.085000e+09,-2.090000e+09
Common Stock Dividend Paid,-2.108000e+09,-2.194000e+09,-8.900000e+07,-4.085000e+09,-2.090000e+09
Net Common Stock Issuance,-1.520000e+08,-3.800000e+07,-2.110000e+08,-5.370000e+08,-7.400000e+07
Common Stock Payments,-1.720000e+08,-1.020000e+08,-3.700000e+08,-5.670000e+08,-3.540000e+08
Common Stock Issuance,2.000000e+07,6.400000e+07,1.590000e+08,3.000000e+07,2.800000e+08
Net Issuance Payments Of Debt,-2.002000e+09,-1.147000e+09,3.837000e+09,-8.450000e+08,1.275000e+09
Net Long Term Debt Issuance,-2.002000e+09,-1.147000e+09,3.837000e+09,-8.450000e+08,1.275000e+09
Long Term Debt Payments,-1.536000e+09,-1.031000e+09,-1.599000e+09,-1.608000e+09,-3.191000e+09
Long Term Debt Issuance,-4.660000e+08,-1.160000e+08,5.436000e+09,7.630000e+08,4.466000e+09
Investing Cash Flow,1.255000e+09,7.890000e+08,-1.067000e+09,-7.830000e+08,2.310000e+09
Cash Flow From Continuing Investing Activities,1.255000e+09,7.890000e+08,-1.067000e+09,-7.830000e+08,2.310000e+09
Net Other Investing Changes,1.840000e+08,3.000000e+08,3.000000e+07,-6.400000e+07,4.420000e+08
Net Investment Purchase And Sale,1.672000e+09,8.380000e+08,-1.502000e+09,2.220000e+08,1.892000e+09
Sale Of Investment,2.099000e+09,1.196000e+09,1.005000e+09,1.464000e+09,2.463000e+09
Purchase Of Investment,-4.270000e+08,-3.580000e+08,-2.507000e+09,-1.242000e+09,-5.710000e+08
Net Business Purchase And Sale,-1.300000e+08,8.800000e+07,7.060000e+08,-1.450000e+08,4.330000e+08
Sale Of Business,4.700000e+07,2.250000e+08,7.480000e+08,1.700000e+07,5.610000e+08
Purchase Of Business,-1.770000e+08,-1.370000e+08,-4.200000e+07,-1.620000e+08,-1.280000e+08
Net PPE Purchase And Sale,-4.710000e+08,-4.370000e+08,-3.010000e+08,-7.960000e+08,-4.570000e+08
Sale Of PPE,8.000000e+06,5.000000e+06,8.000000e+06,7.000000e+06,1.200000e+07
Purchase Of PPE,-4.790000e+08,-4.420000e+08,-3.090000e+08,-8.030000e+08,-4.690000e+08
Operating Cash Flow,5.043000e+09,3.811000e+09,-5.202000e+09,3.951000e+09,-1.259000e+09
Cash Flow From Continuing Operating Activities,5.043000e+09,3.811000e+09,-5.202000e+09,3.951000e+09,-1.259000e+09
Change In Working Capital,1.191000e+09,-7.100000e+08,-8.521000e+09,1.609000e+09,-4.859000e+09
Other Non Cash Items,2.460000e+08,7.000000e+07,-2.270000e+08,-5.700000e+07,6.060000e+08
Stock Based Compensation,7.400000e+07,6.700000e+07,6.300000e+07,7.900000e+07,6.700000e+07
Deferred Tax,3.700000e+07,3.640000e+08,9.500000e+07,-1.100000e+07,2.020000e+08
Deferred Income Tax,3.700000e+07,3.640000e+08,9.500000e+07,-1.100000e+07,2.020000e+08
Depreciation Amortization Depletion,2.680000e+08,2.790000e+08,2.670000e+08,2.760000e+08,2.680000e+08
Depreciation And Amortization,2.680000e+08,2.790000e+08,2.670000e+08,2.760000e+08,2.680000e+08
Operating Gains Losses,-4.560000e+08,-6.200000e+07,-2.140000e+08,-1.580000e+08,-3.930000e+08
Earnings Losses From Equity Investments,-4.720000e+08,-1.230000e+08,-2.640000e+08,-1.090000e+08,-4.190000e+08
Net Foreign Currency Exchange Gain Loss,1.600000e+07,6.100000e+07,5.000000e+07,-4.900000e+07,2.600000e+07
Net Income From Continuing Operations,3.683000e+09,3.803000e+09,3.335000e+09,2.213000e+09,2.850000e+09